version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test -race ./...

builds:
  - id: themegen
    main: ./cmd/themegen
    binary: themegen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    flags:
      - -trimpath

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - DEFAULT_THEMES.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: tj-smith47
    name: gothememe
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ```bash
    go get github.com/tj-smith47/gothememe@v{{.Version}}
    ```

    ## What's Changed

    See the [CHANGELOG](https://github.com/tj-smith47/gothememe/blob/master/CHANGELOG.md) for details.

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
