// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeAtomOneDarkInstance is the Atom One Dark color theme singleton.
var themeAtomOneDarkInstance gothememe.Theme = &themeAtomOneDark{}

// themeAtomOneDark implements the Atom One Dark theme.
type themeAtomOneDark struct{}

func (t *themeAtomOneDark) ID() string          { return "atom_one_dark" }
func (t *themeAtomOneDark) DisplayName() string { return "Atom One Dark" }
func (t *themeAtomOneDark) Description() string { return "Atom One Dark color theme" }
func (t *themeAtomOneDark) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeAtomOneDark) License() string     { return "MIT" }
func (t *themeAtomOneDark) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeAtomOneDark) IsDark() bool { return true }

// Background colors
func (t *themeAtomOneDark) Background() gothememe.Color          { return gothememe.Hex("#21252b") }
func (t *themeAtomOneDark) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#21252b") }
func (t *themeAtomOneDark) Surface() gothememe.Color             { return gothememe.Hex("#323844") }
func (t *themeAtomOneDark) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#767676") }

// Text colors
func (t *themeAtomOneDark) TextPrimary() gothememe.Color   { return gothememe.Hex("#abb2bf") }
func (t *themeAtomOneDark) TextSecondary() gothememe.Color { return gothememe.Hex("#abb2bf") }
func (t *themeAtomOneDark) TextMuted() gothememe.Color     { return gothememe.Hex("#767676") }
func (t *themeAtomOneDark) TextInverted() gothememe.Color  { return gothememe.Hex("#21252b") }

// Accent/Brand colors
func (t *themeAtomOneDark) Accent() gothememe.Color          { return gothememe.Hex("#61afef") }
func (t *themeAtomOneDark) AccentSecondary() gothememe.Color { return gothememe.Hex("#c678dd") }
func (t *themeAtomOneDark) Brand() gothememe.Color           { return gothememe.Hex("#61afef") }

// Border colors
func (t *themeAtomOneDark) Border() gothememe.Color       { return gothememe.Hex("#767676") }
func (t *themeAtomOneDark) BorderSubtle() gothememe.Color { return gothememe.Hex("#21252b") }
func (t *themeAtomOneDark) BorderStrong() gothememe.Color { return gothememe.Hex("#abb2bf") }

// Semantic colors
func (t *themeAtomOneDark) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#98c379").WithAlpha(0.1),
		Border:     gothememe.Hex("#98c379").WithAlpha(0.3),
		Text:       gothememe.Hex("#98c379"),
	}
}

func (t *themeAtomOneDark) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e5c07b").WithAlpha(0.1),
		Border:     gothememe.Hex("#e5c07b").WithAlpha(0.3),
		Text:       gothememe.Hex("#e5c07b"),
	}
}

func (t *themeAtomOneDark) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e06c75").WithAlpha(0.1),
		Border:     gothememe.Hex("#e06c75").WithAlpha(0.3),
		Text:       gothememe.Hex("#e06c75"),
	}
}

func (t *themeAtomOneDark) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#56b6c2").WithAlpha(0.1),
		Border:     gothememe.Hex("#56b6c2").WithAlpha(0.3),
		Text:       gothememe.Hex("#56b6c2"),
	}
}

// ANSI colors
func (t *themeAtomOneDark) Black() gothememe.Color        { return gothememe.Hex("#21252b") }
func (t *themeAtomOneDark) Red() gothememe.Color          { return gothememe.Hex("#e06c75") }
func (t *themeAtomOneDark) Green() gothememe.Color        { return gothememe.Hex("#98c379") }
func (t *themeAtomOneDark) Yellow() gothememe.Color       { return gothememe.Hex("#e5c07b") }
func (t *themeAtomOneDark) Blue() gothememe.Color         { return gothememe.Hex("#61afef") }
func (t *themeAtomOneDark) Purple() gothememe.Color       { return gothememe.Hex("#c678dd") }
func (t *themeAtomOneDark) Cyan() gothememe.Color         { return gothememe.Hex("#56b6c2") }
func (t *themeAtomOneDark) White() gothememe.Color        { return gothememe.Hex("#abb2bf") }
func (t *themeAtomOneDark) BrightBlack() gothememe.Color  { return gothememe.Hex("#767676") }
func (t *themeAtomOneDark) BrightRed() gothememe.Color    { return gothememe.Hex("#e06c75") }
func (t *themeAtomOneDark) BrightGreen() gothememe.Color  { return gothememe.Hex("#98c379") }
func (t *themeAtomOneDark) BrightYellow() gothememe.Color { return gothememe.Hex("#e5c07b") }
func (t *themeAtomOneDark) BrightBlue() gothememe.Color   { return gothememe.Hex("#61afef") }
func (t *themeAtomOneDark) BrightPurple() gothememe.Color { return gothememe.Hex("#c678dd") }
func (t *themeAtomOneDark) BrightCyan() gothememe.Color   { return gothememe.Hex("#56b6c2") }
func (t *themeAtomOneDark) BrightWhite() gothememe.Color  { return gothememe.Hex("#abb2bf") }

// Code/Syntax highlighting colors
func (t *themeAtomOneDark) CodeBackground() gothememe.Color  { return gothememe.Hex("#21252b") }
func (t *themeAtomOneDark) CodeText() gothememe.Color        { return gothememe.Hex("#abb2bf") }
func (t *themeAtomOneDark) CodeComment() gothememe.Color     { return gothememe.Hex("#767676") }
func (t *themeAtomOneDark) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c678dd") }
func (t *themeAtomOneDark) CodeString() gothememe.Color      { return gothememe.Hex("#98c379") }
func (t *themeAtomOneDark) CodeNumber() gothememe.Color      { return gothememe.Hex("#e5c07b") }
func (t *themeAtomOneDark) CodeFunction() gothememe.Color    { return gothememe.Hex("#61afef") }
func (t *themeAtomOneDark) CodeOperator() gothememe.Color    { return gothememe.Hex("#e06c75") }
func (t *themeAtomOneDark) CodePunctuation() gothememe.Color { return gothememe.Hex("#abb2bf") }
func (t *themeAtomOneDark) CodeVariable() gothememe.Color    { return gothememe.Hex("#56b6c2") }
func (t *themeAtomOneDark) CodeConstant() gothememe.Color    { return gothememe.Hex("#e5c07b") }
func (t *themeAtomOneDark) CodeType() gothememe.Color        { return gothememe.Hex("#56b6c2") }
