// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeBlulocoLightInstance is the Bluloco Light color theme singleton.
var themeBlulocoLightInstance gothememe.Theme = &themeBlulocoLight{}

// themeBlulocoLight implements the Bluloco Light theme.
type themeBlulocoLight struct{}

func (t *themeBlulocoLight) ID() string          { return "bluloco_light" }
func (t *themeBlulocoLight) DisplayName() string { return "Bluloco Light" }
func (t *themeBlulocoLight) Description() string { return "Bluloco Light color theme" }
func (t *themeBlulocoLight) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeBlulocoLight) License() string     { return "MIT" }
func (t *themeBlulocoLight) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeBlulocoLight) IsDark() bool { return false }

// Background colors
func (t *themeBlulocoLight) Background() gothememe.Color          { return gothememe.Hex("#f9f9f9") }
func (t *themeBlulocoLight) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#373a41") }
func (t *themeBlulocoLight) Surface() gothememe.Color             { return gothememe.Hex("#daf0ff") }
func (t *themeBlulocoLight) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#676a77") }

// Text colors
func (t *themeBlulocoLight) TextPrimary() gothememe.Color   { return gothememe.Hex("#373a41") }
func (t *themeBlulocoLight) TextSecondary() gothememe.Color { return gothememe.Hex("#babbc2") }
func (t *themeBlulocoLight) TextMuted() gothememe.Color     { return gothememe.Hex("#676a77") }
func (t *themeBlulocoLight) TextInverted() gothememe.Color  { return gothememe.Hex("#f9f9f9") }

// Accent/Brand colors
func (t *themeBlulocoLight) Accent() gothememe.Color          { return gothememe.Hex("#275fe4") }
func (t *themeBlulocoLight) AccentSecondary() gothememe.Color { return gothememe.Hex("#823ff1") }
func (t *themeBlulocoLight) Brand() gothememe.Color           { return gothememe.Hex("#275fe4") }

// Border colors
func (t *themeBlulocoLight) Border() gothememe.Color       { return gothememe.Hex("#676a77") }
func (t *themeBlulocoLight) BorderSubtle() gothememe.Color { return gothememe.Hex("#373a41") }
func (t *themeBlulocoLight) BorderStrong() gothememe.Color { return gothememe.Hex("#babbc2") }

// Semantic colors
func (t *themeBlulocoLight) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#23974a").WithAlpha(0.1),
		Border:     gothememe.Hex("#23974a").WithAlpha(0.3),
		Text:       gothememe.Hex("#23974a"),
	}
}

func (t *themeBlulocoLight) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#df631c").WithAlpha(0.1),
		Border:     gothememe.Hex("#df631c").WithAlpha(0.3),
		Text:       gothememe.Hex("#df631c"),
	}
}

func (t *themeBlulocoLight) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d52753").WithAlpha(0.1),
		Border:     gothememe.Hex("#d52753").WithAlpha(0.3),
		Text:       gothememe.Hex("#d52753"),
	}
}

func (t *themeBlulocoLight) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#27618d").WithAlpha(0.1),
		Border:     gothememe.Hex("#27618d").WithAlpha(0.3),
		Text:       gothememe.Hex("#27618d"),
	}
}

// ANSI colors
func (t *themeBlulocoLight) Black() gothememe.Color        { return gothememe.Hex("#373a41") }
func (t *themeBlulocoLight) Red() gothememe.Color          { return gothememe.Hex("#d52753") }
func (t *themeBlulocoLight) Green() gothememe.Color        { return gothememe.Hex("#23974a") }
func (t *themeBlulocoLight) Yellow() gothememe.Color       { return gothememe.Hex("#df631c") }
func (t *themeBlulocoLight) Blue() gothememe.Color         { return gothememe.Hex("#275fe4") }
func (t *themeBlulocoLight) Purple() gothememe.Color       { return gothememe.Hex("#823ff1") }
func (t *themeBlulocoLight) Cyan() gothememe.Color         { return gothememe.Hex("#27618d") }
func (t *themeBlulocoLight) White() gothememe.Color        { return gothememe.Hex("#babbc2") }
func (t *themeBlulocoLight) BrightBlack() gothememe.Color  { return gothememe.Hex("#676a77") }
func (t *themeBlulocoLight) BrightRed() gothememe.Color    { return gothememe.Hex("#ff6480") }
func (t *themeBlulocoLight) BrightGreen() gothememe.Color  { return gothememe.Hex("#3cbc66") }
func (t *themeBlulocoLight) BrightYellow() gothememe.Color { return gothememe.Hex("#c5a332") }
func (t *themeBlulocoLight) BrightBlue() gothememe.Color   { return gothememe.Hex("#0099e1") }
func (t *themeBlulocoLight) BrightPurple() gothememe.Color { return gothememe.Hex("#ce33c0") }
func (t *themeBlulocoLight) BrightCyan() gothememe.Color   { return gothememe.Hex("#6d93bb") }
func (t *themeBlulocoLight) BrightWhite() gothememe.Color  { return gothememe.Hex("#d3d3d3") }

// Code/Syntax highlighting colors
func (t *themeBlulocoLight) CodeBackground() gothememe.Color  { return gothememe.Hex("#f9f9f9") }
func (t *themeBlulocoLight) CodeText() gothememe.Color        { return gothememe.Hex("#373a41") }
func (t *themeBlulocoLight) CodeComment() gothememe.Color     { return gothememe.Hex("#676a77") }
func (t *themeBlulocoLight) CodeKeyword() gothememe.Color     { return gothememe.Hex("#823ff1") }
func (t *themeBlulocoLight) CodeString() gothememe.Color      { return gothememe.Hex("#23974a") }
func (t *themeBlulocoLight) CodeNumber() gothememe.Color      { return gothememe.Hex("#df631c") }
func (t *themeBlulocoLight) CodeFunction() gothememe.Color    { return gothememe.Hex("#275fe4") }
func (t *themeBlulocoLight) CodeOperator() gothememe.Color    { return gothememe.Hex("#d52753") }
func (t *themeBlulocoLight) CodePunctuation() gothememe.Color { return gothememe.Hex("#373a41") }
func (t *themeBlulocoLight) CodeVariable() gothememe.Color    { return gothememe.Hex("#27618d") }
func (t *themeBlulocoLight) CodeConstant() gothememe.Color    { return gothememe.Hex("#c5a332") }
func (t *themeBlulocoLight) CodeType() gothememe.Color        { return gothememe.Hex("#6d93bb") }
