// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeCobalt2Instance is the Cobalt2 color theme singleton.
var themeCobalt2Instance gothememe.Theme = &themeCobalt2{}

// themeCobalt2 implements the Cobalt2 theme.
type themeCobalt2 struct{}

func (t *themeCobalt2) ID() string          { return "cobalt2" }
func (t *themeCobalt2) DisplayName() string { return "Cobalt2" }
func (t *themeCobalt2) Description() string { return "Cobalt2 color theme" }
func (t *themeCobalt2) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeCobalt2) License() string     { return "MIT" }
func (t *themeCobalt2) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeCobalt2) IsDark() bool        { return true }

// Background colors
func (t *themeCobalt2) Background() gothememe.Color          { return gothememe.Hex("#132738") }
func (t *themeCobalt2) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeCobalt2) Surface() gothememe.Color             { return gothememe.Hex("#18354f") }
func (t *themeCobalt2) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#555555") }

// Text colors
func (t *themeCobalt2) TextPrimary() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeCobalt2) TextSecondary() gothememe.Color { return gothememe.Hex("#bbbbbb") }
func (t *themeCobalt2) TextMuted() gothememe.Color     { return gothememe.Hex("#555555") }
func (t *themeCobalt2) TextInverted() gothememe.Color  { return gothememe.Hex("#132738") }

// Accent/Brand colors
func (t *themeCobalt2) Accent() gothememe.Color          { return gothememe.Hex("#1460d2") }
func (t *themeCobalt2) AccentSecondary() gothememe.Color { return gothememe.Hex("#ff005d") }
func (t *themeCobalt2) Brand() gothememe.Color           { return gothememe.Hex("#1460d2") }

// Border colors
func (t *themeCobalt2) Border() gothememe.Color       { return gothememe.Hex("#555555") }
func (t *themeCobalt2) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeCobalt2) BorderStrong() gothememe.Color { return gothememe.Hex("#bbbbbb") }

// Semantic colors
func (t *themeCobalt2) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#38de21").WithAlpha(0.1),
		Border:     gothememe.Hex("#38de21").WithAlpha(0.3),
		Text:       gothememe.Hex("#38de21"),
	}
}

func (t *themeCobalt2) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ffe50a").WithAlpha(0.1),
		Border:     gothememe.Hex("#ffe50a").WithAlpha(0.3),
		Text:       gothememe.Hex("#ffe50a"),
	}
}

func (t *themeCobalt2) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff0000").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff0000").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff0000"),
	}
}

func (t *themeCobalt2) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00bbbb").WithAlpha(0.1),
		Border:     gothememe.Hex("#00bbbb").WithAlpha(0.3),
		Text:       gothememe.Hex("#00bbbb"),
	}
}

// ANSI colors
func (t *themeCobalt2) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeCobalt2) Red() gothememe.Color          { return gothememe.Hex("#ff0000") }
func (t *themeCobalt2) Green() gothememe.Color        { return gothememe.Hex("#38de21") }
func (t *themeCobalt2) Yellow() gothememe.Color       { return gothememe.Hex("#ffe50a") }
func (t *themeCobalt2) Blue() gothememe.Color         { return gothememe.Hex("#1460d2") }
func (t *themeCobalt2) Purple() gothememe.Color       { return gothememe.Hex("#ff005d") }
func (t *themeCobalt2) Cyan() gothememe.Color         { return gothememe.Hex("#00bbbb") }
func (t *themeCobalt2) White() gothememe.Color        { return gothememe.Hex("#bbbbbb") }
func (t *themeCobalt2) BrightBlack() gothememe.Color  { return gothememe.Hex("#555555") }
func (t *themeCobalt2) BrightRed() gothememe.Color    { return gothememe.Hex("#f40e17") }
func (t *themeCobalt2) BrightGreen() gothememe.Color  { return gothememe.Hex("#3bd01d") }
func (t *themeCobalt2) BrightYellow() gothememe.Color { return gothememe.Hex("#edc809") }
func (t *themeCobalt2) BrightBlue() gothememe.Color   { return gothememe.Hex("#5555ff") }
func (t *themeCobalt2) BrightPurple() gothememe.Color { return gothememe.Hex("#ff55ff") }
func (t *themeCobalt2) BrightCyan() gothememe.Color   { return gothememe.Hex("#6ae3fa") }
func (t *themeCobalt2) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeCobalt2) CodeBackground() gothememe.Color  { return gothememe.Hex("#132738") }
func (t *themeCobalt2) CodeText() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeCobalt2) CodeComment() gothememe.Color     { return gothememe.Hex("#555555") }
func (t *themeCobalt2) CodeKeyword() gothememe.Color     { return gothememe.Hex("#ff005d") }
func (t *themeCobalt2) CodeString() gothememe.Color      { return gothememe.Hex("#38de21") }
func (t *themeCobalt2) CodeNumber() gothememe.Color      { return gothememe.Hex("#ffe50a") }
func (t *themeCobalt2) CodeFunction() gothememe.Color    { return gothememe.Hex("#1460d2") }
func (t *themeCobalt2) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff0000") }
func (t *themeCobalt2) CodePunctuation() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeCobalt2) CodeVariable() gothememe.Color    { return gothememe.Hex("#00bbbb") }
func (t *themeCobalt2) CodeConstant() gothememe.Color    { return gothememe.Hex("#edc809") }
func (t *themeCobalt2) CodeType() gothememe.Color        { return gothememe.Hex("#6ae3fa") }
