// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeDawnfoxInstance is the Dawnfox color theme singleton.
var themeDawnfoxInstance gothememe.Theme = &themeDawnfox{}

// themeDawnfox implements the Dawnfox theme.
type themeDawnfox struct{}

func (t *themeDawnfox) ID() string          { return "dawnfox" }
func (t *themeDawnfox) DisplayName() string { return "Dawnfox" }
func (t *themeDawnfox) Description() string { return "Dawnfox color theme" }
func (t *themeDawnfox) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeDawnfox) License() string     { return "MIT" }
func (t *themeDawnfox) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeDawnfox) IsDark() bool        { return false }

// Background colors
func (t *themeDawnfox) Background() gothememe.Color          { return gothememe.Hex("#faf4ed") }
func (t *themeDawnfox) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#575279") }
func (t *themeDawnfox) Surface() gothememe.Color             { return gothememe.Hex("#d0d8d8") }
func (t *themeDawnfox) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#5f5695") }

// Text colors
func (t *themeDawnfox) TextPrimary() gothememe.Color   { return gothememe.Hex("#575279") }
func (t *themeDawnfox) TextSecondary() gothememe.Color { return gothememe.Hex("#b2b6bd") }
func (t *themeDawnfox) TextMuted() gothememe.Color     { return gothememe.Hex("#5f5695") }
func (t *themeDawnfox) TextInverted() gothememe.Color  { return gothememe.Hex("#faf4ed") }

// Accent/Brand colors
func (t *themeDawnfox) Accent() gothememe.Color          { return gothememe.Hex("#286983") }
func (t *themeDawnfox) AccentSecondary() gothememe.Color { return gothememe.Hex("#907aa9") }
func (t *themeDawnfox) Brand() gothememe.Color           { return gothememe.Hex("#286983") }

// Border colors
func (t *themeDawnfox) Border() gothememe.Color       { return gothememe.Hex("#5f5695") }
func (t *themeDawnfox) BorderSubtle() gothememe.Color { return gothememe.Hex("#575279") }
func (t *themeDawnfox) BorderStrong() gothememe.Color { return gothememe.Hex("#b2b6bd") }

// Semantic colors
func (t *themeDawnfox) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#618774").WithAlpha(0.1),
		Border:     gothememe.Hex("#618774").WithAlpha(0.3),
		Text:       gothememe.Hex("#618774"),
	}
}

func (t *themeDawnfox) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ea9d34").WithAlpha(0.1),
		Border:     gothememe.Hex("#ea9d34").WithAlpha(0.3),
		Text:       gothememe.Hex("#ea9d34"),
	}
}

func (t *themeDawnfox) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b4637a").WithAlpha(0.1),
		Border:     gothememe.Hex("#b4637a").WithAlpha(0.3),
		Text:       gothememe.Hex("#b4637a"),
	}
}

func (t *themeDawnfox) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#56949f").WithAlpha(0.1),
		Border:     gothememe.Hex("#56949f").WithAlpha(0.3),
		Text:       gothememe.Hex("#56949f"),
	}
}

// ANSI colors
func (t *themeDawnfox) Black() gothememe.Color        { return gothememe.Hex("#575279") }
func (t *themeDawnfox) Red() gothememe.Color          { return gothememe.Hex("#b4637a") }
func (t *themeDawnfox) Green() gothememe.Color        { return gothememe.Hex("#618774") }
func (t *themeDawnfox) Yellow() gothememe.Color       { return gothememe.Hex("#ea9d34") }
func (t *themeDawnfox) Blue() gothememe.Color         { return gothememe.Hex("#286983") }
func (t *themeDawnfox) Purple() gothememe.Color       { return gothememe.Hex("#907aa9") }
func (t *themeDawnfox) Cyan() gothememe.Color         { return gothememe.Hex("#56949f") }
func (t *themeDawnfox) White() gothememe.Color        { return gothememe.Hex("#b2b6bd") }
func (t *themeDawnfox) BrightBlack() gothememe.Color  { return gothememe.Hex("#5f5695") }
func (t *themeDawnfox) BrightRed() gothememe.Color    { return gothememe.Hex("#c26d85") }
func (t *themeDawnfox) BrightGreen() gothememe.Color  { return gothememe.Hex("#629f81") }
func (t *themeDawnfox) BrightYellow() gothememe.Color { return gothememe.Hex("#eea846") }
func (t *themeDawnfox) BrightBlue() gothememe.Color   { return gothememe.Hex("#2d81a3") }
func (t *themeDawnfox) BrightPurple() gothememe.Color { return gothememe.Hex("#9a80b9") }
func (t *themeDawnfox) BrightCyan() gothememe.Color   { return gothememe.Hex("#5ca7b4") }
func (t *themeDawnfox) BrightWhite() gothememe.Color  { return gothememe.Hex("#e6ebf3") }

// Code/Syntax highlighting colors
func (t *themeDawnfox) CodeBackground() gothememe.Color  { return gothememe.Hex("#faf4ed") }
func (t *themeDawnfox) CodeText() gothememe.Color        { return gothememe.Hex("#575279") }
func (t *themeDawnfox) CodeComment() gothememe.Color     { return gothememe.Hex("#5f5695") }
func (t *themeDawnfox) CodeKeyword() gothememe.Color     { return gothememe.Hex("#907aa9") }
func (t *themeDawnfox) CodeString() gothememe.Color      { return gothememe.Hex("#618774") }
func (t *themeDawnfox) CodeNumber() gothememe.Color      { return gothememe.Hex("#ea9d34") }
func (t *themeDawnfox) CodeFunction() gothememe.Color    { return gothememe.Hex("#286983") }
func (t *themeDawnfox) CodeOperator() gothememe.Color    { return gothememe.Hex("#b4637a") }
func (t *themeDawnfox) CodePunctuation() gothememe.Color { return gothememe.Hex("#575279") }
func (t *themeDawnfox) CodeVariable() gothememe.Color    { return gothememe.Hex("#56949f") }
func (t *themeDawnfox) CodeConstant() gothememe.Color    { return gothememe.Hex("#eea846") }
func (t *themeDawnfox) CodeType() gothememe.Color        { return gothememe.Hex("#5ca7b4") }
