// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeElementaryInstance is the Elementary color theme singleton.
var themeElementaryInstance gothememe.Theme = &themeElementary{}

// themeElementary implements the Elementary theme.
type themeElementary struct{}

func (t *themeElementary) ID() string          { return "elementary" }
func (t *themeElementary) DisplayName() string { return "Elementary" }
func (t *themeElementary) Description() string { return "Elementary color theme" }
func (t *themeElementary) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeElementary) License() string     { return "MIT" }
func (t *themeElementary) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeElementary) IsDark() bool        { return true }

// Background colors
func (t *themeElementary) Background() gothememe.Color          { return gothememe.Hex("#181818") }
func (t *themeElementary) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#242424") }
func (t *themeElementary) Surface() gothememe.Color             { return gothememe.Hex("#b5d5ff") }
func (t *themeElementary) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4b4b4b") }

// Text colors
func (t *themeElementary) TextPrimary() gothememe.Color   { return gothememe.Hex("#efefef") }
func (t *themeElementary) TextSecondary() gothememe.Color { return gothememe.Hex("#efefef") }
func (t *themeElementary) TextMuted() gothememe.Color     { return gothememe.Hex("#4b4b4b") }
func (t *themeElementary) TextInverted() gothememe.Color  { return gothememe.Hex("#181818") }

// Accent/Brand colors
func (t *themeElementary) Accent() gothememe.Color          { return gothememe.Hex("#134899") }
func (t *themeElementary) AccentSecondary() gothememe.Color { return gothememe.Hex("#e40038") }
func (t *themeElementary) Brand() gothememe.Color           { return gothememe.Hex("#134899") }

// Border colors
func (t *themeElementary) Border() gothememe.Color       { return gothememe.Hex("#4b4b4b") }
func (t *themeElementary) BorderSubtle() gothememe.Color { return gothememe.Hex("#242424") }
func (t *themeElementary) BorderStrong() gothememe.Color { return gothememe.Hex("#efefef") }

// Semantic colors
func (t *themeElementary) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5aa513").WithAlpha(0.1),
		Border:     gothememe.Hex("#5aa513").WithAlpha(0.3),
		Text:       gothememe.Hex("#5aa513"),
	}
}

func (t *themeElementary) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fdb40c").WithAlpha(0.1),
		Border:     gothememe.Hex("#fdb40c").WithAlpha(0.3),
		Text:       gothememe.Hex("#fdb40c"),
	}
}

func (t *themeElementary) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d71c15").WithAlpha(0.1),
		Border:     gothememe.Hex("#d71c15").WithAlpha(0.3),
		Text:       gothememe.Hex("#d71c15"),
	}
}

func (t *themeElementary) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#2595e1").WithAlpha(0.1),
		Border:     gothememe.Hex("#2595e1").WithAlpha(0.3),
		Text:       gothememe.Hex("#2595e1"),
	}
}

// ANSI colors
func (t *themeElementary) Black() gothememe.Color        { return gothememe.Hex("#242424") }
func (t *themeElementary) Red() gothememe.Color          { return gothememe.Hex("#d71c15") }
func (t *themeElementary) Green() gothememe.Color        { return gothememe.Hex("#5aa513") }
func (t *themeElementary) Yellow() gothememe.Color       { return gothememe.Hex("#fdb40c") }
func (t *themeElementary) Blue() gothememe.Color         { return gothememe.Hex("#134899") }
func (t *themeElementary) Purple() gothememe.Color       { return gothememe.Hex("#e40038") }
func (t *themeElementary) Cyan() gothememe.Color         { return gothememe.Hex("#2595e1") }
func (t *themeElementary) White() gothememe.Color        { return gothememe.Hex("#efefef") }
func (t *themeElementary) BrightBlack() gothememe.Color  { return gothememe.Hex("#4b4b4b") }
func (t *themeElementary) BrightRed() gothememe.Color    { return gothememe.Hex("#fc1c18") }
func (t *themeElementary) BrightGreen() gothememe.Color  { return gothememe.Hex("#6bc219") }
func (t *themeElementary) BrightYellow() gothememe.Color { return gothememe.Hex("#fec80e") }
func (t *themeElementary) BrightBlue() gothememe.Color   { return gothememe.Hex("#0955ff") }
func (t *themeElementary) BrightPurple() gothememe.Color { return gothememe.Hex("#fb0050") }
func (t *themeElementary) BrightCyan() gothememe.Color   { return gothememe.Hex("#3ea8fc") }
func (t *themeElementary) BrightWhite() gothememe.Color  { return gothememe.Hex("#8c00ec") }

// Code/Syntax highlighting colors
func (t *themeElementary) CodeBackground() gothememe.Color  { return gothememe.Hex("#181818") }
func (t *themeElementary) CodeText() gothememe.Color        { return gothememe.Hex("#efefef") }
func (t *themeElementary) CodeComment() gothememe.Color     { return gothememe.Hex("#4b4b4b") }
func (t *themeElementary) CodeKeyword() gothememe.Color     { return gothememe.Hex("#e40038") }
func (t *themeElementary) CodeString() gothememe.Color      { return gothememe.Hex("#5aa513") }
func (t *themeElementary) CodeNumber() gothememe.Color      { return gothememe.Hex("#fdb40c") }
func (t *themeElementary) CodeFunction() gothememe.Color    { return gothememe.Hex("#134899") }
func (t *themeElementary) CodeOperator() gothememe.Color    { return gothememe.Hex("#d71c15") }
func (t *themeElementary) CodePunctuation() gothememe.Color { return gothememe.Hex("#efefef") }
func (t *themeElementary) CodeVariable() gothememe.Color    { return gothememe.Hex("#2595e1") }
func (t *themeElementary) CodeConstant() gothememe.Color    { return gothememe.Hex("#fec80e") }
func (t *themeElementary) CodeType() gothememe.Color        { return gothememe.Hex("#3ea8fc") }
