// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeFlexokiDarkInstance is the Flexoki Dark color theme singleton.
var themeFlexokiDarkInstance gothememe.Theme = &themeFlexokiDark{}

// themeFlexokiDark implements the Flexoki Dark theme.
type themeFlexokiDark struct{}

func (t *themeFlexokiDark) ID() string          { return "flexoki_dark" }
func (t *themeFlexokiDark) DisplayName() string { return "Flexoki Dark" }
func (t *themeFlexokiDark) Description() string { return "Flexoki Dark color theme" }
func (t *themeFlexokiDark) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeFlexokiDark) License() string     { return "MIT" }
func (t *themeFlexokiDark) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeFlexokiDark) IsDark() bool { return true }

// Background colors
func (t *themeFlexokiDark) Background() gothememe.Color          { return gothememe.Hex("#100f0f") }
func (t *themeFlexokiDark) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#100f0f") }
func (t *themeFlexokiDark) Surface() gothememe.Color             { return gothememe.Hex("#403e3c") }
func (t *themeFlexokiDark) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#575653") }

// Text colors
func (t *themeFlexokiDark) TextPrimary() gothememe.Color   { return gothememe.Hex("#cecdc3") }
func (t *themeFlexokiDark) TextSecondary() gothememe.Color { return gothememe.Hex("#878580") }
func (t *themeFlexokiDark) TextMuted() gothememe.Color     { return gothememe.Hex("#575653") }
func (t *themeFlexokiDark) TextInverted() gothememe.Color  { return gothememe.Hex("#100f0f") }

// Accent/Brand colors
func (t *themeFlexokiDark) Accent() gothememe.Color          { return gothememe.Hex("#4385be") }
func (t *themeFlexokiDark) AccentSecondary() gothememe.Color { return gothememe.Hex("#ce5d97") }
func (t *themeFlexokiDark) Brand() gothememe.Color           { return gothememe.Hex("#4385be") }

// Border colors
func (t *themeFlexokiDark) Border() gothememe.Color       { return gothememe.Hex("#575653") }
func (t *themeFlexokiDark) BorderSubtle() gothememe.Color { return gothememe.Hex("#100f0f") }
func (t *themeFlexokiDark) BorderStrong() gothememe.Color { return gothememe.Hex("#878580") }

// Semantic colors
func (t *themeFlexokiDark) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#879a39").WithAlpha(0.1),
		Border:     gothememe.Hex("#879a39").WithAlpha(0.3),
		Text:       gothememe.Hex("#879a39"),
	}
}

func (t *themeFlexokiDark) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d0a215").WithAlpha(0.1),
		Border:     gothememe.Hex("#d0a215").WithAlpha(0.3),
		Text:       gothememe.Hex("#d0a215"),
	}
}

func (t *themeFlexokiDark) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d14d41").WithAlpha(0.1),
		Border:     gothememe.Hex("#d14d41").WithAlpha(0.3),
		Text:       gothememe.Hex("#d14d41"),
	}
}

func (t *themeFlexokiDark) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#3aa99f").WithAlpha(0.1),
		Border:     gothememe.Hex("#3aa99f").WithAlpha(0.3),
		Text:       gothememe.Hex("#3aa99f"),
	}
}

// ANSI colors
func (t *themeFlexokiDark) Black() gothememe.Color        { return gothememe.Hex("#100f0f") }
func (t *themeFlexokiDark) Red() gothememe.Color          { return gothememe.Hex("#d14d41") }
func (t *themeFlexokiDark) Green() gothememe.Color        { return gothememe.Hex("#879a39") }
func (t *themeFlexokiDark) Yellow() gothememe.Color       { return gothememe.Hex("#d0a215") }
func (t *themeFlexokiDark) Blue() gothememe.Color         { return gothememe.Hex("#4385be") }
func (t *themeFlexokiDark) Purple() gothememe.Color       { return gothememe.Hex("#ce5d97") }
func (t *themeFlexokiDark) Cyan() gothememe.Color         { return gothememe.Hex("#3aa99f") }
func (t *themeFlexokiDark) White() gothememe.Color        { return gothememe.Hex("#878580") }
func (t *themeFlexokiDark) BrightBlack() gothememe.Color  { return gothememe.Hex("#575653") }
func (t *themeFlexokiDark) BrightRed() gothememe.Color    { return gothememe.Hex("#af3029") }
func (t *themeFlexokiDark) BrightGreen() gothememe.Color  { return gothememe.Hex("#66800b") }
func (t *themeFlexokiDark) BrightYellow() gothememe.Color { return gothememe.Hex("#ad8301") }
func (t *themeFlexokiDark) BrightBlue() gothememe.Color   { return gothememe.Hex("#205ea6") }
func (t *themeFlexokiDark) BrightPurple() gothememe.Color { return gothememe.Hex("#a02f6f") }
func (t *themeFlexokiDark) BrightCyan() gothememe.Color   { return gothememe.Hex("#24837b") }
func (t *themeFlexokiDark) BrightWhite() gothememe.Color  { return gothememe.Hex("#cecdc3") }

// Code/Syntax highlighting colors
func (t *themeFlexokiDark) CodeBackground() gothememe.Color  { return gothememe.Hex("#100f0f") }
func (t *themeFlexokiDark) CodeText() gothememe.Color        { return gothememe.Hex("#cecdc3") }
func (t *themeFlexokiDark) CodeComment() gothememe.Color     { return gothememe.Hex("#575653") }
func (t *themeFlexokiDark) CodeKeyword() gothememe.Color     { return gothememe.Hex("#ce5d97") }
func (t *themeFlexokiDark) CodeString() gothememe.Color      { return gothememe.Hex("#879a39") }
func (t *themeFlexokiDark) CodeNumber() gothememe.Color      { return gothememe.Hex("#d0a215") }
func (t *themeFlexokiDark) CodeFunction() gothememe.Color    { return gothememe.Hex("#4385be") }
func (t *themeFlexokiDark) CodeOperator() gothememe.Color    { return gothememe.Hex("#d14d41") }
func (t *themeFlexokiDark) CodePunctuation() gothememe.Color { return gothememe.Hex("#cecdc3") }
func (t *themeFlexokiDark) CodeVariable() gothememe.Color    { return gothememe.Hex("#3aa99f") }
func (t *themeFlexokiDark) CodeConstant() gothememe.Color    { return gothememe.Hex("#ad8301") }
func (t *themeFlexokiDark) CodeType() gothememe.Color        { return gothememe.Hex("#24837b") }
