// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeGlacierInstance is the Glacier color theme singleton.
var themeGlacierInstance gothememe.Theme = &themeGlacier{}

// themeGlacier implements the Glacier theme.
type themeGlacier struct{}

func (t *themeGlacier) ID() string          { return "glacier" }
func (t *themeGlacier) DisplayName() string { return "Glacier" }
func (t *themeGlacier) Description() string { return "Glacier color theme" }
func (t *themeGlacier) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeGlacier) License() string     { return "MIT" }
func (t *themeGlacier) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeGlacier) IsDark() bool        { return true }

// Background colors
func (t *themeGlacier) Background() gothememe.Color          { return gothememe.Hex("#0c1115") }
func (t *themeGlacier) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#2e343c") }
func (t *themeGlacier) Surface() gothememe.Color             { return gothememe.Hex("#bd2523") }
func (t *themeGlacier) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#404a55") }

// Text colors
func (t *themeGlacier) TextPrimary() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeGlacier) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeGlacier) TextMuted() gothememe.Color     { return gothememe.Hex("#404a55") }
func (t *themeGlacier) TextInverted() gothememe.Color  { return gothememe.Hex("#0c1115") }

// Accent/Brand colors
func (t *themeGlacier) Accent() gothememe.Color          { return gothememe.Hex("#1f5872") }
func (t *themeGlacier) AccentSecondary() gothememe.Color { return gothememe.Hex("#bd2523") }
func (t *themeGlacier) Brand() gothememe.Color           { return gothememe.Hex("#1f5872") }

// Border colors
func (t *themeGlacier) Border() gothememe.Color       { return gothememe.Hex("#404a55") }
func (t *themeGlacier) BorderSubtle() gothememe.Color { return gothememe.Hex("#2e343c") }
func (t *themeGlacier) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeGlacier) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#35a770").WithAlpha(0.1),
		Border:     gothememe.Hex("#35a770").WithAlpha(0.3),
		Text:       gothememe.Hex("#35a770"),
	}
}

func (t *themeGlacier) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fb9435").WithAlpha(0.1),
		Border:     gothememe.Hex("#fb9435").WithAlpha(0.3),
		Text:       gothememe.Hex("#fb9435"),
	}
}

func (t *themeGlacier) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#bd0f2f").WithAlpha(0.1),
		Border:     gothememe.Hex("#bd0f2f").WithAlpha(0.3),
		Text:       gothememe.Hex("#bd0f2f"),
	}
}

func (t *themeGlacier) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#778397").WithAlpha(0.1),
		Border:     gothememe.Hex("#778397").WithAlpha(0.3),
		Text:       gothememe.Hex("#778397"),
	}
}

// ANSI colors
func (t *themeGlacier) Black() gothememe.Color        { return gothememe.Hex("#2e343c") }
func (t *themeGlacier) Red() gothememe.Color          { return gothememe.Hex("#bd0f2f") }
func (t *themeGlacier) Green() gothememe.Color        { return gothememe.Hex("#35a770") }
func (t *themeGlacier) Yellow() gothememe.Color       { return gothememe.Hex("#fb9435") }
func (t *themeGlacier) Blue() gothememe.Color         { return gothememe.Hex("#1f5872") }
func (t *themeGlacier) Purple() gothememe.Color       { return gothememe.Hex("#bd2523") }
func (t *themeGlacier) Cyan() gothememe.Color         { return gothememe.Hex("#778397") }
func (t *themeGlacier) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeGlacier) BrightBlack() gothememe.Color  { return gothememe.Hex("#404a55") }
func (t *themeGlacier) BrightRed() gothememe.Color    { return gothememe.Hex("#bd0f2f") }
func (t *themeGlacier) BrightGreen() gothememe.Color  { return gothememe.Hex("#49e998") }
func (t *themeGlacier) BrightYellow() gothememe.Color { return gothememe.Hex("#fddf6e") }
func (t *themeGlacier) BrightBlue() gothememe.Color   { return gothememe.Hex("#2a8bc1") }
func (t *themeGlacier) BrightPurple() gothememe.Color { return gothememe.Hex("#ea4727") }
func (t *themeGlacier) BrightCyan() gothememe.Color   { return gothememe.Hex("#a0b6d3") }
func (t *themeGlacier) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeGlacier) CodeBackground() gothememe.Color  { return gothememe.Hex("#0c1115") }
func (t *themeGlacier) CodeText() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeGlacier) CodeComment() gothememe.Color     { return gothememe.Hex("#404a55") }
func (t *themeGlacier) CodeKeyword() gothememe.Color     { return gothememe.Hex("#bd2523") }
func (t *themeGlacier) CodeString() gothememe.Color      { return gothememe.Hex("#35a770") }
func (t *themeGlacier) CodeNumber() gothememe.Color      { return gothememe.Hex("#fb9435") }
func (t *themeGlacier) CodeFunction() gothememe.Color    { return gothememe.Hex("#1f5872") }
func (t *themeGlacier) CodeOperator() gothememe.Color    { return gothememe.Hex("#bd0f2f") }
func (t *themeGlacier) CodePunctuation() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeGlacier) CodeVariable() gothememe.Color    { return gothememe.Hex("#778397") }
func (t *themeGlacier) CodeConstant() gothememe.Color    { return gothememe.Hex("#fddf6e") }
func (t *themeGlacier) CodeType() gothememe.Color        { return gothememe.Hex("#a0b6d3") }
