// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeGrapeInstance is the Grape color theme singleton.
var themeGrapeInstance gothememe.Theme = &themeGrape{}

// themeGrape implements the Grape theme.
type themeGrape struct{}

func (t *themeGrape) ID() string          { return "grape" }
func (t *themeGrape) DisplayName() string { return "Grape" }
func (t *themeGrape) Description() string { return "Grape color theme" }
func (t *themeGrape) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeGrape) License() string     { return "MIT" }
func (t *themeGrape) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeGrape) IsDark() bool        { return true }

// Background colors
func (t *themeGrape) Background() gothememe.Color          { return gothememe.Hex("#171423") }
func (t *themeGrape) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#2d283f") }
func (t *themeGrape) Surface() gothememe.Color             { return gothememe.Hex("#493d70") }
func (t *themeGrape) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#59516a") }

// Text colors
func (t *themeGrape) TextPrimary() gothememe.Color   { return gothememe.Hex("#9f9fa1") }
func (t *themeGrape) TextSecondary() gothememe.Color { return gothememe.Hex("#9e9ea0") }
func (t *themeGrape) TextMuted() gothememe.Color     { return gothememe.Hex("#59516a") }
func (t *themeGrape) TextInverted() gothememe.Color  { return gothememe.Hex("#171423") }

// Accent/Brand colors
func (t *themeGrape) Accent() gothememe.Color          { return gothememe.Hex("#487df4") }
func (t *themeGrape) AccentSecondary() gothememe.Color { return gothememe.Hex("#8d35c9") }
func (t *themeGrape) Brand() gothememe.Color           { return gothememe.Hex("#487df4") }

// Border colors
func (t *themeGrape) Border() gothememe.Color       { return gothememe.Hex("#59516a") }
func (t *themeGrape) BorderSubtle() gothememe.Color { return gothememe.Hex("#2d283f") }
func (t *themeGrape) BorderStrong() gothememe.Color { return gothememe.Hex("#9e9ea0") }

// Semantic colors
func (t *themeGrape) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1fa91b").WithAlpha(0.1),
		Border:     gothememe.Hex("#1fa91b").WithAlpha(0.3),
		Text:       gothememe.Hex("#1fa91b"),
	}
}

func (t *themeGrape) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#8ddc20").WithAlpha(0.1),
		Border:     gothememe.Hex("#8ddc20").WithAlpha(0.3),
		Text:       gothememe.Hex("#8ddc20"),
	}
}

func (t *themeGrape) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ed2261").WithAlpha(0.1),
		Border:     gothememe.Hex("#ed2261").WithAlpha(0.3),
		Text:       gothememe.Hex("#ed2261"),
	}
}

func (t *themeGrape) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#3bdeed").WithAlpha(0.1),
		Border:     gothememe.Hex("#3bdeed").WithAlpha(0.3),
		Text:       gothememe.Hex("#3bdeed"),
	}
}

// ANSI colors
func (t *themeGrape) Black() gothememe.Color        { return gothememe.Hex("#2d283f") }
func (t *themeGrape) Red() gothememe.Color          { return gothememe.Hex("#ed2261") }
func (t *themeGrape) Green() gothememe.Color        { return gothememe.Hex("#1fa91b") }
func (t *themeGrape) Yellow() gothememe.Color       { return gothememe.Hex("#8ddc20") }
func (t *themeGrape) Blue() gothememe.Color         { return gothememe.Hex("#487df4") }
func (t *themeGrape) Purple() gothememe.Color       { return gothememe.Hex("#8d35c9") }
func (t *themeGrape) Cyan() gothememe.Color         { return gothememe.Hex("#3bdeed") }
func (t *themeGrape) White() gothememe.Color        { return gothememe.Hex("#9e9ea0") }
func (t *themeGrape) BrightBlack() gothememe.Color  { return gothememe.Hex("#59516a") }
func (t *themeGrape) BrightRed() gothememe.Color    { return gothememe.Hex("#f0729a") }
func (t *themeGrape) BrightGreen() gothememe.Color  { return gothememe.Hex("#53aa5e") }
func (t *themeGrape) BrightYellow() gothememe.Color { return gothememe.Hex("#b2dc87") }
func (t *themeGrape) BrightBlue() gothememe.Color   { return gothememe.Hex("#a9bcec") }
func (t *themeGrape) BrightPurple() gothememe.Color { return gothememe.Hex("#ad81c2") }
func (t *themeGrape) BrightCyan() gothememe.Color   { return gothememe.Hex("#9de3eb") }
func (t *themeGrape) BrightWhite() gothememe.Color  { return gothememe.Hex("#a288f7") }

// Code/Syntax highlighting colors
func (t *themeGrape) CodeBackground() gothememe.Color  { return gothememe.Hex("#171423") }
func (t *themeGrape) CodeText() gothememe.Color        { return gothememe.Hex("#9f9fa1") }
func (t *themeGrape) CodeComment() gothememe.Color     { return gothememe.Hex("#59516a") }
func (t *themeGrape) CodeKeyword() gothememe.Color     { return gothememe.Hex("#8d35c9") }
func (t *themeGrape) CodeString() gothememe.Color      { return gothememe.Hex("#1fa91b") }
func (t *themeGrape) CodeNumber() gothememe.Color      { return gothememe.Hex("#8ddc20") }
func (t *themeGrape) CodeFunction() gothememe.Color    { return gothememe.Hex("#487df4") }
func (t *themeGrape) CodeOperator() gothememe.Color    { return gothememe.Hex("#ed2261") }
func (t *themeGrape) CodePunctuation() gothememe.Color { return gothememe.Hex("#9f9fa1") }
func (t *themeGrape) CodeVariable() gothememe.Color    { return gothememe.Hex("#3bdeed") }
func (t *themeGrape) CodeConstant() gothememe.Color    { return gothememe.Hex("#b2dc87") }
func (t *themeGrape) CodeType() gothememe.Color        { return gothememe.Hex("#9de3eb") }
