// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeGreyGreenInstance is the Grey Green color theme singleton.
var themeGreyGreenInstance gothememe.Theme = &themeGreyGreen{}

// themeGreyGreen implements the Grey Green theme.
type themeGreyGreen struct{}

func (t *themeGreyGreen) ID() string          { return "grey_green" }
func (t *themeGreyGreen) DisplayName() string { return "Grey Green" }
func (t *themeGreyGreen) Description() string { return "Grey Green color theme" }
func (t *themeGreyGreen) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeGreyGreen) License() string     { return "MIT" }
func (t *themeGreyGreen) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeGreyGreen) IsDark() bool        { return true }

// Background colors
func (t *themeGreyGreen) Background() gothememe.Color          { return gothememe.Hex("#002a1a") }
func (t *themeGreyGreen) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeGreyGreen) Surface() gothememe.Color             { return gothememe.Hex("#517e50") }
func (t *themeGreyGreen) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#666666") }

// Text colors
func (t *themeGreyGreen) TextPrimary() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeGreyGreen) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeGreyGreen) TextMuted() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeGreyGreen) TextInverted() gothememe.Color  { return gothememe.Hex("#002a1a") }

// Accent/Brand colors
func (t *themeGreyGreen) Accent() gothememe.Color          { return gothememe.Hex("#00deff") }
func (t *themeGreyGreen) AccentSecondary() gothememe.Color { return gothememe.Hex("#ff00f0") }
func (t *themeGreyGreen) Brand() gothememe.Color           { return gothememe.Hex("#00deff") }

// Border colors
func (t *themeGreyGreen) Border() gothememe.Color       { return gothememe.Hex("#666666") }
func (t *themeGreyGreen) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeGreyGreen) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeGreyGreen) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#74ff00").WithAlpha(0.1),
		Border:     gothememe.Hex("#74ff00").WithAlpha(0.3),
		Text:       gothememe.Hex("#74ff00"),
	}
}

func (t *themeGreyGreen) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f1ff01").WithAlpha(0.1),
		Border:     gothememe.Hex("#f1ff01").WithAlpha(0.3),
		Text:       gothememe.Hex("#f1ff01"),
	}
}

func (t *themeGreyGreen) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fe1414").WithAlpha(0.1),
		Border:     gothememe.Hex("#fe1414").WithAlpha(0.3),
		Text:       gothememe.Hex("#fe1414"),
	}
}

func (t *themeGreyGreen) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00ffbc").WithAlpha(0.1),
		Border:     gothememe.Hex("#00ffbc").WithAlpha(0.3),
		Text:       gothememe.Hex("#00ffbc"),
	}
}

// ANSI colors
func (t *themeGreyGreen) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeGreyGreen) Red() gothememe.Color          { return gothememe.Hex("#fe1414") }
func (t *themeGreyGreen) Green() gothememe.Color        { return gothememe.Hex("#74ff00") }
func (t *themeGreyGreen) Yellow() gothememe.Color       { return gothememe.Hex("#f1ff01") }
func (t *themeGreyGreen) Blue() gothememe.Color         { return gothememe.Hex("#00deff") }
func (t *themeGreyGreen) Purple() gothememe.Color       { return gothememe.Hex("#ff00f0") }
func (t *themeGreyGreen) Cyan() gothememe.Color         { return gothememe.Hex("#00ffbc") }
func (t *themeGreyGreen) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeGreyGreen) BrightBlack() gothememe.Color  { return gothememe.Hex("#666666") }
func (t *themeGreyGreen) BrightRed() gothememe.Color    { return gothememe.Hex("#ff3939") }
func (t *themeGreyGreen) BrightGreen() gothememe.Color  { return gothememe.Hex("#00ff44") }
func (t *themeGreyGreen) BrightYellow() gothememe.Color { return gothememe.Hex("#ffd100") }
func (t *themeGreyGreen) BrightBlue() gothememe.Color   { return gothememe.Hex("#00afff") }
func (t *themeGreyGreen) BrightPurple() gothememe.Color { return gothememe.Hex("#ff008a") }
func (t *themeGreyGreen) BrightCyan() gothememe.Color   { return gothememe.Hex("#00ffd3") }
func (t *themeGreyGreen) BrightWhite() gothememe.Color  { return gothememe.Hex("#f5ecec") }

// Code/Syntax highlighting colors
func (t *themeGreyGreen) CodeBackground() gothememe.Color  { return gothememe.Hex("#002a1a") }
func (t *themeGreyGreen) CodeText() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeGreyGreen) CodeComment() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeGreyGreen) CodeKeyword() gothememe.Color     { return gothememe.Hex("#ff00f0") }
func (t *themeGreyGreen) CodeString() gothememe.Color      { return gothememe.Hex("#74ff00") }
func (t *themeGreyGreen) CodeNumber() gothememe.Color      { return gothememe.Hex("#f1ff01") }
func (t *themeGreyGreen) CodeFunction() gothememe.Color    { return gothememe.Hex("#00deff") }
func (t *themeGreyGreen) CodeOperator() gothememe.Color    { return gothememe.Hex("#fe1414") }
func (t *themeGreyGreen) CodePunctuation() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeGreyGreen) CodeVariable() gothememe.Color    { return gothememe.Hex("#00ffbc") }
func (t *themeGreyGreen) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffd100") }
func (t *themeGreyGreen) CodeType() gothememe.Color        { return gothememe.Hex("#00ffd3") }
