// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeGruvboxLightHardInstance is the Gruvbox Light Hard color theme singleton.
var themeGruvboxLightHardInstance gothememe.Theme = &themeGruvboxLightHard{}

// themeGruvboxLightHard implements the Gruvbox Light Hard theme.
type themeGruvboxLightHard struct{}

func (t *themeGruvboxLightHard) ID() string          { return "gruvbox_light_hard" }
func (t *themeGruvboxLightHard) DisplayName() string { return "Gruvbox Light Hard" }
func (t *themeGruvboxLightHard) Description() string { return "Gruvbox Light Hard color theme" }
func (t *themeGruvboxLightHard) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeGruvboxLightHard) License() string     { return "MIT" }
func (t *themeGruvboxLightHard) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeGruvboxLightHard) IsDark() bool { return false }

// Background colors
func (t *themeGruvboxLightHard) Background() gothememe.Color { return gothememe.Hex("#f9f5d7") }
func (t *themeGruvboxLightHard) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#f9f5d7")
}
func (t *themeGruvboxLightHard) Surface() gothememe.Color          { return gothememe.Hex("#3c3836") }
func (t *themeGruvboxLightHard) SurfaceSecondary() gothememe.Color { return gothememe.Hex("#928374") }

// Text colors
func (t *themeGruvboxLightHard) TextPrimary() gothememe.Color   { return gothememe.Hex("#3c3836") }
func (t *themeGruvboxLightHard) TextSecondary() gothememe.Color { return gothememe.Hex("#7c6f64") }
func (t *themeGruvboxLightHard) TextMuted() gothememe.Color     { return gothememe.Hex("#928374") }
func (t *themeGruvboxLightHard) TextInverted() gothememe.Color  { return gothememe.Hex("#f9f5d7") }

// Accent/Brand colors
func (t *themeGruvboxLightHard) Accent() gothememe.Color          { return gothememe.Hex("#458588") }
func (t *themeGruvboxLightHard) AccentSecondary() gothememe.Color { return gothememe.Hex("#b16286") }
func (t *themeGruvboxLightHard) Brand() gothememe.Color           { return gothememe.Hex("#458588") }

// Border colors
func (t *themeGruvboxLightHard) Border() gothememe.Color       { return gothememe.Hex("#928374") }
func (t *themeGruvboxLightHard) BorderSubtle() gothememe.Color { return gothememe.Hex("#f9f5d7") }
func (t *themeGruvboxLightHard) BorderStrong() gothememe.Color { return gothememe.Hex("#7c6f64") }

// Semantic colors
func (t *themeGruvboxLightHard) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#98971a").WithAlpha(0.1),
		Border:     gothememe.Hex("#98971a").WithAlpha(0.3),
		Text:       gothememe.Hex("#98971a"),
	}
}

func (t *themeGruvboxLightHard) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d79921").WithAlpha(0.1),
		Border:     gothememe.Hex("#d79921").WithAlpha(0.3),
		Text:       gothememe.Hex("#d79921"),
	}
}

func (t *themeGruvboxLightHard) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cc241d").WithAlpha(0.1),
		Border:     gothememe.Hex("#cc241d").WithAlpha(0.3),
		Text:       gothememe.Hex("#cc241d"),
	}
}

func (t *themeGruvboxLightHard) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#689d6a").WithAlpha(0.1),
		Border:     gothememe.Hex("#689d6a").WithAlpha(0.3),
		Text:       gothememe.Hex("#689d6a"),
	}
}

// ANSI colors
func (t *themeGruvboxLightHard) Black() gothememe.Color        { return gothememe.Hex("#f9f5d7") }
func (t *themeGruvboxLightHard) Red() gothememe.Color          { return gothememe.Hex("#cc241d") }
func (t *themeGruvboxLightHard) Green() gothememe.Color        { return gothememe.Hex("#98971a") }
func (t *themeGruvboxLightHard) Yellow() gothememe.Color       { return gothememe.Hex("#d79921") }
func (t *themeGruvboxLightHard) Blue() gothememe.Color         { return gothememe.Hex("#458588") }
func (t *themeGruvboxLightHard) Purple() gothememe.Color       { return gothememe.Hex("#b16286") }
func (t *themeGruvboxLightHard) Cyan() gothememe.Color         { return gothememe.Hex("#689d6a") }
func (t *themeGruvboxLightHard) White() gothememe.Color        { return gothememe.Hex("#7c6f64") }
func (t *themeGruvboxLightHard) BrightBlack() gothememe.Color  { return gothememe.Hex("#928374") }
func (t *themeGruvboxLightHard) BrightRed() gothememe.Color    { return gothememe.Hex("#9d0006") }
func (t *themeGruvboxLightHard) BrightGreen() gothememe.Color  { return gothememe.Hex("#79740e") }
func (t *themeGruvboxLightHard) BrightYellow() gothememe.Color { return gothememe.Hex("#b57614") }
func (t *themeGruvboxLightHard) BrightBlue() gothememe.Color   { return gothememe.Hex("#076678") }
func (t *themeGruvboxLightHard) BrightPurple() gothememe.Color { return gothememe.Hex("#8f3f71") }
func (t *themeGruvboxLightHard) BrightCyan() gothememe.Color   { return gothememe.Hex("#427b58") }
func (t *themeGruvboxLightHard) BrightWhite() gothememe.Color  { return gothememe.Hex("#3c3836") }

// Code/Syntax highlighting colors
func (t *themeGruvboxLightHard) CodeBackground() gothememe.Color  { return gothememe.Hex("#f9f5d7") }
func (t *themeGruvboxLightHard) CodeText() gothememe.Color        { return gothememe.Hex("#3c3836") }
func (t *themeGruvboxLightHard) CodeComment() gothememe.Color     { return gothememe.Hex("#928374") }
func (t *themeGruvboxLightHard) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b16286") }
func (t *themeGruvboxLightHard) CodeString() gothememe.Color      { return gothememe.Hex("#98971a") }
func (t *themeGruvboxLightHard) CodeNumber() gothememe.Color      { return gothememe.Hex("#d79921") }
func (t *themeGruvboxLightHard) CodeFunction() gothememe.Color    { return gothememe.Hex("#458588") }
func (t *themeGruvboxLightHard) CodeOperator() gothememe.Color    { return gothememe.Hex("#cc241d") }
func (t *themeGruvboxLightHard) CodePunctuation() gothememe.Color { return gothememe.Hex("#3c3836") }
func (t *themeGruvboxLightHard) CodeVariable() gothememe.Color    { return gothememe.Hex("#689d6a") }
func (t *themeGruvboxLightHard) CodeConstant() gothememe.Color    { return gothememe.Hex("#b57614") }
func (t *themeGruvboxLightHard) CodeType() gothememe.Color        { return gothememe.Hex("#427b58") }
