// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeGuezwhozInstance is the Guezwhoz color theme singleton.
var themeGuezwhozInstance gothememe.Theme = &themeGuezwhoz{}

// themeGuezwhoz implements the Guezwhoz theme.
type themeGuezwhoz struct{}

func (t *themeGuezwhoz) ID() string          { return "guezwhoz" }
func (t *themeGuezwhoz) DisplayName() string { return "Guezwhoz" }
func (t *themeGuezwhoz) Description() string { return "Guezwhoz color theme" }
func (t *themeGuezwhoz) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeGuezwhoz) License() string     { return "MIT" }
func (t *themeGuezwhoz) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeGuezwhoz) IsDark() bool        { return true }

// Background colors
func (t *themeGuezwhoz) Background() gothememe.Color          { return gothememe.Hex("#1d1d1d") }
func (t *themeGuezwhoz) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#333333") }
func (t *themeGuezwhoz) Surface() gothememe.Color             { return gothememe.Hex("#245354") }
func (t *themeGuezwhoz) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#808080") }

// Text colors
func (t *themeGuezwhoz) TextPrimary() gothememe.Color   { return gothememe.Hex("#d9d9d9") }
func (t *themeGuezwhoz) TextSecondary() gothememe.Color { return gothememe.Hex("#d9d9d9") }
func (t *themeGuezwhoz) TextMuted() gothememe.Color     { return gothememe.Hex("#808080") }
func (t *themeGuezwhoz) TextInverted() gothememe.Color  { return gothememe.Hex("#1d1d1d") }

// Accent/Brand colors
func (t *themeGuezwhoz) Accent() gothememe.Color          { return gothememe.Hex("#5aa0d6") }
func (t *themeGuezwhoz) AccentSecondary() gothememe.Color { return gothememe.Hex("#9a90e0") }
func (t *themeGuezwhoz) Brand() gothememe.Color           { return gothememe.Hex("#5aa0d6") }

// Border colors
func (t *themeGuezwhoz) Border() gothememe.Color       { return gothememe.Hex("#808080") }
func (t *themeGuezwhoz) BorderSubtle() gothememe.Color { return gothememe.Hex("#333333") }
func (t *themeGuezwhoz) BorderStrong() gothememe.Color { return gothememe.Hex("#d9d9d9") }

// Semantic colors
func (t *themeGuezwhoz) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#7ad694").WithAlpha(0.1),
		Border:     gothememe.Hex("#7ad694").WithAlpha(0.3),
		Text:       gothememe.Hex("#7ad694"),
	}
}

func (t *themeGuezwhoz) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b7d074").WithAlpha(0.1),
		Border:     gothememe.Hex("#b7d074").WithAlpha(0.3),
		Text:       gothememe.Hex("#b7d074"),
	}
}

func (t *themeGuezwhoz) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e85181").WithAlpha(0.1),
		Border:     gothememe.Hex("#e85181").WithAlpha(0.3),
		Text:       gothememe.Hex("#e85181"),
	}
}

func (t *themeGuezwhoz) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#58d6ce").WithAlpha(0.1),
		Border:     gothememe.Hex("#58d6ce").WithAlpha(0.3),
		Text:       gothememe.Hex("#58d6ce"),
	}
}

// ANSI colors
func (t *themeGuezwhoz) Black() gothememe.Color        { return gothememe.Hex("#333333") }
func (t *themeGuezwhoz) Red() gothememe.Color          { return gothememe.Hex("#e85181") }
func (t *themeGuezwhoz) Green() gothememe.Color        { return gothememe.Hex("#7ad694") }
func (t *themeGuezwhoz) Yellow() gothememe.Color       { return gothememe.Hex("#b7d074") }
func (t *themeGuezwhoz) Blue() gothememe.Color         { return gothememe.Hex("#5aa0d6") }
func (t *themeGuezwhoz) Purple() gothememe.Color       { return gothememe.Hex("#9a90e0") }
func (t *themeGuezwhoz) Cyan() gothememe.Color         { return gothememe.Hex("#58d6ce") }
func (t *themeGuezwhoz) White() gothememe.Color        { return gothememe.Hex("#d9d9d9") }
func (t *themeGuezwhoz) BrightBlack() gothememe.Color  { return gothememe.Hex("#808080") }
func (t *themeGuezwhoz) BrightRed() gothememe.Color    { return gothememe.Hex("#e85181") }
func (t *themeGuezwhoz) BrightGreen() gothememe.Color  { return gothememe.Hex("#afd7af") }
func (t *themeGuezwhoz) BrightYellow() gothememe.Color { return gothememe.Hex("#d1ed85") }
func (t *themeGuezwhoz) BrightBlue() gothememe.Color   { return gothememe.Hex("#64b2ed") }
func (t *themeGuezwhoz) BrightPurple() gothememe.Color { return gothememe.Hex("#a398ed") }
func (t *themeGuezwhoz) BrightCyan() gothememe.Color   { return gothememe.Hex("#61ede4") }
func (t *themeGuezwhoz) BrightWhite() gothememe.Color  { return gothememe.Hex("#ededed") }

// Code/Syntax highlighting colors
func (t *themeGuezwhoz) CodeBackground() gothememe.Color  { return gothememe.Hex("#1d1d1d") }
func (t *themeGuezwhoz) CodeText() gothememe.Color        { return gothememe.Hex("#d9d9d9") }
func (t *themeGuezwhoz) CodeComment() gothememe.Color     { return gothememe.Hex("#808080") }
func (t *themeGuezwhoz) CodeKeyword() gothememe.Color     { return gothememe.Hex("#9a90e0") }
func (t *themeGuezwhoz) CodeString() gothememe.Color      { return gothememe.Hex("#7ad694") }
func (t *themeGuezwhoz) CodeNumber() gothememe.Color      { return gothememe.Hex("#b7d074") }
func (t *themeGuezwhoz) CodeFunction() gothememe.Color    { return gothememe.Hex("#5aa0d6") }
func (t *themeGuezwhoz) CodeOperator() gothememe.Color    { return gothememe.Hex("#e85181") }
func (t *themeGuezwhoz) CodePunctuation() gothememe.Color { return gothememe.Hex("#d9d9d9") }
func (t *themeGuezwhoz) CodeVariable() gothememe.Color    { return gothememe.Hex("#58d6ce") }
func (t *themeGuezwhoz) CodeConstant() gothememe.Color    { return gothememe.Hex("#d1ed85") }
func (t *themeGuezwhoz) CodeType() gothememe.Color        { return gothememe.Hex("#61ede4") }
