// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeHax0rR3dInstance is the HaX0R R3D color theme singleton.
var themeHax0rR3dInstance gothememe.Theme = &themeHax0rR3d{}

// themeHax0rR3d implements the HaX0R R3D theme.
type themeHax0rR3d struct{}

func (t *themeHax0rR3d) ID() string          { return "hax0r_r3d" }
func (t *themeHax0rR3d) DisplayName() string { return "HaX0R R3D" }
func (t *themeHax0rR3d) Description() string { return "HaX0R R3D color theme" }
func (t *themeHax0rR3d) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeHax0rR3d) License() string     { return "MIT" }
func (t *themeHax0rR3d) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeHax0rR3d) IsDark() bool        { return true }

// Background colors
func (t *themeHax0rR3d) Background() gothememe.Color          { return gothememe.Hex("#200101") }
func (t *themeHax0rR3d) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#1f0000") }
func (t *themeHax0rR3d) Surface() gothememe.Color             { return gothememe.Hex("#ebc1ff") }
func (t *themeHax0rR3d) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#554040") }

// Text colors
func (t *themeHax0rR3d) TextPrimary() gothememe.Color   { return gothememe.Hex("#b10e0e") }
func (t *themeHax0rR3d) TextSecondary() gothememe.Color { return gothememe.Hex("#fafafa") }
func (t *themeHax0rR3d) TextMuted() gothememe.Color     { return gothememe.Hex("#554040") }
func (t *themeHax0rR3d) TextInverted() gothememe.Color  { return gothememe.Hex("#200101") }

// Accent/Brand colors
func (t *themeHax0rR3d) Accent() gothememe.Color          { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) AccentSecondary() gothememe.Color { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) Brand() gothememe.Color           { return gothememe.Hex("#b00d0d") }

// Border colors
func (t *themeHax0rR3d) Border() gothememe.Color       { return gothememe.Hex("#554040") }
func (t *themeHax0rR3d) BorderSubtle() gothememe.Color { return gothememe.Hex("#1f0000") }
func (t *themeHax0rR3d) BorderStrong() gothememe.Color { return gothememe.Hex("#fafafa") }

// Semantic colors
func (t *themeHax0rR3d) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b00d0d").WithAlpha(0.1),
		Border:     gothememe.Hex("#b00d0d").WithAlpha(0.3),
		Text:       gothememe.Hex("#b00d0d"),
	}
}

func (t *themeHax0rR3d) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b00d0d").WithAlpha(0.1),
		Border:     gothememe.Hex("#b00d0d").WithAlpha(0.3),
		Text:       gothememe.Hex("#b00d0d"),
	}
}

func (t *themeHax0rR3d) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b00d0d").WithAlpha(0.1),
		Border:     gothememe.Hex("#b00d0d").WithAlpha(0.3),
		Text:       gothememe.Hex("#b00d0d"),
	}
}

func (t *themeHax0rR3d) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b00d0d").WithAlpha(0.1),
		Border:     gothememe.Hex("#b00d0d").WithAlpha(0.3),
		Text:       gothememe.Hex("#b00d0d"),
	}
}

// ANSI colors
func (t *themeHax0rR3d) Black() gothememe.Color        { return gothememe.Hex("#1f0000") }
func (t *themeHax0rR3d) Red() gothememe.Color          { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) Green() gothememe.Color        { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) Yellow() gothememe.Color       { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) Blue() gothememe.Color         { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) Purple() gothememe.Color       { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) Cyan() gothememe.Color         { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) White() gothememe.Color        { return gothememe.Hex("#fafafa") }
func (t *themeHax0rR3d) BrightBlack() gothememe.Color  { return gothememe.Hex("#554040") }
func (t *themeHax0rR3d) BrightRed() gothememe.Color    { return gothememe.Hex("#ff1111") }
func (t *themeHax0rR3d) BrightGreen() gothememe.Color  { return gothememe.Hex("#ff1010") }
func (t *themeHax0rR3d) BrightYellow() gothememe.Color { return gothememe.Hex("#ff1010") }
func (t *themeHax0rR3d) BrightBlue() gothememe.Color   { return gothememe.Hex("#ff1010") }
func (t *themeHax0rR3d) BrightPurple() gothememe.Color { return gothememe.Hex("#ff1010") }
func (t *themeHax0rR3d) BrightCyan() gothememe.Color   { return gothememe.Hex("#ff1010") }
func (t *themeHax0rR3d) BrightWhite() gothememe.Color  { return gothememe.Hex("#fefefe") }

// Code/Syntax highlighting colors
func (t *themeHax0rR3d) CodeBackground() gothememe.Color  { return gothememe.Hex("#200101") }
func (t *themeHax0rR3d) CodeText() gothememe.Color        { return gothememe.Hex("#b10e0e") }
func (t *themeHax0rR3d) CodeComment() gothememe.Color     { return gothememe.Hex("#554040") }
func (t *themeHax0rR3d) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) CodeString() gothememe.Color      { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) CodeNumber() gothememe.Color      { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) CodeFunction() gothememe.Color    { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) CodeOperator() gothememe.Color    { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) CodePunctuation() gothememe.Color { return gothememe.Hex("#b10e0e") }
func (t *themeHax0rR3d) CodeVariable() gothememe.Color    { return gothememe.Hex("#b00d0d") }
func (t *themeHax0rR3d) CodeConstant() gothememe.Color    { return gothememe.Hex("#ff1010") }
func (t *themeHax0rR3d) CodeType() gothememe.Color        { return gothememe.Hex("#ff1010") }
