// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeManPageInstance is the Man Page color theme singleton.
var themeManPageInstance gothememe.Theme = &themeManPage{}

// themeManPage implements the Man Page theme.
type themeManPage struct{}

func (t *themeManPage) ID() string          { return "man_page" }
func (t *themeManPage) DisplayName() string { return "Man Page" }
func (t *themeManPage) Description() string { return "Man Page color theme" }
func (t *themeManPage) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeManPage) License() string     { return "MIT" }
func (t *themeManPage) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeManPage) IsDark() bool        { return false }

// Background colors
func (t *themeManPage) Background() gothememe.Color          { return gothememe.Hex("#fef49c") }
func (t *themeManPage) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeManPage) Surface() gothememe.Color             { return gothememe.Hex("#a4c9cd") }
func (t *themeManPage) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#666666") }

// Text colors
func (t *themeManPage) TextPrimary() gothememe.Color   { return gothememe.Hex("#000000") }
func (t *themeManPage) TextSecondary() gothememe.Color { return gothememe.Hex("#b2b2b2") }
func (t *themeManPage) TextMuted() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeManPage) TextInverted() gothememe.Color  { return gothememe.Hex("#fef49c") }

// Accent/Brand colors
func (t *themeManPage) Accent() gothememe.Color          { return gothememe.Hex("#0000b2") }
func (t *themeManPage) AccentSecondary() gothememe.Color { return gothememe.Hex("#b200b2") }
func (t *themeManPage) Brand() gothememe.Color           { return gothememe.Hex("#0000b2") }

// Border colors
func (t *themeManPage) Border() gothememe.Color       { return gothememe.Hex("#666666") }
func (t *themeManPage) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeManPage) BorderStrong() gothememe.Color { return gothememe.Hex("#b2b2b2") }

// Semantic colors
func (t *themeManPage) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00a600").WithAlpha(0.1),
		Border:     gothememe.Hex("#00a600").WithAlpha(0.3),
		Text:       gothememe.Hex("#00a600"),
	}
}

func (t *themeManPage) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#999900").WithAlpha(0.1),
		Border:     gothememe.Hex("#999900").WithAlpha(0.3),
		Text:       gothememe.Hex("#999900"),
	}
}

func (t *themeManPage) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cc0000").WithAlpha(0.1),
		Border:     gothememe.Hex("#cc0000").WithAlpha(0.3),
		Text:       gothememe.Hex("#cc0000"),
	}
}

func (t *themeManPage) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00a6b2").WithAlpha(0.1),
		Border:     gothememe.Hex("#00a6b2").WithAlpha(0.3),
		Text:       gothememe.Hex("#00a6b2"),
	}
}

// ANSI colors
func (t *themeManPage) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeManPage) Red() gothememe.Color          { return gothememe.Hex("#cc0000") }
func (t *themeManPage) Green() gothememe.Color        { return gothememe.Hex("#00a600") }
func (t *themeManPage) Yellow() gothememe.Color       { return gothememe.Hex("#999900") }
func (t *themeManPage) Blue() gothememe.Color         { return gothememe.Hex("#0000b2") }
func (t *themeManPage) Purple() gothememe.Color       { return gothememe.Hex("#b200b2") }
func (t *themeManPage) Cyan() gothememe.Color         { return gothememe.Hex("#00a6b2") }
func (t *themeManPage) White() gothememe.Color        { return gothememe.Hex("#b2b2b2") }
func (t *themeManPage) BrightBlack() gothememe.Color  { return gothememe.Hex("#666666") }
func (t *themeManPage) BrightRed() gothememe.Color    { return gothememe.Hex("#e50000") }
func (t *themeManPage) BrightGreen() gothememe.Color  { return gothememe.Hex("#00cc00") }
func (t *themeManPage) BrightYellow() gothememe.Color { return gothememe.Hex("#bfbf00") }
func (t *themeManPage) BrightBlue() gothememe.Color   { return gothememe.Hex("#0000ff") }
func (t *themeManPage) BrightPurple() gothememe.Color { return gothememe.Hex("#e500e5") }
func (t *themeManPage) BrightCyan() gothememe.Color   { return gothememe.Hex("#00cbcb") }
func (t *themeManPage) BrightWhite() gothememe.Color  { return gothememe.Hex("#e5e5e5") }

// Code/Syntax highlighting colors
func (t *themeManPage) CodeBackground() gothememe.Color  { return gothememe.Hex("#fef49c") }
func (t *themeManPage) CodeText() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeManPage) CodeComment() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeManPage) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b200b2") }
func (t *themeManPage) CodeString() gothememe.Color      { return gothememe.Hex("#00a600") }
func (t *themeManPage) CodeNumber() gothememe.Color      { return gothememe.Hex("#999900") }
func (t *themeManPage) CodeFunction() gothememe.Color    { return gothememe.Hex("#0000b2") }
func (t *themeManPage) CodeOperator() gothememe.Color    { return gothememe.Hex("#cc0000") }
func (t *themeManPage) CodePunctuation() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeManPage) CodeVariable() gothememe.Color    { return gothememe.Hex("#00a6b2") }
func (t *themeManPage) CodeConstant() gothememe.Color    { return gothememe.Hex("#bfbf00") }
func (t *themeManPage) CodeType() gothememe.Color        { return gothememe.Hex("#00cbcb") }
