// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeMaterialDesignColorsInstance is the Material Design Colors color theme singleton.
var themeMaterialDesignColorsInstance gothememe.Theme = &themeMaterialDesignColors{}

// themeMaterialDesignColors implements the Material Design Colors theme.
type themeMaterialDesignColors struct{}

func (t *themeMaterialDesignColors) ID() string          { return "material_design_colors" }
func (t *themeMaterialDesignColors) DisplayName() string { return "Material Design Colors" }
func (t *themeMaterialDesignColors) Description() string { return "Material Design Colors color theme" }
func (t *themeMaterialDesignColors) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeMaterialDesignColors) License() string     { return "MIT" }
func (t *themeMaterialDesignColors) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeMaterialDesignColors) IsDark() bool { return true }

// Background colors
func (t *themeMaterialDesignColors) Background() gothememe.Color { return gothememe.Hex("#1d262a") }
func (t *themeMaterialDesignColors) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#435b67")
}
func (t *themeMaterialDesignColors) Surface() gothememe.Color { return gothememe.Hex("#4e6a78") }
func (t *themeMaterialDesignColors) SurfaceSecondary() gothememe.Color {
	return gothememe.Hex("#a1b0b8")
}

// Text colors
func (t *themeMaterialDesignColors) TextPrimary() gothememe.Color   { return gothememe.Hex("#e7ebed") }
func (t *themeMaterialDesignColors) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeMaterialDesignColors) TextMuted() gothememe.Color     { return gothememe.Hex("#a1b0b8") }
func (t *themeMaterialDesignColors) TextInverted() gothememe.Color  { return gothememe.Hex("#1d262a") }

// Accent/Brand colors
func (t *themeMaterialDesignColors) Accent() gothememe.Color { return gothememe.Hex("#37b6ff") }
func (t *themeMaterialDesignColors) AccentSecondary() gothememe.Color {
	return gothememe.Hex("#fc226e")
}
func (t *themeMaterialDesignColors) Brand() gothememe.Color { return gothememe.Hex("#37b6ff") }

// Border colors
func (t *themeMaterialDesignColors) Border() gothememe.Color       { return gothememe.Hex("#a1b0b8") }
func (t *themeMaterialDesignColors) BorderSubtle() gothememe.Color { return gothememe.Hex("#435b67") }
func (t *themeMaterialDesignColors) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeMaterialDesignColors) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5cf19e").WithAlpha(0.1),
		Border:     gothememe.Hex("#5cf19e").WithAlpha(0.3),
		Text:       gothememe.Hex("#5cf19e"),
	}
}

func (t *themeMaterialDesignColors) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fed032").WithAlpha(0.1),
		Border:     gothememe.Hex("#fed032").WithAlpha(0.3),
		Text:       gothememe.Hex("#fed032"),
	}
}

func (t *themeMaterialDesignColors) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fc3841").WithAlpha(0.1),
		Border:     gothememe.Hex("#fc3841").WithAlpha(0.3),
		Text:       gothememe.Hex("#fc3841"),
	}
}

func (t *themeMaterialDesignColors) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#59ffd1").WithAlpha(0.1),
		Border:     gothememe.Hex("#59ffd1").WithAlpha(0.3),
		Text:       gothememe.Hex("#59ffd1"),
	}
}

// ANSI colors
func (t *themeMaterialDesignColors) Black() gothememe.Color        { return gothememe.Hex("#435b67") }
func (t *themeMaterialDesignColors) Red() gothememe.Color          { return gothememe.Hex("#fc3841") }
func (t *themeMaterialDesignColors) Green() gothememe.Color        { return gothememe.Hex("#5cf19e") }
func (t *themeMaterialDesignColors) Yellow() gothememe.Color       { return gothememe.Hex("#fed032") }
func (t *themeMaterialDesignColors) Blue() gothememe.Color         { return gothememe.Hex("#37b6ff") }
func (t *themeMaterialDesignColors) Purple() gothememe.Color       { return gothememe.Hex("#fc226e") }
func (t *themeMaterialDesignColors) Cyan() gothememe.Color         { return gothememe.Hex("#59ffd1") }
func (t *themeMaterialDesignColors) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeMaterialDesignColors) BrightBlack() gothememe.Color  { return gothememe.Hex("#a1b0b8") }
func (t *themeMaterialDesignColors) BrightRed() gothememe.Color    { return gothememe.Hex("#fc746d") }
func (t *themeMaterialDesignColors) BrightGreen() gothememe.Color  { return gothememe.Hex("#adf7be") }
func (t *themeMaterialDesignColors) BrightYellow() gothememe.Color { return gothememe.Hex("#fee16c") }
func (t *themeMaterialDesignColors) BrightBlue() gothememe.Color   { return gothememe.Hex("#70cfff") }
func (t *themeMaterialDesignColors) BrightPurple() gothememe.Color { return gothememe.Hex("#fc669b") }
func (t *themeMaterialDesignColors) BrightCyan() gothememe.Color   { return gothememe.Hex("#9affe6") }
func (t *themeMaterialDesignColors) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeMaterialDesignColors) CodeBackground() gothememe.Color { return gothememe.Hex("#1d262a") }
func (t *themeMaterialDesignColors) CodeText() gothememe.Color       { return gothememe.Hex("#e7ebed") }
func (t *themeMaterialDesignColors) CodeComment() gothememe.Color    { return gothememe.Hex("#a1b0b8") }
func (t *themeMaterialDesignColors) CodeKeyword() gothememe.Color    { return gothememe.Hex("#fc226e") }
func (t *themeMaterialDesignColors) CodeString() gothememe.Color     { return gothememe.Hex("#5cf19e") }
func (t *themeMaterialDesignColors) CodeNumber() gothememe.Color     { return gothememe.Hex("#fed032") }
func (t *themeMaterialDesignColors) CodeFunction() gothememe.Color   { return gothememe.Hex("#37b6ff") }
func (t *themeMaterialDesignColors) CodeOperator() gothememe.Color   { return gothememe.Hex("#fc3841") }
func (t *themeMaterialDesignColors) CodePunctuation() gothememe.Color {
	return gothememe.Hex("#e7ebed")
}
func (t *themeMaterialDesignColors) CodeVariable() gothememe.Color { return gothememe.Hex("#59ffd1") }
func (t *themeMaterialDesignColors) CodeConstant() gothememe.Color { return gothememe.Hex("#fee16c") }
func (t *themeMaterialDesignColors) CodeType() gothememe.Color     { return gothememe.Hex("#9affe6") }
