// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeMatrixInstance is the Matrix color theme singleton.
var themeMatrixInstance gothememe.Theme = &themeMatrix{}

// themeMatrix implements the Matrix theme.
type themeMatrix struct{}

func (t *themeMatrix) ID() string          { return "matrix" }
func (t *themeMatrix) DisplayName() string { return "Matrix" }
func (t *themeMatrix) Description() string { return "Matrix color theme" }
func (t *themeMatrix) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeMatrix) License() string     { return "MIT" }
func (t *themeMatrix) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeMatrix) IsDark() bool        { return true }

// Background colors
func (t *themeMatrix) Background() gothememe.Color          { return gothememe.Hex("#0f191c") }
func (t *themeMatrix) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#0f191c") }
func (t *themeMatrix) Surface() gothememe.Color             { return gothememe.Hex("#18282e") }
func (t *themeMatrix) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#688060") }

// Text colors
func (t *themeMatrix) TextPrimary() gothememe.Color   { return gothememe.Hex("#426644") }
func (t *themeMatrix) TextSecondary() gothememe.Color { return gothememe.Hex("#507350") }
func (t *themeMatrix) TextMuted() gothememe.Color     { return gothememe.Hex("#688060") }
func (t *themeMatrix) TextInverted() gothememe.Color  { return gothememe.Hex("#0f191c") }

// Accent/Brand colors
func (t *themeMatrix) Accent() gothememe.Color          { return gothememe.Hex("#3f5242") }
func (t *themeMatrix) AccentSecondary() gothememe.Color { return gothememe.Hex("#409931") }
func (t *themeMatrix) Brand() gothememe.Color           { return gothememe.Hex("#3f5242") }

// Border colors
func (t *themeMatrix) Border() gothememe.Color       { return gothememe.Hex("#688060") }
func (t *themeMatrix) BorderSubtle() gothememe.Color { return gothememe.Hex("#0f191c") }
func (t *themeMatrix) BorderStrong() gothememe.Color { return gothememe.Hex("#507350") }

// Semantic colors
func (t *themeMatrix) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#82d967").WithAlpha(0.1),
		Border:     gothememe.Hex("#82d967").WithAlpha(0.3),
		Text:       gothememe.Hex("#82d967"),
	}
}

func (t *themeMatrix) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ffd700").WithAlpha(0.1),
		Border:     gothememe.Hex("#ffd700").WithAlpha(0.3),
		Text:       gothememe.Hex("#ffd700"),
	}
}

func (t *themeMatrix) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#23755a").WithAlpha(0.1),
		Border:     gothememe.Hex("#23755a").WithAlpha(0.3),
		Text:       gothememe.Hex("#23755a"),
	}
}

func (t *themeMatrix) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#50b45a").WithAlpha(0.1),
		Border:     gothememe.Hex("#50b45a").WithAlpha(0.3),
		Text:       gothememe.Hex("#50b45a"),
	}
}

// ANSI colors
func (t *themeMatrix) Black() gothememe.Color        { return gothememe.Hex("#0f191c") }
func (t *themeMatrix) Red() gothememe.Color          { return gothememe.Hex("#23755a") }
func (t *themeMatrix) Green() gothememe.Color        { return gothememe.Hex("#82d967") }
func (t *themeMatrix) Yellow() gothememe.Color       { return gothememe.Hex("#ffd700") }
func (t *themeMatrix) Blue() gothememe.Color         { return gothememe.Hex("#3f5242") }
func (t *themeMatrix) Purple() gothememe.Color       { return gothememe.Hex("#409931") }
func (t *themeMatrix) Cyan() gothememe.Color         { return gothememe.Hex("#50b45a") }
func (t *themeMatrix) White() gothememe.Color        { return gothememe.Hex("#507350") }
func (t *themeMatrix) BrightBlack() gothememe.Color  { return gothememe.Hex("#688060") }
func (t *themeMatrix) BrightRed() gothememe.Color    { return gothememe.Hex("#2fc079") }
func (t *themeMatrix) BrightGreen() gothememe.Color  { return gothememe.Hex("#90d762") }
func (t *themeMatrix) BrightYellow() gothememe.Color { return gothememe.Hex("#faff00") }
func (t *themeMatrix) BrightBlue() gothememe.Color   { return gothememe.Hex("#4f7e7e") }
func (t *themeMatrix) BrightPurple() gothememe.Color { return gothememe.Hex("#11ff25") }
func (t *themeMatrix) BrightCyan() gothememe.Color   { return gothememe.Hex("#c1ff8a") }
func (t *themeMatrix) BrightWhite() gothememe.Color  { return gothememe.Hex("#678c61") }

// Code/Syntax highlighting colors
func (t *themeMatrix) CodeBackground() gothememe.Color  { return gothememe.Hex("#0f191c") }
func (t *themeMatrix) CodeText() gothememe.Color        { return gothememe.Hex("#426644") }
func (t *themeMatrix) CodeComment() gothememe.Color     { return gothememe.Hex("#688060") }
func (t *themeMatrix) CodeKeyword() gothememe.Color     { return gothememe.Hex("#409931") }
func (t *themeMatrix) CodeString() gothememe.Color      { return gothememe.Hex("#82d967") }
func (t *themeMatrix) CodeNumber() gothememe.Color      { return gothememe.Hex("#ffd700") }
func (t *themeMatrix) CodeFunction() gothememe.Color    { return gothememe.Hex("#3f5242") }
func (t *themeMatrix) CodeOperator() gothememe.Color    { return gothememe.Hex("#23755a") }
func (t *themeMatrix) CodePunctuation() gothememe.Color { return gothememe.Hex("#426644") }
func (t *themeMatrix) CodeVariable() gothememe.Color    { return gothememe.Hex("#50b45a") }
func (t *themeMatrix) CodeConstant() gothememe.Color    { return gothememe.Hex("#faff00") }
func (t *themeMatrix) CodeType() gothememe.Color        { return gothememe.Hex("#c1ff8a") }
