// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeMisteriosoInstance is the Misterioso color theme singleton.
var themeMisteriosoInstance gothememe.Theme = &themeMisterioso{}

// themeMisterioso implements the Misterioso theme.
type themeMisterioso struct{}

func (t *themeMisterioso) ID() string          { return "misterioso" }
func (t *themeMisterioso) DisplayName() string { return "Misterioso" }
func (t *themeMisterioso) Description() string { return "Misterioso color theme" }
func (t *themeMisterioso) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeMisterioso) License() string     { return "MIT" }
func (t *themeMisterioso) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeMisterioso) IsDark() bool        { return true }

// Background colors
func (t *themeMisterioso) Background() gothememe.Color          { return gothememe.Hex("#2d3743") }
func (t *themeMisterioso) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeMisterioso) Surface() gothememe.Color             { return gothememe.Hex("#2d37ff") }
func (t *themeMisterioso) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#626262") }

// Text colors
func (t *themeMisterioso) TextPrimary() gothememe.Color   { return gothememe.Hex("#e1e1e0") }
func (t *themeMisterioso) TextSecondary() gothememe.Color { return gothememe.Hex("#e1e1e0") }
func (t *themeMisterioso) TextMuted() gothememe.Color     { return gothememe.Hex("#626262") }
func (t *themeMisterioso) TextInverted() gothememe.Color  { return gothememe.Hex("#2d3743") }

// Accent/Brand colors
func (t *themeMisterioso) Accent() gothememe.Color          { return gothememe.Hex("#338f86") }
func (t *themeMisterioso) AccentSecondary() gothememe.Color { return gothememe.Hex("#9414e6") }
func (t *themeMisterioso) Brand() gothememe.Color           { return gothememe.Hex("#338f86") }

// Border colors
func (t *themeMisterioso) Border() gothememe.Color       { return gothememe.Hex("#626262") }
func (t *themeMisterioso) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeMisterioso) BorderStrong() gothememe.Color { return gothememe.Hex("#e1e1e0") }

// Semantic colors
func (t *themeMisterioso) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#74af68").WithAlpha(0.1),
		Border:     gothememe.Hex("#74af68").WithAlpha(0.3),
		Text:       gothememe.Hex("#74af68"),
	}
}

func (t *themeMisterioso) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ffad29").WithAlpha(0.1),
		Border:     gothememe.Hex("#ffad29").WithAlpha(0.3),
		Text:       gothememe.Hex("#ffad29"),
	}
}

func (t *themeMisterioso) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff4242").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff4242").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff4242"),
	}
}

func (t *themeMisterioso) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#23d7d7").WithAlpha(0.1),
		Border:     gothememe.Hex("#23d7d7").WithAlpha(0.3),
		Text:       gothememe.Hex("#23d7d7"),
	}
}

// ANSI colors
func (t *themeMisterioso) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeMisterioso) Red() gothememe.Color          { return gothememe.Hex("#ff4242") }
func (t *themeMisterioso) Green() gothememe.Color        { return gothememe.Hex("#74af68") }
func (t *themeMisterioso) Yellow() gothememe.Color       { return gothememe.Hex("#ffad29") }
func (t *themeMisterioso) Blue() gothememe.Color         { return gothememe.Hex("#338f86") }
func (t *themeMisterioso) Purple() gothememe.Color       { return gothememe.Hex("#9414e6") }
func (t *themeMisterioso) Cyan() gothememe.Color         { return gothememe.Hex("#23d7d7") }
func (t *themeMisterioso) White() gothememe.Color        { return gothememe.Hex("#e1e1e0") }
func (t *themeMisterioso) BrightBlack() gothememe.Color  { return gothememe.Hex("#626262") }
func (t *themeMisterioso) BrightRed() gothememe.Color    { return gothememe.Hex("#ff3242") }
func (t *themeMisterioso) BrightGreen() gothememe.Color  { return gothememe.Hex("#74cd68") }
func (t *themeMisterioso) BrightYellow() gothememe.Color { return gothememe.Hex("#ffb929") }
func (t *themeMisterioso) BrightBlue() gothememe.Color   { return gothememe.Hex("#23d7d7") }
func (t *themeMisterioso) BrightPurple() gothememe.Color { return gothememe.Hex("#ff37ff") }
func (t *themeMisterioso) BrightCyan() gothememe.Color   { return gothememe.Hex("#00ede1") }
func (t *themeMisterioso) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeMisterioso) CodeBackground() gothememe.Color  { return gothememe.Hex("#2d3743") }
func (t *themeMisterioso) CodeText() gothememe.Color        { return gothememe.Hex("#e1e1e0") }
func (t *themeMisterioso) CodeComment() gothememe.Color     { return gothememe.Hex("#626262") }
func (t *themeMisterioso) CodeKeyword() gothememe.Color     { return gothememe.Hex("#9414e6") }
func (t *themeMisterioso) CodeString() gothememe.Color      { return gothememe.Hex("#74af68") }
func (t *themeMisterioso) CodeNumber() gothememe.Color      { return gothememe.Hex("#ffad29") }
func (t *themeMisterioso) CodeFunction() gothememe.Color    { return gothememe.Hex("#338f86") }
func (t *themeMisterioso) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff4242") }
func (t *themeMisterioso) CodePunctuation() gothememe.Color { return gothememe.Hex("#e1e1e0") }
func (t *themeMisterioso) CodeVariable() gothememe.Color    { return gothememe.Hex("#23d7d7") }
func (t *themeMisterioso) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffb929") }
func (t *themeMisterioso) CodeType() gothememe.Color        { return gothememe.Hex("#00ede1") }
