// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeNoClownFiestaInstance is the No Clown Fiesta color theme singleton.
var themeNoClownFiestaInstance gothememe.Theme = &themeNoClownFiesta{}

// themeNoClownFiesta implements the No Clown Fiesta theme.
type themeNoClownFiesta struct{}

func (t *themeNoClownFiesta) ID() string          { return "no_clown_fiesta" }
func (t *themeNoClownFiesta) DisplayName() string { return "No Clown Fiesta" }
func (t *themeNoClownFiesta) Description() string { return "No Clown Fiesta color theme" }
func (t *themeNoClownFiesta) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeNoClownFiesta) License() string     { return "MIT" }
func (t *themeNoClownFiesta) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeNoClownFiesta) IsDark() bool { return true }

// Background colors
func (t *themeNoClownFiesta) Background() gothememe.Color          { return gothememe.Hex("#101010") }
func (t *themeNoClownFiesta) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#151515") }
func (t *themeNoClownFiesta) Surface() gothememe.Color             { return gothememe.Hex("#696d79") }
func (t *themeNoClownFiesta) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#727272") }

// Text colors
func (t *themeNoClownFiesta) TextPrimary() gothememe.Color   { return gothememe.Hex("#e0e1e4") }
func (t *themeNoClownFiesta) TextSecondary() gothememe.Color { return gothememe.Hex("#e1e1e1") }
func (t *themeNoClownFiesta) TextMuted() gothememe.Color     { return gothememe.Hex("#727272") }
func (t *themeNoClownFiesta) TextInverted() gothememe.Color  { return gothememe.Hex("#101010") }

// Accent/Brand colors
func (t *themeNoClownFiesta) Accent() gothememe.Color          { return gothememe.Hex("#bad7ff") }
func (t *themeNoClownFiesta) AccentSecondary() gothememe.Color { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiesta) Brand() gothememe.Color           { return gothememe.Hex("#bad7ff") }

// Border colors
func (t *themeNoClownFiesta) Border() gothememe.Color       { return gothememe.Hex("#727272") }
func (t *themeNoClownFiesta) BorderSubtle() gothememe.Color { return gothememe.Hex("#151515") }
func (t *themeNoClownFiesta) BorderStrong() gothememe.Color { return gothememe.Hex("#e1e1e1") }

// Semantic colors
func (t *themeNoClownFiesta) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#90a959").WithAlpha(0.1),
		Border:     gothememe.Hex("#90a959").WithAlpha(0.3),
		Text:       gothememe.Hex("#90a959"),
	}
}

func (t *themeNoClownFiesta) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f4bf75").WithAlpha(0.1),
		Border:     gothememe.Hex("#f4bf75").WithAlpha(0.3),
		Text:       gothememe.Hex("#f4bf75"),
	}
}

func (t *themeNoClownFiesta) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b46958").WithAlpha(0.1),
		Border:     gothememe.Hex("#b46958").WithAlpha(0.3),
		Text:       gothememe.Hex("#b46958"),
	}
}

func (t *themeNoClownFiesta) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#88afa2").WithAlpha(0.1),
		Border:     gothememe.Hex("#88afa2").WithAlpha(0.3),
		Text:       gothememe.Hex("#88afa2"),
	}
}

// ANSI colors
func (t *themeNoClownFiesta) Black() gothememe.Color        { return gothememe.Hex("#151515") }
func (t *themeNoClownFiesta) Red() gothememe.Color          { return gothememe.Hex("#b46958") }
func (t *themeNoClownFiesta) Green() gothememe.Color        { return gothememe.Hex("#90a959") }
func (t *themeNoClownFiesta) Yellow() gothememe.Color       { return gothememe.Hex("#f4bf75") }
func (t *themeNoClownFiesta) Blue() gothememe.Color         { return gothememe.Hex("#bad7ff") }
func (t *themeNoClownFiesta) Purple() gothememe.Color       { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiesta) Cyan() gothememe.Color         { return gothememe.Hex("#88afa2") }
func (t *themeNoClownFiesta) White() gothememe.Color        { return gothememe.Hex("#e1e1e1") }
func (t *themeNoClownFiesta) BrightBlack() gothememe.Color  { return gothememe.Hex("#727272") }
func (t *themeNoClownFiesta) BrightRed() gothememe.Color    { return gothememe.Hex("#7e97ab") }
func (t *themeNoClownFiesta) BrightGreen() gothememe.Color  { return gothememe.Hex("#90a959") }
func (t *themeNoClownFiesta) BrightYellow() gothememe.Color { return gothememe.Hex("#f4bf75") }
func (t *themeNoClownFiesta) BrightBlue() gothememe.Color   { return gothememe.Hex("#bad7ff") }
func (t *themeNoClownFiesta) BrightPurple() gothememe.Color { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiesta) BrightCyan() gothememe.Color   { return gothememe.Hex("#88afa2") }
func (t *themeNoClownFiesta) BrightWhite() gothememe.Color  { return gothememe.Hex("#afafaf") }

// Code/Syntax highlighting colors
func (t *themeNoClownFiesta) CodeBackground() gothememe.Color  { return gothememe.Hex("#101010") }
func (t *themeNoClownFiesta) CodeText() gothememe.Color        { return gothememe.Hex("#e0e1e4") }
func (t *themeNoClownFiesta) CodeComment() gothememe.Color     { return gothememe.Hex("#727272") }
func (t *themeNoClownFiesta) CodeKeyword() gothememe.Color     { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiesta) CodeString() gothememe.Color      { return gothememe.Hex("#90a959") }
func (t *themeNoClownFiesta) CodeNumber() gothememe.Color      { return gothememe.Hex("#f4bf75") }
func (t *themeNoClownFiesta) CodeFunction() gothememe.Color    { return gothememe.Hex("#bad7ff") }
func (t *themeNoClownFiesta) CodeOperator() gothememe.Color    { return gothememe.Hex("#b46958") }
func (t *themeNoClownFiesta) CodePunctuation() gothememe.Color { return gothememe.Hex("#e0e1e4") }
func (t *themeNoClownFiesta) CodeVariable() gothememe.Color    { return gothememe.Hex("#88afa2") }
func (t *themeNoClownFiesta) CodeConstant() gothememe.Color    { return gothememe.Hex("#f4bf75") }
func (t *themeNoClownFiesta) CodeType() gothememe.Color        { return gothememe.Hex("#88afa2") }
