// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeNoClownFiestaLightInstance is the No Clown Fiesta Light color theme singleton.
var themeNoClownFiestaLightInstance gothememe.Theme = &themeNoClownFiestaLight{}

// themeNoClownFiestaLight implements the No Clown Fiesta Light theme.
type themeNoClownFiestaLight struct{}

func (t *themeNoClownFiestaLight) ID() string          { return "no_clown_fiesta_light" }
func (t *themeNoClownFiestaLight) DisplayName() string { return "No Clown Fiesta Light" }
func (t *themeNoClownFiestaLight) Description() string { return "No Clown Fiesta Light color theme" }
func (t *themeNoClownFiestaLight) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeNoClownFiestaLight) License() string     { return "MIT" }
func (t *themeNoClownFiestaLight) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeNoClownFiestaLight) IsDark() bool { return true }

// Background colors
func (t *themeNoClownFiestaLight) Background() gothememe.Color { return gothememe.Hex("#e1e1e1") }
func (t *themeNoClownFiestaLight) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#d6d6d6")
}
func (t *themeNoClownFiestaLight) Surface() gothememe.Color          { return gothememe.Hex("#c6d5de") }
func (t *themeNoClownFiestaLight) SurfaceSecondary() gothememe.Color { return gothememe.Hex("#2b2b2b") }

// Text colors
func (t *themeNoClownFiestaLight) TextPrimary() gothememe.Color   { return gothememe.Hex("#151515") }
func (t *themeNoClownFiestaLight) TextSecondary() gothememe.Color { return gothememe.Hex("#151515") }
func (t *themeNoClownFiestaLight) TextMuted() gothememe.Color     { return gothememe.Hex("#2b2b2b") }
func (t *themeNoClownFiestaLight) TextInverted() gothememe.Color  { return gothememe.Hex("#e1e1e1") }

// Accent/Brand colors
func (t *themeNoClownFiestaLight) Accent() gothememe.Color          { return gothememe.Hex("#8ba1bf") }
func (t *themeNoClownFiestaLight) AccentSecondary() gothememe.Color { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiestaLight) Brand() gothememe.Color           { return gothememe.Hex("#8ba1bf") }

// Border colors
func (t *themeNoClownFiestaLight) Border() gothememe.Color       { return gothememe.Hex("#2b2b2b") }
func (t *themeNoClownFiestaLight) BorderSubtle() gothememe.Color { return gothememe.Hex("#d6d6d6") }
func (t *themeNoClownFiestaLight) BorderStrong() gothememe.Color { return gothememe.Hex("#151515") }

// Semantic colors
func (t *themeNoClownFiestaLight) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#677940").WithAlpha(0.1),
		Border:     gothememe.Hex("#677940").WithAlpha(0.3),
		Text:       gothememe.Hex("#677940"),
	}
}

func (t *themeNoClownFiestaLight) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b89058").WithAlpha(0.1),
		Border:     gothememe.Hex("#b89058").WithAlpha(0.3),
		Text:       gothememe.Hex("#b89058"),
	}
}

func (t *themeNoClownFiestaLight) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#874e42").WithAlpha(0.1),
		Border:     gothememe.Hex("#874e42").WithAlpha(0.3),
		Text:       gothememe.Hex("#874e42"),
	}
}

func (t *themeNoClownFiestaLight) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#3e5f66").WithAlpha(0.1),
		Border:     gothememe.Hex("#3e5f66").WithAlpha(0.3),
		Text:       gothememe.Hex("#3e5f66"),
	}
}

// ANSI colors
func (t *themeNoClownFiestaLight) Black() gothememe.Color        { return gothememe.Hex("#d6d6d6") }
func (t *themeNoClownFiestaLight) Red() gothememe.Color          { return gothememe.Hex("#874e42") }
func (t *themeNoClownFiestaLight) Green() gothememe.Color        { return gothememe.Hex("#677940") }
func (t *themeNoClownFiestaLight) Yellow() gothememe.Color       { return gothememe.Hex("#b89058") }
func (t *themeNoClownFiestaLight) Blue() gothememe.Color         { return gothememe.Hex("#8ba1bf") }
func (t *themeNoClownFiestaLight) Purple() gothememe.Color       { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiestaLight) Cyan() gothememe.Color         { return gothememe.Hex("#3e5f66") }
func (t *themeNoClownFiestaLight) White() gothememe.Color        { return gothememe.Hex("#151515") }
func (t *themeNoClownFiestaLight) BrightBlack() gothememe.Color  { return gothememe.Hex("#2b2b2b") }
func (t *themeNoClownFiestaLight) BrightRed() gothememe.Color    { return gothememe.Hex("#637786") }
func (t *themeNoClownFiestaLight) BrightGreen() gothememe.Color  { return gothememe.Hex("#677940") }
func (t *themeNoClownFiestaLight) BrightYellow() gothememe.Color { return gothememe.Hex("#b89058") }
func (t *themeNoClownFiestaLight) BrightBlue() gothememe.Color   { return gothememe.Hex("#93a2ab") }
func (t *themeNoClownFiestaLight) BrightPurple() gothememe.Color { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiestaLight) BrightCyan() gothememe.Color   { return gothememe.Hex("#99ab93") }
func (t *themeNoClownFiestaLight) BrightWhite() gothememe.Color  { return gothememe.Hex("#373737") }

// Code/Syntax highlighting colors
func (t *themeNoClownFiestaLight) CodeBackground() gothememe.Color  { return gothememe.Hex("#e1e1e1") }
func (t *themeNoClownFiestaLight) CodeText() gothememe.Color        { return gothememe.Hex("#151515") }
func (t *themeNoClownFiestaLight) CodeComment() gothememe.Color     { return gothememe.Hex("#2b2b2b") }
func (t *themeNoClownFiestaLight) CodeKeyword() gothememe.Color     { return gothememe.Hex("#aa759f") }
func (t *themeNoClownFiestaLight) CodeString() gothememe.Color      { return gothememe.Hex("#677940") }
func (t *themeNoClownFiestaLight) CodeNumber() gothememe.Color      { return gothememe.Hex("#b89058") }
func (t *themeNoClownFiestaLight) CodeFunction() gothememe.Color    { return gothememe.Hex("#8ba1bf") }
func (t *themeNoClownFiestaLight) CodeOperator() gothememe.Color    { return gothememe.Hex("#874e42") }
func (t *themeNoClownFiestaLight) CodePunctuation() gothememe.Color { return gothememe.Hex("#151515") }
func (t *themeNoClownFiestaLight) CodeVariable() gothememe.Color    { return gothememe.Hex("#3e5f66") }
func (t *themeNoClownFiestaLight) CodeConstant() gothememe.Color    { return gothememe.Hex("#b89058") }
func (t *themeNoClownFiestaLight) CodeType() gothememe.Color        { return gothememe.Hex("#99ab93") }
