// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeNovmbrInstance is the novmbr color theme singleton.
var themeNovmbrInstance gothememe.Theme = &themeNovmbr{}

// themeNovmbr implements the novmbr theme.
type themeNovmbr struct{}

func (t *themeNovmbr) ID() string          { return "novmbr" }
func (t *themeNovmbr) DisplayName() string { return "novmbr" }
func (t *themeNovmbr) Description() string { return "novmbr color theme" }
func (t *themeNovmbr) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeNovmbr) License() string     { return "MIT" }
func (t *themeNovmbr) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeNovmbr) IsDark() bool        { return true }

// Background colors
func (t *themeNovmbr) Background() gothememe.Color          { return gothememe.Hex("#241d1a") }
func (t *themeNovmbr) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#282a2e") }
func (t *themeNovmbr) Surface() gothememe.Color             { return gothememe.Hex("#241d1a") }
func (t *themeNovmbr) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#5d4e47") }

// Text colors
func (t *themeNovmbr) TextPrimary() gothememe.Color   { return gothememe.Hex("#c7b8ac") }
func (t *themeNovmbr) TextSecondary() gothememe.Color { return gothememe.Hex("#c7b8ac") }
func (t *themeNovmbr) TextMuted() gothememe.Color     { return gothememe.Hex("#5d4e47") }
func (t *themeNovmbr) TextInverted() gothememe.Color  { return gothememe.Hex("#241d1a") }

// Accent/Brand colors
func (t *themeNovmbr) Accent() gothememe.Color          { return gothememe.Hex("#2f7d7c") }
func (t *themeNovmbr) AccentSecondary() gothememe.Color { return gothememe.Hex("#b5896e") }
func (t *themeNovmbr) Brand() gothememe.Color           { return gothememe.Hex("#2f7d7c") }

// Border colors
func (t *themeNovmbr) Border() gothememe.Color       { return gothememe.Hex("#5d4e47") }
func (t *themeNovmbr) BorderSubtle() gothememe.Color { return gothememe.Hex("#282a2e") }
func (t *themeNovmbr) BorderStrong() gothememe.Color { return gothememe.Hex("#c7b8ac") }

// Semantic colors
func (t *themeNovmbr) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#9dac5f").WithAlpha(0.1),
		Border:     gothememe.Hex("#9dac5f").WithAlpha(0.3),
		Text:       gothememe.Hex("#9dac5f"),
	}
}

func (t *themeNovmbr) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cca75f").WithAlpha(0.1),
		Border:     gothememe.Hex("#cca75f").WithAlpha(0.3),
		Text:       gothememe.Hex("#cca75f"),
	}
}

func (t *themeNovmbr) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#9f6434").WithAlpha(0.1),
		Border:     gothememe.Hex("#9f6434").WithAlpha(0.3),
		Text:       gothememe.Hex("#9f6434"),
	}
}

func (t *themeNovmbr) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#52877f").WithAlpha(0.1),
		Border:     gothememe.Hex("#52877f").WithAlpha(0.3),
		Text:       gothememe.Hex("#52877f"),
	}
}

// ANSI colors
func (t *themeNovmbr) Black() gothememe.Color        { return gothememe.Hex("#282a2e") }
func (t *themeNovmbr) Red() gothememe.Color          { return gothememe.Hex("#9f6434") }
func (t *themeNovmbr) Green() gothememe.Color        { return gothememe.Hex("#9dac5f") }
func (t *themeNovmbr) Yellow() gothememe.Color       { return gothememe.Hex("#cca75f") }
func (t *themeNovmbr) Blue() gothememe.Color         { return gothememe.Hex("#2f7d7c") }
func (t *themeNovmbr) Purple() gothememe.Color       { return gothememe.Hex("#b5896e") }
func (t *themeNovmbr) Cyan() gothememe.Color         { return gothememe.Hex("#52877f") }
func (t *themeNovmbr) White() gothememe.Color        { return gothememe.Hex("#c7b8ac") }
func (t *themeNovmbr) BrightBlack() gothememe.Color  { return gothememe.Hex("#5d4e47") }
func (t *themeNovmbr) BrightRed() gothememe.Color    { return gothememe.Hex("#9f6434") }
func (t *themeNovmbr) BrightGreen() gothememe.Color  { return gothememe.Hex("#9dac5f") }
func (t *themeNovmbr) BrightYellow() gothememe.Color { return gothememe.Hex("#cca75f") }
func (t *themeNovmbr) BrightBlue() gothememe.Color   { return gothememe.Hex("#2f7d7c") }
func (t *themeNovmbr) BrightPurple() gothememe.Color { return gothememe.Hex("#b5896e") }
func (t *themeNovmbr) BrightCyan() gothememe.Color   { return gothememe.Hex("#52877f") }
func (t *themeNovmbr) BrightWhite() gothememe.Color  { return gothememe.Hex("#c7b8ac") }

// Code/Syntax highlighting colors
func (t *themeNovmbr) CodeBackground() gothememe.Color  { return gothememe.Hex("#241d1a") }
func (t *themeNovmbr) CodeText() gothememe.Color        { return gothememe.Hex("#c7b8ac") }
func (t *themeNovmbr) CodeComment() gothememe.Color     { return gothememe.Hex("#5d4e47") }
func (t *themeNovmbr) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b5896e") }
func (t *themeNovmbr) CodeString() gothememe.Color      { return gothememe.Hex("#9dac5f") }
func (t *themeNovmbr) CodeNumber() gothememe.Color      { return gothememe.Hex("#cca75f") }
func (t *themeNovmbr) CodeFunction() gothememe.Color    { return gothememe.Hex("#2f7d7c") }
func (t *themeNovmbr) CodeOperator() gothememe.Color    { return gothememe.Hex("#9f6434") }
func (t *themeNovmbr) CodePunctuation() gothememe.Color { return gothememe.Hex("#c7b8ac") }
func (t *themeNovmbr) CodeVariable() gothememe.Color    { return gothememe.Hex("#52877f") }
func (t *themeNovmbr) CodeConstant() gothememe.Color    { return gothememe.Hex("#cca75f") }
func (t *themeNovmbr) CodeType() gothememe.Color        { return gothememe.Hex("#52877f") }
