// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeOceanInstance is the Ocean color theme singleton.
var themeOceanInstance gothememe.Theme = &themeOcean{}

// themeOcean implements the Ocean theme.
type themeOcean struct{}

func (t *themeOcean) ID() string          { return "ocean" }
func (t *themeOcean) DisplayName() string { return "Ocean" }
func (t *themeOcean) Description() string { return "Ocean color theme" }
func (t *themeOcean) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeOcean) License() string     { return "MIT" }
func (t *themeOcean) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeOcean) IsDark() bool        { return true }

// Background colors
func (t *themeOcean) Background() gothememe.Color          { return gothememe.Hex("#224fbc") }
func (t *themeOcean) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeOcean) Surface() gothememe.Color             { return gothememe.Hex("#216dff") }
func (t *themeOcean) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#808080") }

// Text colors
func (t *themeOcean) TextPrimary() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeOcean) TextSecondary() gothememe.Color { return gothememe.Hex("#bfbfbf") }
func (t *themeOcean) TextMuted() gothememe.Color     { return gothememe.Hex("#808080") }
func (t *themeOcean) TextInverted() gothememe.Color  { return gothememe.Hex("#224fbc") }

// Accent/Brand colors
func (t *themeOcean) Accent() gothememe.Color          { return gothememe.Hex("#0000b2") }
func (t *themeOcean) AccentSecondary() gothememe.Color { return gothememe.Hex("#d826d8") }
func (t *themeOcean) Brand() gothememe.Color           { return gothememe.Hex("#0000b2") }

// Border colors
func (t *themeOcean) Border() gothememe.Color       { return gothememe.Hex("#808080") }
func (t *themeOcean) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeOcean) BorderStrong() gothememe.Color { return gothememe.Hex("#bfbfbf") }

// Semantic colors
func (t *themeOcean) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00a600").WithAlpha(0.1),
		Border:     gothememe.Hex("#00a600").WithAlpha(0.3),
		Text:       gothememe.Hex("#00a600"),
	}
}

func (t *themeOcean) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#999900").WithAlpha(0.1),
		Border:     gothememe.Hex("#999900").WithAlpha(0.3),
		Text:       gothememe.Hex("#999900"),
	}
}

func (t *themeOcean) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e64c4c").WithAlpha(0.1),
		Border:     gothememe.Hex("#e64c4c").WithAlpha(0.3),
		Text:       gothememe.Hex("#e64c4c"),
	}
}

func (t *themeOcean) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00a6b2").WithAlpha(0.1),
		Border:     gothememe.Hex("#00a6b2").WithAlpha(0.3),
		Text:       gothememe.Hex("#00a6b2"),
	}
}

// ANSI colors
func (t *themeOcean) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeOcean) Red() gothememe.Color          { return gothememe.Hex("#e64c4c") }
func (t *themeOcean) Green() gothememe.Color        { return gothememe.Hex("#00a600") }
func (t *themeOcean) Yellow() gothememe.Color       { return gothememe.Hex("#999900") }
func (t *themeOcean) Blue() gothememe.Color         { return gothememe.Hex("#0000b2") }
func (t *themeOcean) Purple() gothememe.Color       { return gothememe.Hex("#d826d8") }
func (t *themeOcean) Cyan() gothememe.Color         { return gothememe.Hex("#00a6b2") }
func (t *themeOcean) White() gothememe.Color        { return gothememe.Hex("#bfbfbf") }
func (t *themeOcean) BrightBlack() gothememe.Color  { return gothememe.Hex("#808080") }
func (t *themeOcean) BrightRed() gothememe.Color    { return gothememe.Hex("#ff1a1a") }
func (t *themeOcean) BrightGreen() gothememe.Color  { return gothememe.Hex("#00d900") }
func (t *themeOcean) BrightYellow() gothememe.Color { return gothememe.Hex("#e5e500") }
func (t *themeOcean) BrightBlue() gothememe.Color   { return gothememe.Hex("#7373ff") }
func (t *themeOcean) BrightPurple() gothememe.Color { return gothememe.Hex("#e500e5") }
func (t *themeOcean) BrightCyan() gothememe.Color   { return gothememe.Hex("#00e5e5") }
func (t *themeOcean) BrightWhite() gothememe.Color  { return gothememe.Hex("#e5e5e5") }

// Code/Syntax highlighting colors
func (t *themeOcean) CodeBackground() gothememe.Color  { return gothememe.Hex("#224fbc") }
func (t *themeOcean) CodeText() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeOcean) CodeComment() gothememe.Color     { return gothememe.Hex("#808080") }
func (t *themeOcean) CodeKeyword() gothememe.Color     { return gothememe.Hex("#d826d8") }
func (t *themeOcean) CodeString() gothememe.Color      { return gothememe.Hex("#00a600") }
func (t *themeOcean) CodeNumber() gothememe.Color      { return gothememe.Hex("#999900") }
func (t *themeOcean) CodeFunction() gothememe.Color    { return gothememe.Hex("#0000b2") }
func (t *themeOcean) CodeOperator() gothememe.Color    { return gothememe.Hex("#e64c4c") }
func (t *themeOcean) CodePunctuation() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeOcean) CodeVariable() gothememe.Color    { return gothememe.Hex("#00a6b2") }
func (t *themeOcean) CodeConstant() gothememe.Color    { return gothememe.Hex("#e5e500") }
func (t *themeOcean) CodeType() gothememe.Color        { return gothememe.Hex("#00e5e5") }
