// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themePoppingAndLockingInstance is the Popping And Locking color theme singleton.
var themePoppingAndLockingInstance gothememe.Theme = &themePoppingAndLocking{}

// themePoppingAndLocking implements the Popping And Locking theme.
type themePoppingAndLocking struct{}

func (t *themePoppingAndLocking) ID() string          { return "popping_and_locking" }
func (t *themePoppingAndLocking) DisplayName() string { return "Popping And Locking" }
func (t *themePoppingAndLocking) Description() string { return "Popping And Locking color theme" }
func (t *themePoppingAndLocking) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themePoppingAndLocking) License() string     { return "MIT" }
func (t *themePoppingAndLocking) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themePoppingAndLocking) IsDark() bool { return true }

// Background colors
func (t *themePoppingAndLocking) Background() gothememe.Color { return gothememe.Hex("#181921") }
func (t *themePoppingAndLocking) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#1d2021")
}
func (t *themePoppingAndLocking) Surface() gothememe.Color          { return gothememe.Hex("#ebdbb2") }
func (t *themePoppingAndLocking) SurfaceSecondary() gothememe.Color { return gothememe.Hex("#928374") }

// Text colors
func (t *themePoppingAndLocking) TextPrimary() gothememe.Color   { return gothememe.Hex("#ebdbb2") }
func (t *themePoppingAndLocking) TextSecondary() gothememe.Color { return gothememe.Hex("#a89984") }
func (t *themePoppingAndLocking) TextMuted() gothememe.Color     { return gothememe.Hex("#928374") }
func (t *themePoppingAndLocking) TextInverted() gothememe.Color  { return gothememe.Hex("#181921") }

// Accent/Brand colors
func (t *themePoppingAndLocking) Accent() gothememe.Color          { return gothememe.Hex("#458588") }
func (t *themePoppingAndLocking) AccentSecondary() gothememe.Color { return gothememe.Hex("#b16286") }
func (t *themePoppingAndLocking) Brand() gothememe.Color           { return gothememe.Hex("#458588") }

// Border colors
func (t *themePoppingAndLocking) Border() gothememe.Color       { return gothememe.Hex("#928374") }
func (t *themePoppingAndLocking) BorderSubtle() gothememe.Color { return gothememe.Hex("#1d2021") }
func (t *themePoppingAndLocking) BorderStrong() gothememe.Color { return gothememe.Hex("#a89984") }

// Semantic colors
func (t *themePoppingAndLocking) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#98971a").WithAlpha(0.1),
		Border:     gothememe.Hex("#98971a").WithAlpha(0.3),
		Text:       gothememe.Hex("#98971a"),
	}
}

func (t *themePoppingAndLocking) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d79921").WithAlpha(0.1),
		Border:     gothememe.Hex("#d79921").WithAlpha(0.3),
		Text:       gothememe.Hex("#d79921"),
	}
}

func (t *themePoppingAndLocking) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cc241d").WithAlpha(0.1),
		Border:     gothememe.Hex("#cc241d").WithAlpha(0.3),
		Text:       gothememe.Hex("#cc241d"),
	}
}

func (t *themePoppingAndLocking) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#689d6a").WithAlpha(0.1),
		Border:     gothememe.Hex("#689d6a").WithAlpha(0.3),
		Text:       gothememe.Hex("#689d6a"),
	}
}

// ANSI colors
func (t *themePoppingAndLocking) Black() gothememe.Color        { return gothememe.Hex("#1d2021") }
func (t *themePoppingAndLocking) Red() gothememe.Color          { return gothememe.Hex("#cc241d") }
func (t *themePoppingAndLocking) Green() gothememe.Color        { return gothememe.Hex("#98971a") }
func (t *themePoppingAndLocking) Yellow() gothememe.Color       { return gothememe.Hex("#d79921") }
func (t *themePoppingAndLocking) Blue() gothememe.Color         { return gothememe.Hex("#458588") }
func (t *themePoppingAndLocking) Purple() gothememe.Color       { return gothememe.Hex("#b16286") }
func (t *themePoppingAndLocking) Cyan() gothememe.Color         { return gothememe.Hex("#689d6a") }
func (t *themePoppingAndLocking) White() gothememe.Color        { return gothememe.Hex("#a89984") }
func (t *themePoppingAndLocking) BrightBlack() gothememe.Color  { return gothememe.Hex("#928374") }
func (t *themePoppingAndLocking) BrightRed() gothememe.Color    { return gothememe.Hex("#f42c3e") }
func (t *themePoppingAndLocking) BrightGreen() gothememe.Color  { return gothememe.Hex("#b8bb26") }
func (t *themePoppingAndLocking) BrightYellow() gothememe.Color { return gothememe.Hex("#fabd2f") }
func (t *themePoppingAndLocking) BrightBlue() gothememe.Color   { return gothememe.Hex("#99c6ca") }
func (t *themePoppingAndLocking) BrightPurple() gothememe.Color { return gothememe.Hex("#d3869b") }
func (t *themePoppingAndLocking) BrightCyan() gothememe.Color   { return gothememe.Hex("#7ec16e") }
func (t *themePoppingAndLocking) BrightWhite() gothememe.Color  { return gothememe.Hex("#ebdbb2") }

// Code/Syntax highlighting colors
func (t *themePoppingAndLocking) CodeBackground() gothememe.Color  { return gothememe.Hex("#181921") }
func (t *themePoppingAndLocking) CodeText() gothememe.Color        { return gothememe.Hex("#ebdbb2") }
func (t *themePoppingAndLocking) CodeComment() gothememe.Color     { return gothememe.Hex("#928374") }
func (t *themePoppingAndLocking) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b16286") }
func (t *themePoppingAndLocking) CodeString() gothememe.Color      { return gothememe.Hex("#98971a") }
func (t *themePoppingAndLocking) CodeNumber() gothememe.Color      { return gothememe.Hex("#d79921") }
func (t *themePoppingAndLocking) CodeFunction() gothememe.Color    { return gothememe.Hex("#458588") }
func (t *themePoppingAndLocking) CodeOperator() gothememe.Color    { return gothememe.Hex("#cc241d") }
func (t *themePoppingAndLocking) CodePunctuation() gothememe.Color { return gothememe.Hex("#ebdbb2") }
func (t *themePoppingAndLocking) CodeVariable() gothememe.Color    { return gothememe.Hex("#689d6a") }
func (t *themePoppingAndLocking) CodeConstant() gothememe.Color    { return gothememe.Hex("#fabd2f") }
func (t *themePoppingAndLocking) CodeType() gothememe.Color        { return gothememe.Hex("#7ec16e") }
