// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeRetroLegendsInstance is the Retro Legends color theme singleton.
var themeRetroLegendsInstance gothememe.Theme = &themeRetroLegends{}

// themeRetroLegends implements the Retro Legends theme.
type themeRetroLegends struct{}

func (t *themeRetroLegends) ID() string          { return "retro_legends" }
func (t *themeRetroLegends) DisplayName() string { return "Retro Legends" }
func (t *themeRetroLegends) Description() string { return "Retro Legends color theme" }
func (t *themeRetroLegends) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeRetroLegends) License() string     { return "MIT" }
func (t *themeRetroLegends) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeRetroLegends) IsDark() bool { return true }

// Background colors
func (t *themeRetroLegends) Background() gothememe.Color          { return gothememe.Hex("#0d0d0d") }
func (t *themeRetroLegends) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#262626") }
func (t *themeRetroLegends) Surface() gothememe.Color             { return gothememe.Hex("#336633") }
func (t *themeRetroLegends) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4c594c") }

// Text colors
func (t *themeRetroLegends) TextPrimary() gothememe.Color   { return gothememe.Hex("#45eb45") }
func (t *themeRetroLegends) TextSecondary() gothememe.Color { return gothememe.Hex("#bfe6bf") }
func (t *themeRetroLegends) TextMuted() gothememe.Color     { return gothememe.Hex("#4c594c") }
func (t *themeRetroLegends) TextInverted() gothememe.Color  { return gothememe.Hex("#0d0d0d") }

// Accent/Brand colors
func (t *themeRetroLegends) Accent() gothememe.Color          { return gothememe.Hex("#4066f2") }
func (t *themeRetroLegends) AccentSecondary() gothememe.Color { return gothememe.Hex("#bf4cf2") }
func (t *themeRetroLegends) Brand() gothememe.Color           { return gothememe.Hex("#4066f2") }

// Border colors
func (t *themeRetroLegends) Border() gothememe.Color       { return gothememe.Hex("#4c594c") }
func (t *themeRetroLegends) BorderSubtle() gothememe.Color { return gothememe.Hex("#262626") }
func (t *themeRetroLegends) BorderStrong() gothememe.Color { return gothememe.Hex("#bfe6bf") }

// Semantic colors
func (t *themeRetroLegends) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#45eb45").WithAlpha(0.1),
		Border:     gothememe.Hex("#45eb45").WithAlpha(0.3),
		Text:       gothememe.Hex("#45eb45"),
	}
}

func (t *themeRetroLegends) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f7bf2b").WithAlpha(0.1),
		Border:     gothememe.Hex("#f7bf2b").WithAlpha(0.3),
		Text:       gothememe.Hex("#f7bf2b"),
	}
}

func (t *themeRetroLegends) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#de5454").WithAlpha(0.1),
		Border:     gothememe.Hex("#de5454").WithAlpha(0.3),
		Text:       gothememe.Hex("#de5454"),
	}
}

func (t *themeRetroLegends) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#40d9e6").WithAlpha(0.1),
		Border:     gothememe.Hex("#40d9e6").WithAlpha(0.3),
		Text:       gothememe.Hex("#40d9e6"),
	}
}

// ANSI colors
func (t *themeRetroLegends) Black() gothememe.Color        { return gothememe.Hex("#262626") }
func (t *themeRetroLegends) Red() gothememe.Color          { return gothememe.Hex("#de5454") }
func (t *themeRetroLegends) Green() gothememe.Color        { return gothememe.Hex("#45eb45") }
func (t *themeRetroLegends) Yellow() gothememe.Color       { return gothememe.Hex("#f7bf2b") }
func (t *themeRetroLegends) Blue() gothememe.Color         { return gothememe.Hex("#4066f2") }
func (t *themeRetroLegends) Purple() gothememe.Color       { return gothememe.Hex("#bf4cf2") }
func (t *themeRetroLegends) Cyan() gothememe.Color         { return gothememe.Hex("#40d9e6") }
func (t *themeRetroLegends) White() gothememe.Color        { return gothememe.Hex("#bfe6bf") }
func (t *themeRetroLegends) BrightBlack() gothememe.Color  { return gothememe.Hex("#4c594c") }
func (t *themeRetroLegends) BrightRed() gothememe.Color    { return gothememe.Hex("#ff6666") }
func (t *themeRetroLegends) BrightGreen() gothememe.Color  { return gothememe.Hex("#59ff59") }
func (t *themeRetroLegends) BrightYellow() gothememe.Color { return gothememe.Hex("#ffd933") }
func (t *themeRetroLegends) BrightBlue() gothememe.Color   { return gothememe.Hex("#4c80ff") }
func (t *themeRetroLegends) BrightPurple() gothememe.Color { return gothememe.Hex("#e666ff") }
func (t *themeRetroLegends) BrightCyan() gothememe.Color   { return gothememe.Hex("#59e6ff") }
func (t *themeRetroLegends) BrightWhite() gothememe.Color  { return gothememe.Hex("#f2fff2") }

// Code/Syntax highlighting colors
func (t *themeRetroLegends) CodeBackground() gothememe.Color  { return gothememe.Hex("#0d0d0d") }
func (t *themeRetroLegends) CodeText() gothememe.Color        { return gothememe.Hex("#45eb45") }
func (t *themeRetroLegends) CodeComment() gothememe.Color     { return gothememe.Hex("#4c594c") }
func (t *themeRetroLegends) CodeKeyword() gothememe.Color     { return gothememe.Hex("#bf4cf2") }
func (t *themeRetroLegends) CodeString() gothememe.Color      { return gothememe.Hex("#45eb45") }
func (t *themeRetroLegends) CodeNumber() gothememe.Color      { return gothememe.Hex("#f7bf2b") }
func (t *themeRetroLegends) CodeFunction() gothememe.Color    { return gothememe.Hex("#4066f2") }
func (t *themeRetroLegends) CodeOperator() gothememe.Color    { return gothememe.Hex("#de5454") }
func (t *themeRetroLegends) CodePunctuation() gothememe.Color { return gothememe.Hex("#45eb45") }
func (t *themeRetroLegends) CodeVariable() gothememe.Color    { return gothememe.Hex("#40d9e6") }
func (t *themeRetroLegends) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffd933") }
func (t *themeRetroLegends) CodeType() gothememe.Color        { return gothememe.Hex("#59e6ff") }
