// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSeaShellsInstance is the Sea Shells color theme singleton.
var themeSeaShellsInstance gothememe.Theme = &themeSeaShells{}

// themeSeaShells implements the Sea Shells theme.
type themeSeaShells struct{}

func (t *themeSeaShells) ID() string          { return "sea_shells" }
func (t *themeSeaShells) DisplayName() string { return "Sea Shells" }
func (t *themeSeaShells) Description() string { return "Sea Shells color theme" }
func (t *themeSeaShells) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSeaShells) License() string     { return "MIT" }
func (t *themeSeaShells) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeSeaShells) IsDark() bool        { return true }

// Background colors
func (t *themeSeaShells) Background() gothememe.Color          { return gothememe.Hex("#09141b") }
func (t *themeSeaShells) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#17384c") }
func (t *themeSeaShells) Surface() gothememe.Color             { return gothememe.Hex("#1e4962") }
func (t *themeSeaShells) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#434b53") }

// Text colors
func (t *themeSeaShells) TextPrimary() gothememe.Color   { return gothememe.Hex("#deb88d") }
func (t *themeSeaShells) TextSecondary() gothememe.Color { return gothememe.Hex("#deb88d") }
func (t *themeSeaShells) TextMuted() gothememe.Color     { return gothememe.Hex("#434b53") }
func (t *themeSeaShells) TextInverted() gothememe.Color  { return gothememe.Hex("#09141b") }

// Accent/Brand colors
func (t *themeSeaShells) Accent() gothememe.Color          { return gothememe.Hex("#1e4950") }
func (t *themeSeaShells) AccentSecondary() gothememe.Color { return gothememe.Hex("#68d4f1") }
func (t *themeSeaShells) Brand() gothememe.Color           { return gothememe.Hex("#1e4950") }

// Border colors
func (t *themeSeaShells) Border() gothememe.Color       { return gothememe.Hex("#434b53") }
func (t *themeSeaShells) BorderSubtle() gothememe.Color { return gothememe.Hex("#17384c") }
func (t *themeSeaShells) BorderStrong() gothememe.Color { return gothememe.Hex("#deb88d") }

// Semantic colors
func (t *themeSeaShells) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#027c9b").WithAlpha(0.1),
		Border:     gothememe.Hex("#027c9b").WithAlpha(0.3),
		Text:       gothememe.Hex("#027c9b"),
	}
}

func (t *themeSeaShells) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fca02f").WithAlpha(0.1),
		Border:     gothememe.Hex("#fca02f").WithAlpha(0.3),
		Text:       gothememe.Hex("#fca02f"),
	}
}

func (t *themeSeaShells) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d15123").WithAlpha(0.1),
		Border:     gothememe.Hex("#d15123").WithAlpha(0.3),
		Text:       gothememe.Hex("#d15123"),
	}
}

func (t *themeSeaShells) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#50a3b5").WithAlpha(0.1),
		Border:     gothememe.Hex("#50a3b5").WithAlpha(0.3),
		Text:       gothememe.Hex("#50a3b5"),
	}
}

// ANSI colors
func (t *themeSeaShells) Black() gothememe.Color        { return gothememe.Hex("#17384c") }
func (t *themeSeaShells) Red() gothememe.Color          { return gothememe.Hex("#d15123") }
func (t *themeSeaShells) Green() gothememe.Color        { return gothememe.Hex("#027c9b") }
func (t *themeSeaShells) Yellow() gothememe.Color       { return gothememe.Hex("#fca02f") }
func (t *themeSeaShells) Blue() gothememe.Color         { return gothememe.Hex("#1e4950") }
func (t *themeSeaShells) Purple() gothememe.Color       { return gothememe.Hex("#68d4f1") }
func (t *themeSeaShells) Cyan() gothememe.Color         { return gothememe.Hex("#50a3b5") }
func (t *themeSeaShells) White() gothememe.Color        { return gothememe.Hex("#deb88d") }
func (t *themeSeaShells) BrightBlack() gothememe.Color  { return gothememe.Hex("#434b53") }
func (t *themeSeaShells) BrightRed() gothememe.Color    { return gothememe.Hex("#d48678") }
func (t *themeSeaShells) BrightGreen() gothememe.Color  { return gothememe.Hex("#628d98") }
func (t *themeSeaShells) BrightYellow() gothememe.Color { return gothememe.Hex("#fdd39f") }
func (t *themeSeaShells) BrightBlue() gothememe.Color   { return gothememe.Hex("#1bbcdd") }
func (t *themeSeaShells) BrightPurple() gothememe.Color { return gothememe.Hex("#bbe3ee") }
func (t *themeSeaShells) BrightCyan() gothememe.Color   { return gothememe.Hex("#87acb4") }
func (t *themeSeaShells) BrightWhite() gothememe.Color  { return gothememe.Hex("#fee4ce") }

// Code/Syntax highlighting colors
func (t *themeSeaShells) CodeBackground() gothememe.Color  { return gothememe.Hex("#09141b") }
func (t *themeSeaShells) CodeText() gothememe.Color        { return gothememe.Hex("#deb88d") }
func (t *themeSeaShells) CodeComment() gothememe.Color     { return gothememe.Hex("#434b53") }
func (t *themeSeaShells) CodeKeyword() gothememe.Color     { return gothememe.Hex("#68d4f1") }
func (t *themeSeaShells) CodeString() gothememe.Color      { return gothememe.Hex("#027c9b") }
func (t *themeSeaShells) CodeNumber() gothememe.Color      { return gothememe.Hex("#fca02f") }
func (t *themeSeaShells) CodeFunction() gothememe.Color    { return gothememe.Hex("#1e4950") }
func (t *themeSeaShells) CodeOperator() gothememe.Color    { return gothememe.Hex("#d15123") }
func (t *themeSeaShells) CodePunctuation() gothememe.Color { return gothememe.Hex("#deb88d") }
func (t *themeSeaShells) CodeVariable() gothememe.Color    { return gothememe.Hex("#50a3b5") }
func (t *themeSeaShells) CodeConstant() gothememe.Color    { return gothememe.Hex("#fdd39f") }
func (t *themeSeaShells) CodeType() gothememe.Color        { return gothememe.Hex("#87acb4") }
