// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSelenizedBlackInstance is the Selenized Black color theme singleton.
var themeSelenizedBlackInstance gothememe.Theme = &themeSelenizedBlack{}

// themeSelenizedBlack implements the Selenized Black theme.
type themeSelenizedBlack struct{}

func (t *themeSelenizedBlack) ID() string          { return "selenized_black" }
func (t *themeSelenizedBlack) DisplayName() string { return "Selenized Black" }
func (t *themeSelenizedBlack) Description() string { return "Selenized Black color theme" }
func (t *themeSelenizedBlack) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSelenizedBlack) License() string     { return "MIT" }
func (t *themeSelenizedBlack) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeSelenizedBlack) IsDark() bool { return true }

// Background colors
func (t *themeSelenizedBlack) Background() gothememe.Color          { return gothememe.Hex("#181818") }
func (t *themeSelenizedBlack) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#252525") }
func (t *themeSelenizedBlack) Surface() gothememe.Color             { return gothememe.Hex("#3b3b3b") }
func (t *themeSelenizedBlack) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#777777") }

// Text colors
func (t *themeSelenizedBlack) TextPrimary() gothememe.Color   { return gothememe.Hex("#b9b9b9") }
func (t *themeSelenizedBlack) TextSecondary() gothememe.Color { return gothememe.Hex("#b9b9b9") }
func (t *themeSelenizedBlack) TextMuted() gothememe.Color     { return gothememe.Hex("#777777") }
func (t *themeSelenizedBlack) TextInverted() gothememe.Color  { return gothememe.Hex("#181818") }

// Accent/Brand colors
func (t *themeSelenizedBlack) Accent() gothememe.Color          { return gothememe.Hex("#368aeb") }
func (t *themeSelenizedBlack) AccentSecondary() gothememe.Color { return gothememe.Hex("#eb6eb7") }
func (t *themeSelenizedBlack) Brand() gothememe.Color           { return gothememe.Hex("#368aeb") }

// Border colors
func (t *themeSelenizedBlack) Border() gothememe.Color       { return gothememe.Hex("#777777") }
func (t *themeSelenizedBlack) BorderSubtle() gothememe.Color { return gothememe.Hex("#252525") }
func (t *themeSelenizedBlack) BorderStrong() gothememe.Color { return gothememe.Hex("#b9b9b9") }

// Semantic colors
func (t *themeSelenizedBlack) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#70b433").WithAlpha(0.1),
		Border:     gothememe.Hex("#70b433").WithAlpha(0.3),
		Text:       gothememe.Hex("#70b433"),
	}
}

func (t *themeSelenizedBlack) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#dbb32d").WithAlpha(0.1),
		Border:     gothememe.Hex("#dbb32d").WithAlpha(0.3),
		Text:       gothememe.Hex("#dbb32d"),
	}
}

func (t *themeSelenizedBlack) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ed4a46").WithAlpha(0.1),
		Border:     gothememe.Hex("#ed4a46").WithAlpha(0.3),
		Text:       gothememe.Hex("#ed4a46"),
	}
}

func (t *themeSelenizedBlack) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#3fc5b7").WithAlpha(0.1),
		Border:     gothememe.Hex("#3fc5b7").WithAlpha(0.3),
		Text:       gothememe.Hex("#3fc5b7"),
	}
}

// ANSI colors
func (t *themeSelenizedBlack) Black() gothememe.Color        { return gothememe.Hex("#252525") }
func (t *themeSelenizedBlack) Red() gothememe.Color          { return gothememe.Hex("#ed4a46") }
func (t *themeSelenizedBlack) Green() gothememe.Color        { return gothememe.Hex("#70b433") }
func (t *themeSelenizedBlack) Yellow() gothememe.Color       { return gothememe.Hex("#dbb32d") }
func (t *themeSelenizedBlack) Blue() gothememe.Color         { return gothememe.Hex("#368aeb") }
func (t *themeSelenizedBlack) Purple() gothememe.Color       { return gothememe.Hex("#eb6eb7") }
func (t *themeSelenizedBlack) Cyan() gothememe.Color         { return gothememe.Hex("#3fc5b7") }
func (t *themeSelenizedBlack) White() gothememe.Color        { return gothememe.Hex("#b9b9b9") }
func (t *themeSelenizedBlack) BrightBlack() gothememe.Color  { return gothememe.Hex("#777777") }
func (t *themeSelenizedBlack) BrightRed() gothememe.Color    { return gothememe.Hex("#ff5e56") }
func (t *themeSelenizedBlack) BrightGreen() gothememe.Color  { return gothememe.Hex("#83c746") }
func (t *themeSelenizedBlack) BrightYellow() gothememe.Color { return gothememe.Hex("#efc541") }
func (t *themeSelenizedBlack) BrightBlue() gothememe.Color   { return gothememe.Hex("#4f9cfe") }
func (t *themeSelenizedBlack) BrightPurple() gothememe.Color { return gothememe.Hex("#ff81ca") }
func (t *themeSelenizedBlack) BrightCyan() gothememe.Color   { return gothememe.Hex("#56d8c9") }
func (t *themeSelenizedBlack) BrightWhite() gothememe.Color  { return gothememe.Hex("#dedede") }

// Code/Syntax highlighting colors
func (t *themeSelenizedBlack) CodeBackground() gothememe.Color  { return gothememe.Hex("#181818") }
func (t *themeSelenizedBlack) CodeText() gothememe.Color        { return gothememe.Hex("#b9b9b9") }
func (t *themeSelenizedBlack) CodeComment() gothememe.Color     { return gothememe.Hex("#777777") }
func (t *themeSelenizedBlack) CodeKeyword() gothememe.Color     { return gothememe.Hex("#eb6eb7") }
func (t *themeSelenizedBlack) CodeString() gothememe.Color      { return gothememe.Hex("#70b433") }
func (t *themeSelenizedBlack) CodeNumber() gothememe.Color      { return gothememe.Hex("#dbb32d") }
func (t *themeSelenizedBlack) CodeFunction() gothememe.Color    { return gothememe.Hex("#368aeb") }
func (t *themeSelenizedBlack) CodeOperator() gothememe.Color    { return gothememe.Hex("#ed4a46") }
func (t *themeSelenizedBlack) CodePunctuation() gothememe.Color { return gothememe.Hex("#b9b9b9") }
func (t *themeSelenizedBlack) CodeVariable() gothememe.Color    { return gothememe.Hex("#3fc5b7") }
func (t *themeSelenizedBlack) CodeConstant() gothememe.Color    { return gothememe.Hex("#efc541") }
func (t *themeSelenizedBlack) CodeType() gothememe.Color        { return gothememe.Hex("#56d8c9") }
