// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSugarplumInstance is the Sugarplum color theme singleton.
var themeSugarplumInstance gothememe.Theme = &themeSugarplum{}

// themeSugarplum implements the Sugarplum theme.
type themeSugarplum struct{}

func (t *themeSugarplum) ID() string          { return "sugarplum" }
func (t *themeSugarplum) DisplayName() string { return "Sugarplum" }
func (t *themeSugarplum) Description() string { return "Sugarplum color theme" }
func (t *themeSugarplum) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSugarplum) License() string     { return "MIT" }
func (t *themeSugarplum) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeSugarplum) IsDark() bool        { return true }

// Background colors
func (t *themeSugarplum) Background() gothememe.Color          { return gothememe.Hex("#111147") }
func (t *themeSugarplum) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#111147") }
func (t *themeSugarplum) Surface() gothememe.Color             { return gothememe.Hex("#5ca8dc") }
func (t *themeSugarplum) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#44447a") }

// Text colors
func (t *themeSugarplum) TextPrimary() gothememe.Color   { return gothememe.Hex("#db7ddd") }
func (t *themeSugarplum) TextSecondary() gothememe.Color { return gothememe.Hex("#a175d4") }
func (t *themeSugarplum) TextMuted() gothememe.Color     { return gothememe.Hex("#44447a") }
func (t *themeSugarplum) TextInverted() gothememe.Color  { return gothememe.Hex("#111147") }

// Accent/Brand colors
func (t *themeSugarplum) Accent() gothememe.Color          { return gothememe.Hex("#db7ddd") }
func (t *themeSugarplum) AccentSecondary() gothememe.Color { return gothememe.Hex("#d0beee") }
func (t *themeSugarplum) Brand() gothememe.Color           { return gothememe.Hex("#db7ddd") }

// Border colors
func (t *themeSugarplum) Border() gothememe.Color       { return gothememe.Hex("#44447a") }
func (t *themeSugarplum) BorderSubtle() gothememe.Color { return gothememe.Hex("#111147") }
func (t *themeSugarplum) BorderStrong() gothememe.Color { return gothememe.Hex("#a175d4") }

// Semantic colors
func (t *themeSugarplum) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#53b397").WithAlpha(0.1),
		Border:     gothememe.Hex("#53b397").WithAlpha(0.3),
		Text:       gothememe.Hex("#53b397"),
	}
}

func (t *themeSugarplum) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#249a84").WithAlpha(0.1),
		Border:     gothememe.Hex("#249a84").WithAlpha(0.3),
		Text:       gothememe.Hex("#249a84"),
	}
}

func (t *themeSugarplum) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5ca8dc").WithAlpha(0.1),
		Border:     gothememe.Hex("#5ca8dc").WithAlpha(0.3),
		Text:       gothememe.Hex("#5ca8dc"),
	}
}

func (t *themeSugarplum) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f9f3f9").WithAlpha(0.1),
		Border:     gothememe.Hex("#f9f3f9").WithAlpha(0.3),
		Text:       gothememe.Hex("#f9f3f9"),
	}
}

// ANSI colors
func (t *themeSugarplum) Black() gothememe.Color        { return gothememe.Hex("#111147") }
func (t *themeSugarplum) Red() gothememe.Color          { return gothememe.Hex("#5ca8dc") }
func (t *themeSugarplum) Green() gothememe.Color        { return gothememe.Hex("#53b397") }
func (t *themeSugarplum) Yellow() gothememe.Color       { return gothememe.Hex("#249a84") }
func (t *themeSugarplum) Blue() gothememe.Color         { return gothememe.Hex("#db7ddd") }
func (t *themeSugarplum) Purple() gothememe.Color       { return gothememe.Hex("#d0beee") }
func (t *themeSugarplum) Cyan() gothememe.Color         { return gothememe.Hex("#f9f3f9") }
func (t *themeSugarplum) White() gothememe.Color        { return gothememe.Hex("#a175d4") }
func (t *themeSugarplum) BrightBlack() gothememe.Color  { return gothememe.Hex("#44447a") }
func (t *themeSugarplum) BrightRed() gothememe.Color    { return gothememe.Hex("#5cb5dc") }
func (t *themeSugarplum) BrightGreen() gothememe.Color  { return gothememe.Hex("#52deb5") }
func (t *themeSugarplum) BrightYellow() gothememe.Color { return gothememe.Hex("#01f5c7") }
func (t *themeSugarplum) BrightBlue() gothememe.Color   { return gothememe.Hex("#fa5dfd") }
func (t *themeSugarplum) BrightPurple() gothememe.Color { return gothememe.Hex("#c6a5fd") }
func (t *themeSugarplum) BrightCyan() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeSugarplum) BrightWhite() gothememe.Color  { return gothememe.Hex("#b577fd") }

// Code/Syntax highlighting colors
func (t *themeSugarplum) CodeBackground() gothememe.Color  { return gothememe.Hex("#111147") }
func (t *themeSugarplum) CodeText() gothememe.Color        { return gothememe.Hex("#db7ddd") }
func (t *themeSugarplum) CodeComment() gothememe.Color     { return gothememe.Hex("#44447a") }
func (t *themeSugarplum) CodeKeyword() gothememe.Color     { return gothememe.Hex("#d0beee") }
func (t *themeSugarplum) CodeString() gothememe.Color      { return gothememe.Hex("#53b397") }
func (t *themeSugarplum) CodeNumber() gothememe.Color      { return gothememe.Hex("#249a84") }
func (t *themeSugarplum) CodeFunction() gothememe.Color    { return gothememe.Hex("#db7ddd") }
func (t *themeSugarplum) CodeOperator() gothememe.Color    { return gothememe.Hex("#5ca8dc") }
func (t *themeSugarplum) CodePunctuation() gothememe.Color { return gothememe.Hex("#db7ddd") }
func (t *themeSugarplum) CodeVariable() gothememe.Color    { return gothememe.Hex("#f9f3f9") }
func (t *themeSugarplum) CodeConstant() gothememe.Color    { return gothememe.Hex("#01f5c7") }
func (t *themeSugarplum) CodeType() gothememe.Color        { return gothememe.Hex("#ffffff") }
