// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeTeerbInstance is the Teerb color theme singleton.
var themeTeerbInstance gothememe.Theme = &themeTeerb{}

// themeTeerb implements the Teerb theme.
type themeTeerb struct{}

func (t *themeTeerb) ID() string          { return "teerb" }
func (t *themeTeerb) DisplayName() string { return "Teerb" }
func (t *themeTeerb) Description() string { return "Teerb color theme" }
func (t *themeTeerb) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeTeerb) License() string     { return "MIT" }
func (t *themeTeerb) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeTeerb) IsDark() bool        { return true }

// Background colors
func (t *themeTeerb) Background() gothememe.Color          { return gothememe.Hex("#262626") }
func (t *themeTeerb) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#1c1c1c") }
func (t *themeTeerb) Surface() gothememe.Color             { return gothememe.Hex("#4d4d4d") }
func (t *themeTeerb) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4f4f4f") }

// Text colors
func (t *themeTeerb) TextPrimary() gothememe.Color   { return gothememe.Hex("#d0d0d0") }
func (t *themeTeerb) TextSecondary() gothememe.Color { return gothememe.Hex("#d0d0d0") }
func (t *themeTeerb) TextMuted() gothememe.Color     { return gothememe.Hex("#4f4f4f") }
func (t *themeTeerb) TextInverted() gothememe.Color  { return gothememe.Hex("#262626") }

// Accent/Brand colors
func (t *themeTeerb) Accent() gothememe.Color          { return gothememe.Hex("#86aed6") }
func (t *themeTeerb) AccentSecondary() gothememe.Color { return gothememe.Hex("#d6aed6") }
func (t *themeTeerb) Brand() gothememe.Color           { return gothememe.Hex("#86aed6") }

// Border colors
func (t *themeTeerb) Border() gothememe.Color       { return gothememe.Hex("#4f4f4f") }
func (t *themeTeerb) BorderSubtle() gothememe.Color { return gothememe.Hex("#1c1c1c") }
func (t *themeTeerb) BorderStrong() gothememe.Color { return gothememe.Hex("#d0d0d0") }

// Semantic colors
func (t *themeTeerb) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#aed686").WithAlpha(0.1),
		Border:     gothememe.Hex("#aed686").WithAlpha(0.3),
		Text:       gothememe.Hex("#aed686"),
	}
}

func (t *themeTeerb) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d7af87").WithAlpha(0.1),
		Border:     gothememe.Hex("#d7af87").WithAlpha(0.3),
		Text:       gothememe.Hex("#d7af87"),
	}
}

func (t *themeTeerb) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d68686").WithAlpha(0.1),
		Border:     gothememe.Hex("#d68686").WithAlpha(0.3),
		Text:       gothememe.Hex("#d68686"),
	}
}

func (t *themeTeerb) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#8adbb4").WithAlpha(0.1),
		Border:     gothememe.Hex("#8adbb4").WithAlpha(0.3),
		Text:       gothememe.Hex("#8adbb4"),
	}
}

// ANSI colors
func (t *themeTeerb) Black() gothememe.Color        { return gothememe.Hex("#1c1c1c") }
func (t *themeTeerb) Red() gothememe.Color          { return gothememe.Hex("#d68686") }
func (t *themeTeerb) Green() gothememe.Color        { return gothememe.Hex("#aed686") }
func (t *themeTeerb) Yellow() gothememe.Color       { return gothememe.Hex("#d7af87") }
func (t *themeTeerb) Blue() gothememe.Color         { return gothememe.Hex("#86aed6") }
func (t *themeTeerb) Purple() gothememe.Color       { return gothememe.Hex("#d6aed6") }
func (t *themeTeerb) Cyan() gothememe.Color         { return gothememe.Hex("#8adbb4") }
func (t *themeTeerb) White() gothememe.Color        { return gothememe.Hex("#d0d0d0") }
func (t *themeTeerb) BrightBlack() gothememe.Color  { return gothememe.Hex("#4f4f4f") }
func (t *themeTeerb) BrightRed() gothememe.Color    { return gothememe.Hex("#d68686") }
func (t *themeTeerb) BrightGreen() gothememe.Color  { return gothememe.Hex("#aed686") }
func (t *themeTeerb) BrightYellow() gothememe.Color { return gothememe.Hex("#e4c9af") }
func (t *themeTeerb) BrightBlue() gothememe.Color   { return gothememe.Hex("#86aed6") }
func (t *themeTeerb) BrightPurple() gothememe.Color { return gothememe.Hex("#d6aed6") }
func (t *themeTeerb) BrightCyan() gothememe.Color   { return gothememe.Hex("#b1e7dd") }
func (t *themeTeerb) BrightWhite() gothememe.Color  { return gothememe.Hex("#efefef") }

// Code/Syntax highlighting colors
func (t *themeTeerb) CodeBackground() gothememe.Color  { return gothememe.Hex("#262626") }
func (t *themeTeerb) CodeText() gothememe.Color        { return gothememe.Hex("#d0d0d0") }
func (t *themeTeerb) CodeComment() gothememe.Color     { return gothememe.Hex("#4f4f4f") }
func (t *themeTeerb) CodeKeyword() gothememe.Color     { return gothememe.Hex("#d6aed6") }
func (t *themeTeerb) CodeString() gothememe.Color      { return gothememe.Hex("#aed686") }
func (t *themeTeerb) CodeNumber() gothememe.Color      { return gothememe.Hex("#d7af87") }
func (t *themeTeerb) CodeFunction() gothememe.Color    { return gothememe.Hex("#86aed6") }
func (t *themeTeerb) CodeOperator() gothememe.Color    { return gothememe.Hex("#d68686") }
func (t *themeTeerb) CodePunctuation() gothememe.Color { return gothememe.Hex("#d0d0d0") }
func (t *themeTeerb) CodeVariable() gothememe.Color    { return gothememe.Hex("#8adbb4") }
func (t *themeTeerb) CodeConstant() gothememe.Color    { return gothememe.Hex("#e4c9af") }
func (t *themeTeerb) CodeType() gothememe.Color        { return gothememe.Hex("#b1e7dd") }
