// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeTerafoxInstance is the Terafox color theme singleton.
var themeTerafoxInstance gothememe.Theme = &themeTerafox{}

// themeTerafox implements the Terafox theme.
type themeTerafox struct{}

func (t *themeTerafox) ID() string          { return "terafox" }
func (t *themeTerafox) DisplayName() string { return "Terafox" }
func (t *themeTerafox) Description() string { return "Terafox color theme" }
func (t *themeTerafox) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeTerafox) License() string     { return "MIT" }
func (t *themeTerafox) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeTerafox) IsDark() bool        { return true }

// Background colors
func (t *themeTerafox) Background() gothememe.Color          { return gothememe.Hex("#152528") }
func (t *themeTerafox) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#2f3239") }
func (t *themeTerafox) Surface() gothememe.Color             { return gothememe.Hex("#293e40") }
func (t *themeTerafox) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4e5157") }

// Text colors
func (t *themeTerafox) TextPrimary() gothememe.Color   { return gothememe.Hex("#e6eaea") }
func (t *themeTerafox) TextSecondary() gothememe.Color { return gothememe.Hex("#ebebeb") }
func (t *themeTerafox) TextMuted() gothememe.Color     { return gothememe.Hex("#4e5157") }
func (t *themeTerafox) TextInverted() gothememe.Color  { return gothememe.Hex("#152528") }

// Accent/Brand colors
func (t *themeTerafox) Accent() gothememe.Color          { return gothememe.Hex("#5a93aa") }
func (t *themeTerafox) AccentSecondary() gothememe.Color { return gothememe.Hex("#ad5c7c") }
func (t *themeTerafox) Brand() gothememe.Color           { return gothememe.Hex("#5a93aa") }

// Border colors
func (t *themeTerafox) Border() gothememe.Color       { return gothememe.Hex("#4e5157") }
func (t *themeTerafox) BorderSubtle() gothememe.Color { return gothememe.Hex("#2f3239") }
func (t *themeTerafox) BorderStrong() gothememe.Color { return gothememe.Hex("#ebebeb") }

// Semantic colors
func (t *themeTerafox) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#7aa4a1").WithAlpha(0.1),
		Border:     gothememe.Hex("#7aa4a1").WithAlpha(0.3),
		Text:       gothememe.Hex("#7aa4a1"),
	}
}

func (t *themeTerafox) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fda47f").WithAlpha(0.1),
		Border:     gothememe.Hex("#fda47f").WithAlpha(0.3),
		Text:       gothememe.Hex("#fda47f"),
	}
}

func (t *themeTerafox) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e85c51").WithAlpha(0.1),
		Border:     gothememe.Hex("#e85c51").WithAlpha(0.3),
		Text:       gothememe.Hex("#e85c51"),
	}
}

func (t *themeTerafox) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a1cdd8").WithAlpha(0.1),
		Border:     gothememe.Hex("#a1cdd8").WithAlpha(0.3),
		Text:       gothememe.Hex("#a1cdd8"),
	}
}

// ANSI colors
func (t *themeTerafox) Black() gothememe.Color        { return gothememe.Hex("#2f3239") }
func (t *themeTerafox) Red() gothememe.Color          { return gothememe.Hex("#e85c51") }
func (t *themeTerafox) Green() gothememe.Color        { return gothememe.Hex("#7aa4a1") }
func (t *themeTerafox) Yellow() gothememe.Color       { return gothememe.Hex("#fda47f") }
func (t *themeTerafox) Blue() gothememe.Color         { return gothememe.Hex("#5a93aa") }
func (t *themeTerafox) Purple() gothememe.Color       { return gothememe.Hex("#ad5c7c") }
func (t *themeTerafox) Cyan() gothememe.Color         { return gothememe.Hex("#a1cdd8") }
func (t *themeTerafox) White() gothememe.Color        { return gothememe.Hex("#ebebeb") }
func (t *themeTerafox) BrightBlack() gothememe.Color  { return gothememe.Hex("#4e5157") }
func (t *themeTerafox) BrightRed() gothememe.Color    { return gothememe.Hex("#eb746b") }
func (t *themeTerafox) BrightGreen() gothememe.Color  { return gothememe.Hex("#8eb2af") }
func (t *themeTerafox) BrightYellow() gothememe.Color { return gothememe.Hex("#fdb292") }
func (t *themeTerafox) BrightBlue() gothememe.Color   { return gothememe.Hex("#73a3b7") }
func (t *themeTerafox) BrightPurple() gothememe.Color { return gothememe.Hex("#b97490") }
func (t *themeTerafox) BrightCyan() gothememe.Color   { return gothememe.Hex("#afd4de") }
func (t *themeTerafox) BrightWhite() gothememe.Color  { return gothememe.Hex("#eeeeee") }

// Code/Syntax highlighting colors
func (t *themeTerafox) CodeBackground() gothememe.Color  { return gothememe.Hex("#152528") }
func (t *themeTerafox) CodeText() gothememe.Color        { return gothememe.Hex("#e6eaea") }
func (t *themeTerafox) CodeComment() gothememe.Color     { return gothememe.Hex("#4e5157") }
func (t *themeTerafox) CodeKeyword() gothememe.Color     { return gothememe.Hex("#ad5c7c") }
func (t *themeTerafox) CodeString() gothememe.Color      { return gothememe.Hex("#7aa4a1") }
func (t *themeTerafox) CodeNumber() gothememe.Color      { return gothememe.Hex("#fda47f") }
func (t *themeTerafox) CodeFunction() gothememe.Color    { return gothememe.Hex("#5a93aa") }
func (t *themeTerafox) CodeOperator() gothememe.Color    { return gothememe.Hex("#e85c51") }
func (t *themeTerafox) CodePunctuation() gothememe.Color { return gothememe.Hex("#e6eaea") }
func (t *themeTerafox) CodeVariable() gothememe.Color    { return gothememe.Hex("#a1cdd8") }
func (t *themeTerafox) CodeConstant() gothememe.Color    { return gothememe.Hex("#fdb292") }
func (t *themeTerafox) CodeType() gothememe.Color        { return gothememe.Hex("#afd4de") }
