// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeWilmersdorfInstance is the Wilmersdorf color theme singleton.
var themeWilmersdorfInstance gothememe.Theme = &themeWilmersdorf{}

// themeWilmersdorf implements the Wilmersdorf theme.
type themeWilmersdorf struct{}

func (t *themeWilmersdorf) ID() string          { return "wilmersdorf" }
func (t *themeWilmersdorf) DisplayName() string { return "Wilmersdorf" }
func (t *themeWilmersdorf) Description() string { return "Wilmersdorf color theme" }
func (t *themeWilmersdorf) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeWilmersdorf) License() string     { return "MIT" }
func (t *themeWilmersdorf) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeWilmersdorf) IsDark() bool { return true }

// Background colors
func (t *themeWilmersdorf) Background() gothememe.Color          { return gothememe.Hex("#282b33") }
func (t *themeWilmersdorf) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#34373e") }
func (t *themeWilmersdorf) Surface() gothememe.Color             { return gothememe.Hex("#1f2024") }
func (t *themeWilmersdorf) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#50545d") }

// Text colors
func (t *themeWilmersdorf) TextPrimary() gothememe.Color   { return gothememe.Hex("#c6c6c6") }
func (t *themeWilmersdorf) TextSecondary() gothememe.Color { return gothememe.Hex("#ababab") }
func (t *themeWilmersdorf) TextMuted() gothememe.Color     { return gothememe.Hex("#50545d") }
func (t *themeWilmersdorf) TextInverted() gothememe.Color  { return gothememe.Hex("#282b33") }

// Accent/Brand colors
func (t *themeWilmersdorf) Accent() gothememe.Color          { return gothememe.Hex("#a6c1e0") }
func (t *themeWilmersdorf) AccentSecondary() gothememe.Color { return gothememe.Hex("#e1c1ee") }
func (t *themeWilmersdorf) Brand() gothememe.Color           { return gothememe.Hex("#a6c1e0") }

// Border colors
func (t *themeWilmersdorf) Border() gothememe.Color       { return gothememe.Hex("#50545d") }
func (t *themeWilmersdorf) BorderSubtle() gothememe.Color { return gothememe.Hex("#34373e") }
func (t *themeWilmersdorf) BorderStrong() gothememe.Color { return gothememe.Hex("#ababab") }

// Semantic colors
func (t *themeWilmersdorf) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#7ebebd").WithAlpha(0.1),
		Border:     gothememe.Hex("#7ebebd").WithAlpha(0.3),
		Text:       gothememe.Hex("#7ebebd"),
	}
}

func (t *themeWilmersdorf) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cccccc").WithAlpha(0.1),
		Border:     gothememe.Hex("#cccccc").WithAlpha(0.3),
		Text:       gothememe.Hex("#cccccc"),
	}
}

func (t *themeWilmersdorf) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e06383").WithAlpha(0.1),
		Border:     gothememe.Hex("#e06383").WithAlpha(0.3),
		Text:       gothememe.Hex("#e06383"),
	}
}

func (t *themeWilmersdorf) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5b94ab").WithAlpha(0.1),
		Border:     gothememe.Hex("#5b94ab").WithAlpha(0.3),
		Text:       gothememe.Hex("#5b94ab"),
	}
}

// ANSI colors
func (t *themeWilmersdorf) Black() gothememe.Color        { return gothememe.Hex("#34373e") }
func (t *themeWilmersdorf) Red() gothememe.Color          { return gothememe.Hex("#e06383") }
func (t *themeWilmersdorf) Green() gothememe.Color        { return gothememe.Hex("#7ebebd") }
func (t *themeWilmersdorf) Yellow() gothememe.Color       { return gothememe.Hex("#cccccc") }
func (t *themeWilmersdorf) Blue() gothememe.Color         { return gothememe.Hex("#a6c1e0") }
func (t *themeWilmersdorf) Purple() gothememe.Color       { return gothememe.Hex("#e1c1ee") }
func (t *themeWilmersdorf) Cyan() gothememe.Color         { return gothememe.Hex("#5b94ab") }
func (t *themeWilmersdorf) White() gothememe.Color        { return gothememe.Hex("#ababab") }
func (t *themeWilmersdorf) BrightBlack() gothememe.Color  { return gothememe.Hex("#50545d") }
func (t *themeWilmersdorf) BrightRed() gothememe.Color    { return gothememe.Hex("#fa7193") }
func (t *themeWilmersdorf) BrightGreen() gothememe.Color  { return gothememe.Hex("#8fd7d6") }
func (t *themeWilmersdorf) BrightYellow() gothememe.Color { return gothememe.Hex("#d1dfff") }
func (t *themeWilmersdorf) BrightBlue() gothememe.Color   { return gothememe.Hex("#b2cff0") }
func (t *themeWilmersdorf) BrightPurple() gothememe.Color { return gothememe.Hex("#efccfd") }
func (t *themeWilmersdorf) BrightCyan() gothememe.Color   { return gothememe.Hex("#69abc5") }
func (t *themeWilmersdorf) BrightWhite() gothememe.Color  { return gothememe.Hex("#d3d3d3") }

// Code/Syntax highlighting colors
func (t *themeWilmersdorf) CodeBackground() gothememe.Color  { return gothememe.Hex("#282b33") }
func (t *themeWilmersdorf) CodeText() gothememe.Color        { return gothememe.Hex("#c6c6c6") }
func (t *themeWilmersdorf) CodeComment() gothememe.Color     { return gothememe.Hex("#50545d") }
func (t *themeWilmersdorf) CodeKeyword() gothememe.Color     { return gothememe.Hex("#e1c1ee") }
func (t *themeWilmersdorf) CodeString() gothememe.Color      { return gothememe.Hex("#7ebebd") }
func (t *themeWilmersdorf) CodeNumber() gothememe.Color      { return gothememe.Hex("#cccccc") }
func (t *themeWilmersdorf) CodeFunction() gothememe.Color    { return gothememe.Hex("#a6c1e0") }
func (t *themeWilmersdorf) CodeOperator() gothememe.Color    { return gothememe.Hex("#e06383") }
func (t *themeWilmersdorf) CodePunctuation() gothememe.Color { return gothememe.Hex("#c6c6c6") }
func (t *themeWilmersdorf) CodeVariable() gothememe.Color    { return gothememe.Hex("#5b94ab") }
func (t *themeWilmersdorf) CodeConstant() gothememe.Color    { return gothememe.Hex("#d1dfff") }
func (t *themeWilmersdorf) CodeType() gothememe.Color        { return gothememe.Hex("#69abc5") }
