// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themePencilDarkInstance is the Pencil Dark color theme singleton.
var themePencilDarkInstance gothememe.Theme = &themePencilDark{}

// themePencilDark implements the Pencil Dark theme.
type themePencilDark struct{}

func (t *themePencilDark) ID() string          { return "pencil_dark" }
func (t *themePencilDark) DisplayName() string { return "Pencil Dark" }
func (t *themePencilDark) Description() string { return "Pencil Dark color theme" }
func (t *themePencilDark) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themePencilDark) License() string     { return "MIT" }
func (t *themePencilDark) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themePencilDark) IsDark() bool        { return true }

// Background colors
func (t *themePencilDark) Background() gothememe.Color          { return gothememe.Hex("#212121") }
func (t *themePencilDark) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#212121") }
func (t *themePencilDark) Surface() gothememe.Color             { return gothememe.Hex("#b6d6fd") }
func (t *themePencilDark) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4f4f4f") }

// Text colors
func (t *themePencilDark) TextPrimary() gothememe.Color   { return gothememe.Hex("#f1f1f1") }
func (t *themePencilDark) TextSecondary() gothememe.Color { return gothememe.Hex("#d9d9d9") }
func (t *themePencilDark) TextMuted() gothememe.Color     { return gothememe.Hex("#4f4f4f") }
func (t *themePencilDark) TextInverted() gothememe.Color  { return gothememe.Hex("#212121") }

// Accent/Brand colors
func (t *themePencilDark) Accent() gothememe.Color          { return gothememe.Hex("#008ec4") }
func (t *themePencilDark) AccentSecondary() gothememe.Color { return gothememe.Hex("#5f4986") }
func (t *themePencilDark) Brand() gothememe.Color           { return gothememe.Hex("#008ec4") }

// Border colors
func (t *themePencilDark) Border() gothememe.Color       { return gothememe.Hex("#4f4f4f") }
func (t *themePencilDark) BorderSubtle() gothememe.Color { return gothememe.Hex("#212121") }
func (t *themePencilDark) BorderStrong() gothememe.Color { return gothememe.Hex("#d9d9d9") }

// Semantic colors
func (t *themePencilDark) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#10a778").WithAlpha(0.1),
		Border:     gothememe.Hex("#10a778").WithAlpha(0.3),
		Text:       gothememe.Hex("#10a778"),
	}
}

func (t *themePencilDark) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a89c14").WithAlpha(0.1),
		Border:     gothememe.Hex("#a89c14").WithAlpha(0.3),
		Text:       gothememe.Hex("#a89c14"),
	}
}

func (t *themePencilDark) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c30771").WithAlpha(0.1),
		Border:     gothememe.Hex("#c30771").WithAlpha(0.3),
		Text:       gothememe.Hex("#c30771"),
	}
}

func (t *themePencilDark) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#20a5ba").WithAlpha(0.1),
		Border:     gothememe.Hex("#20a5ba").WithAlpha(0.3),
		Text:       gothememe.Hex("#20a5ba"),
	}
}

// ANSI colors
func (t *themePencilDark) Black() gothememe.Color        { return gothememe.Hex("#212121") }
func (t *themePencilDark) Red() gothememe.Color          { return gothememe.Hex("#c30771") }
func (t *themePencilDark) Green() gothememe.Color        { return gothememe.Hex("#10a778") }
func (t *themePencilDark) Yellow() gothememe.Color       { return gothememe.Hex("#a89c14") }
func (t *themePencilDark) Blue() gothememe.Color         { return gothememe.Hex("#008ec4") }
func (t *themePencilDark) Purple() gothememe.Color       { return gothememe.Hex("#5f4986") }
func (t *themePencilDark) Cyan() gothememe.Color         { return gothememe.Hex("#20a5ba") }
func (t *themePencilDark) White() gothememe.Color        { return gothememe.Hex("#d9d9d9") }
func (t *themePencilDark) BrightBlack() gothememe.Color  { return gothememe.Hex("#4f4f4f") }
func (t *themePencilDark) BrightRed() gothememe.Color    { return gothememe.Hex("#fb007a") }
func (t *themePencilDark) BrightGreen() gothememe.Color  { return gothememe.Hex("#5fd7af") }
func (t *themePencilDark) BrightYellow() gothememe.Color { return gothememe.Hex("#f3e430") }
func (t *themePencilDark) BrightBlue() gothememe.Color   { return gothememe.Hex("#20bbfc") }
func (t *themePencilDark) BrightPurple() gothememe.Color { return gothememe.Hex("#6855de") }
func (t *themePencilDark) BrightCyan() gothememe.Color   { return gothememe.Hex("#4fb8cc") }
func (t *themePencilDark) BrightWhite() gothememe.Color  { return gothememe.Hex("#f1f1f1") }

// Code/Syntax highlighting colors
func (t *themePencilDark) CodeBackground() gothememe.Color  { return gothememe.Hex("#212121") }
func (t *themePencilDark) CodeText() gothememe.Color        { return gothememe.Hex("#f1f1f1") }
func (t *themePencilDark) CodeComment() gothememe.Color     { return gothememe.Hex("#4f4f4f") }
func (t *themePencilDark) CodeKeyword() gothememe.Color     { return gothememe.Hex("#5f4986") }
func (t *themePencilDark) CodeString() gothememe.Color      { return gothememe.Hex("#10a778") }
func (t *themePencilDark) CodeNumber() gothememe.Color      { return gothememe.Hex("#a89c14") }
func (t *themePencilDark) CodeFunction() gothememe.Color    { return gothememe.Hex("#008ec4") }
func (t *themePencilDark) CodeOperator() gothememe.Color    { return gothememe.Hex("#c30771") }
func (t *themePencilDark) CodePunctuation() gothememe.Color { return gothememe.Hex("#f1f1f1") }
func (t *themePencilDark) CodeVariable() gothememe.Color    { return gothememe.Hex("#20a5ba") }
func (t *themePencilDark) CodeConstant() gothememe.Color    { return gothememe.Hex("#f3e430") }
func (t *themePencilDark) CodeType() gothememe.Color        { return gothememe.Hex("#4fb8cc") }
