// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSynthwaveInstance is the Synthwave color theme singleton.
var themeSynthwaveInstance gothememe.Theme = &themeSynthwave{}

// themeSynthwave implements the Synthwave theme.
type themeSynthwave struct{}

func (t *themeSynthwave) ID() string          { return "synthwave" }
func (t *themeSynthwave) DisplayName() string { return "Synthwave" }
func (t *themeSynthwave) Description() string { return "Synthwave color theme" }
func (t *themeSynthwave) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSynthwave) License() string     { return "MIT" }
func (t *themeSynthwave) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeSynthwave) IsDark() bool        { return true }

// Background colors
func (t *themeSynthwave) Background() gothememe.Color          { return gothememe.Hex("#000000") }
func (t *themeSynthwave) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeSynthwave) Surface() gothememe.Color             { return gothememe.Hex("#19cde6") }
func (t *themeSynthwave) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#7f7094") }

// Text colors
func (t *themeSynthwave) TextPrimary() gothememe.Color   { return gothememe.Hex("#dad9c7") }
func (t *themeSynthwave) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeSynthwave) TextMuted() gothememe.Color     { return gothememe.Hex("#7f7094") }
func (t *themeSynthwave) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themeSynthwave) Accent() gothememe.Color          { return gothememe.Hex("#2186ec") }
func (t *themeSynthwave) AccentSecondary() gothememe.Color { return gothememe.Hex("#f85a21") }
func (t *themeSynthwave) Brand() gothememe.Color           { return gothememe.Hex("#2186ec") }

// Border colors
func (t *themeSynthwave) Border() gothememe.Color       { return gothememe.Hex("#7f7094") }
func (t *themeSynthwave) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeSynthwave) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeSynthwave) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1ebb2b").WithAlpha(0.1),
		Border:     gothememe.Hex("#1ebb2b").WithAlpha(0.3),
		Text:       gothememe.Hex("#1ebb2b"),
	}
}

func (t *themeSynthwave) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fdf834").WithAlpha(0.1),
		Border:     gothememe.Hex("#fdf834").WithAlpha(0.3),
		Text:       gothememe.Hex("#fdf834"),
	}
}

func (t *themeSynthwave) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f6188f").WithAlpha(0.1),
		Border:     gothememe.Hex("#f6188f").WithAlpha(0.3),
		Text:       gothememe.Hex("#f6188f"),
	}
}

func (t *themeSynthwave) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#12c3e2").WithAlpha(0.1),
		Border:     gothememe.Hex("#12c3e2").WithAlpha(0.3),
		Text:       gothememe.Hex("#12c3e2"),
	}
}

// ANSI colors
func (t *themeSynthwave) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeSynthwave) Red() gothememe.Color          { return gothememe.Hex("#f6188f") }
func (t *themeSynthwave) Green() gothememe.Color        { return gothememe.Hex("#1ebb2b") }
func (t *themeSynthwave) Yellow() gothememe.Color       { return gothememe.Hex("#fdf834") }
func (t *themeSynthwave) Blue() gothememe.Color         { return gothememe.Hex("#2186ec") }
func (t *themeSynthwave) Purple() gothememe.Color       { return gothememe.Hex("#f85a21") }
func (t *themeSynthwave) Cyan() gothememe.Color         { return gothememe.Hex("#12c3e2") }
func (t *themeSynthwave) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeSynthwave) BrightBlack() gothememe.Color  { return gothememe.Hex("#7f7094") }
func (t *themeSynthwave) BrightRed() gothememe.Color    { return gothememe.Hex("#f841a0") }
func (t *themeSynthwave) BrightGreen() gothememe.Color  { return gothememe.Hex("#25c141") }
func (t *themeSynthwave) BrightYellow() gothememe.Color { return gothememe.Hex("#fdf454") }
func (t *themeSynthwave) BrightBlue() gothememe.Color   { return gothememe.Hex("#2f9ded") }
func (t *themeSynthwave) BrightPurple() gothememe.Color { return gothememe.Hex("#f97137") }
func (t *themeSynthwave) BrightCyan() gothememe.Color   { return gothememe.Hex("#19cde6") }
func (t *themeSynthwave) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeSynthwave) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themeSynthwave) CodeText() gothememe.Color        { return gothememe.Hex("#dad9c7") }
func (t *themeSynthwave) CodeComment() gothememe.Color     { return gothememe.Hex("#7f7094") }
func (t *themeSynthwave) CodeKeyword() gothememe.Color     { return gothememe.Hex("#f85a21") }
func (t *themeSynthwave) CodeString() gothememe.Color      { return gothememe.Hex("#1ebb2b") }
func (t *themeSynthwave) CodeNumber() gothememe.Color      { return gothememe.Hex("#fdf834") }
func (t *themeSynthwave) CodeFunction() gothememe.Color    { return gothememe.Hex("#2186ec") }
func (t *themeSynthwave) CodeOperator() gothememe.Color    { return gothememe.Hex("#f6188f") }
func (t *themeSynthwave) CodePunctuation() gothememe.Color { return gothememe.Hex("#dad9c7") }
func (t *themeSynthwave) CodeVariable() gothememe.Color    { return gothememe.Hex("#12c3e2") }
func (t *themeSynthwave) CodeConstant() gothememe.Color    { return gothememe.Hex("#fdf454") }
func (t *themeSynthwave) CodeType() gothememe.Color        { return gothememe.Hex("#19cde6") }
