// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themePeppermintInstance is the Peppermint color theme singleton.
var themePeppermintInstance gothememe.Theme = &themePeppermint{}

// themePeppermint implements the Peppermint theme.
type themePeppermint struct{}

func (t *themePeppermint) ID() string          { return "peppermint" }
func (t *themePeppermint) DisplayName() string { return "Peppermint" }
func (t *themePeppermint) Description() string { return "Peppermint color theme" }
func (t *themePeppermint) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themePeppermint) License() string     { return "MIT" }
func (t *themePeppermint) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themePeppermint) IsDark() bool        { return true }

// Background colors
func (t *themePeppermint) Background() gothememe.Color          { return gothememe.Hex("#000000") }
func (t *themePeppermint) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#353535") }
func (t *themePeppermint) Surface() gothememe.Color             { return gothememe.Hex("#e6e6e6") }
func (t *themePeppermint) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#535353") }

// Text colors
func (t *themePeppermint) TextPrimary() gothememe.Color   { return gothememe.Hex("#c8c8c8") }
func (t *themePeppermint) TextSecondary() gothememe.Color { return gothememe.Hex("#b4b4b4") }
func (t *themePeppermint) TextMuted() gothememe.Color     { return gothememe.Hex("#535353") }
func (t *themePeppermint) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themePeppermint) Accent() gothememe.Color          { return gothememe.Hex("#449fd0") }
func (t *themePeppermint) AccentSecondary() gothememe.Color { return gothememe.Hex("#da62dc") }
func (t *themePeppermint) Brand() gothememe.Color           { return gothememe.Hex("#449fd0") }

// Border colors
func (t *themePeppermint) Border() gothememe.Color       { return gothememe.Hex("#535353") }
func (t *themePeppermint) BorderSubtle() gothememe.Color { return gothememe.Hex("#353535") }
func (t *themePeppermint) BorderStrong() gothememe.Color { return gothememe.Hex("#b4b4b4") }

// Semantic colors
func (t *themePeppermint) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#89d287").WithAlpha(0.1),
		Border:     gothememe.Hex("#89d287").WithAlpha(0.3),
		Text:       gothememe.Hex("#89d287"),
	}
}

func (t *themePeppermint) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#dab853").WithAlpha(0.1),
		Border:     gothememe.Hex("#dab853").WithAlpha(0.3),
		Text:       gothememe.Hex("#dab853"),
	}
}

func (t *themePeppermint) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e74669").WithAlpha(0.1),
		Border:     gothememe.Hex("#e74669").WithAlpha(0.3),
		Text:       gothememe.Hex("#e74669"),
	}
}

func (t *themePeppermint) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#65aaaf").WithAlpha(0.1),
		Border:     gothememe.Hex("#65aaaf").WithAlpha(0.3),
		Text:       gothememe.Hex("#65aaaf"),
	}
}

// ANSI colors
func (t *themePeppermint) Black() gothememe.Color        { return gothememe.Hex("#353535") }
func (t *themePeppermint) Red() gothememe.Color          { return gothememe.Hex("#e74669") }
func (t *themePeppermint) Green() gothememe.Color        { return gothememe.Hex("#89d287") }
func (t *themePeppermint) Yellow() gothememe.Color       { return gothememe.Hex("#dab853") }
func (t *themePeppermint) Blue() gothememe.Color         { return gothememe.Hex("#449fd0") }
func (t *themePeppermint) Purple() gothememe.Color       { return gothememe.Hex("#da62dc") }
func (t *themePeppermint) Cyan() gothememe.Color         { return gothememe.Hex("#65aaaf") }
func (t *themePeppermint) White() gothememe.Color        { return gothememe.Hex("#b4b4b4") }
func (t *themePeppermint) BrightBlack() gothememe.Color  { return gothememe.Hex("#535353") }
func (t *themePeppermint) BrightRed() gothememe.Color    { return gothememe.Hex("#e4859b") }
func (t *themePeppermint) BrightGreen() gothememe.Color  { return gothememe.Hex("#a3cca2") }
func (t *themePeppermint) BrightYellow() gothememe.Color { return gothememe.Hex("#e1e487") }
func (t *themePeppermint) BrightBlue() gothememe.Color   { return gothememe.Hex("#6fbce2") }
func (t *themePeppermint) BrightPurple() gothememe.Color { return gothememe.Hex("#e586e7") }
func (t *themePeppermint) BrightCyan() gothememe.Color   { return gothememe.Hex("#96dcdb") }
func (t *themePeppermint) BrightWhite() gothememe.Color  { return gothememe.Hex("#dfdfdf") }

// Code/Syntax highlighting colors
func (t *themePeppermint) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themePeppermint) CodeText() gothememe.Color        { return gothememe.Hex("#c8c8c8") }
func (t *themePeppermint) CodeComment() gothememe.Color     { return gothememe.Hex("#535353") }
func (t *themePeppermint) CodeKeyword() gothememe.Color     { return gothememe.Hex("#da62dc") }
func (t *themePeppermint) CodeString() gothememe.Color      { return gothememe.Hex("#89d287") }
func (t *themePeppermint) CodeNumber() gothememe.Color      { return gothememe.Hex("#dab853") }
func (t *themePeppermint) CodeFunction() gothememe.Color    { return gothememe.Hex("#449fd0") }
func (t *themePeppermint) CodeOperator() gothememe.Color    { return gothememe.Hex("#e74669") }
func (t *themePeppermint) CodePunctuation() gothememe.Color { return gothememe.Hex("#c8c8c8") }
func (t *themePeppermint) CodeVariable() gothememe.Color    { return gothememe.Hex("#65aaaf") }
func (t *themePeppermint) CodeConstant() gothememe.Color    { return gothememe.Hex("#e1e487") }
func (t *themePeppermint) CodeType() gothememe.Color        { return gothememe.Hex("#96dcdb") }
