// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeLaterThisEveningInstance is the Later This Evening color theme singleton.
var themeLaterThisEveningInstance gothememe.Theme = &themeLaterThisEvening{}

// themeLaterThisEvening implements the Later This Evening theme.
type themeLaterThisEvening struct{}

func (t *themeLaterThisEvening) ID() string          { return "later_this_evening" }
func (t *themeLaterThisEvening) DisplayName() string { return "Later This Evening" }
func (t *themeLaterThisEvening) Description() string { return "Later This Evening color theme" }
func (t *themeLaterThisEvening) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeLaterThisEvening) License() string     { return "MIT" }
func (t *themeLaterThisEvening) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeLaterThisEvening) IsDark() bool { return true }

// Background colors
func (t *themeLaterThisEvening) Background() gothememe.Color { return gothememe.Hex("#222222") }
func (t *themeLaterThisEvening) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#2b2b2b")
}
func (t *themeLaterThisEvening) Surface() gothememe.Color          { return gothememe.Hex("#424242") }
func (t *themeLaterThisEvening) SurfaceSecondary() gothememe.Color { return gothememe.Hex("#525454") }

// Text colors
func (t *themeLaterThisEvening) TextPrimary() gothememe.Color   { return gothememe.Hex("#959595") }
func (t *themeLaterThisEvening) TextSecondary() gothememe.Color { return gothememe.Hex("#494a4a") }
func (t *themeLaterThisEvening) TextMuted() gothememe.Color     { return gothememe.Hex("#525454") }
func (t *themeLaterThisEvening) TextInverted() gothememe.Color  { return gothememe.Hex("#222222") }

// Accent/Brand colors
func (t *themeLaterThisEvening) Accent() gothememe.Color          { return gothememe.Hex("#a0bad6") }
func (t *themeLaterThisEvening) AccentSecondary() gothememe.Color { return gothememe.Hex("#c092d6") }
func (t *themeLaterThisEvening) Brand() gothememe.Color           { return gothememe.Hex("#a0bad6") }

// Border colors
func (t *themeLaterThisEvening) Border() gothememe.Color       { return gothememe.Hex("#525454") }
func (t *themeLaterThisEvening) BorderSubtle() gothememe.Color { return gothememe.Hex("#2b2b2b") }
func (t *themeLaterThisEvening) BorderStrong() gothememe.Color { return gothememe.Hex("#494a4a") }

// Semantic colors
func (t *themeLaterThisEvening) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#afba67").WithAlpha(0.1),
		Border:     gothememe.Hex("#afba67").WithAlpha(0.3),
		Text:       gothememe.Hex("#afba67"),
	}
}

func (t *themeLaterThisEvening) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e5d289").WithAlpha(0.1),
		Border:     gothememe.Hex("#e5d289").WithAlpha(0.3),
		Text:       gothememe.Hex("#e5d289"),
	}
}

func (t *themeLaterThisEvening) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d45a60").WithAlpha(0.1),
		Border:     gothememe.Hex("#d45a60").WithAlpha(0.3),
		Text:       gothememe.Hex("#d45a60"),
	}
}

func (t *themeLaterThisEvening) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#91bfb7").WithAlpha(0.1),
		Border:     gothememe.Hex("#91bfb7").WithAlpha(0.3),
		Text:       gothememe.Hex("#91bfb7"),
	}
}

// ANSI colors
func (t *themeLaterThisEvening) Black() gothememe.Color        { return gothememe.Hex("#2b2b2b") }
func (t *themeLaterThisEvening) Red() gothememe.Color          { return gothememe.Hex("#d45a60") }
func (t *themeLaterThisEvening) Green() gothememe.Color        { return gothememe.Hex("#afba67") }
func (t *themeLaterThisEvening) Yellow() gothememe.Color       { return gothememe.Hex("#e5d289") }
func (t *themeLaterThisEvening) Blue() gothememe.Color         { return gothememe.Hex("#a0bad6") }
func (t *themeLaterThisEvening) Purple() gothememe.Color       { return gothememe.Hex("#c092d6") }
func (t *themeLaterThisEvening) Cyan() gothememe.Color         { return gothememe.Hex("#91bfb7") }
func (t *themeLaterThisEvening) White() gothememe.Color        { return gothememe.Hex("#494a4a") }
func (t *themeLaterThisEvening) BrightBlack() gothememe.Color  { return gothememe.Hex("#525454") }
func (t *themeLaterThisEvening) BrightRed() gothememe.Color    { return gothememe.Hex("#d3232f") }
func (t *themeLaterThisEvening) BrightGreen() gothememe.Color  { return gothememe.Hex("#aabb39") }
func (t *themeLaterThisEvening) BrightYellow() gothememe.Color { return gothememe.Hex("#e5be39") }
func (t *themeLaterThisEvening) BrightBlue() gothememe.Color   { return gothememe.Hex("#6699d6") }
func (t *themeLaterThisEvening) BrightPurple() gothememe.Color { return gothememe.Hex("#ab53d6") }
func (t *themeLaterThisEvening) BrightCyan() gothememe.Color   { return gothememe.Hex("#5fc0ae") }
func (t *themeLaterThisEvening) BrightWhite() gothememe.Color  { return gothememe.Hex("#c1c2c2") }

// Code/Syntax highlighting colors
func (t *themeLaterThisEvening) CodeBackground() gothememe.Color  { return gothememe.Hex("#222222") }
func (t *themeLaterThisEvening) CodeText() gothememe.Color        { return gothememe.Hex("#959595") }
func (t *themeLaterThisEvening) CodeComment() gothememe.Color     { return gothememe.Hex("#525454") }
func (t *themeLaterThisEvening) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c092d6") }
func (t *themeLaterThisEvening) CodeString() gothememe.Color      { return gothememe.Hex("#afba67") }
func (t *themeLaterThisEvening) CodeNumber() gothememe.Color      { return gothememe.Hex("#e5d289") }
func (t *themeLaterThisEvening) CodeFunction() gothememe.Color    { return gothememe.Hex("#a0bad6") }
func (t *themeLaterThisEvening) CodeOperator() gothememe.Color    { return gothememe.Hex("#d45a60") }
func (t *themeLaterThisEvening) CodePunctuation() gothememe.Color { return gothememe.Hex("#959595") }
func (t *themeLaterThisEvening) CodeVariable() gothememe.Color    { return gothememe.Hex("#91bfb7") }
func (t *themeLaterThisEvening) CodeConstant() gothememe.Color    { return gothememe.Hex("#e5be39") }
func (t *themeLaterThisEvening) CodeType() gothememe.Color        { return gothememe.Hex("#5fc0ae") }
