// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeCyberdyneInstance is the Cyberdyne color theme singleton.
var themeCyberdyneInstance gothememe.Theme = &themeCyberdyne{}

// themeCyberdyne implements the Cyberdyne theme.
type themeCyberdyne struct{}

func (t *themeCyberdyne) ID() string          { return "cyberdyne" }
func (t *themeCyberdyne) DisplayName() string { return "Cyberdyne" }
func (t *themeCyberdyne) Description() string { return "Cyberdyne color theme" }
func (t *themeCyberdyne) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeCyberdyne) License() string     { return "MIT" }
func (t *themeCyberdyne) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeCyberdyne) IsDark() bool        { return true }

// Background colors
func (t *themeCyberdyne) Background() gothememe.Color          { return gothememe.Hex("#151144") }
func (t *themeCyberdyne) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#080808") }
func (t *themeCyberdyne) Surface() gothememe.Color             { return gothememe.Hex("#454d96") }
func (t *themeCyberdyne) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#484848") }

// Text colors
func (t *themeCyberdyne) TextPrimary() gothememe.Color   { return gothememe.Hex("#00ff92") }
func (t *themeCyberdyne) TextSecondary() gothememe.Color { return gothememe.Hex("#f1f1f1") }
func (t *themeCyberdyne) TextMuted() gothememe.Color     { return gothememe.Hex("#484848") }
func (t *themeCyberdyne) TextInverted() gothememe.Color  { return gothememe.Hex("#151144") }

// Accent/Brand colors
func (t *themeCyberdyne) Accent() gothememe.Color          { return gothememe.Hex("#0071cf") }
func (t *themeCyberdyne) AccentSecondary() gothememe.Color { return gothememe.Hex("#ff90fe") }
func (t *themeCyberdyne) Brand() gothememe.Color           { return gothememe.Hex("#0071cf") }

// Border colors
func (t *themeCyberdyne) Border() gothememe.Color       { return gothememe.Hex("#484848") }
func (t *themeCyberdyne) BorderSubtle() gothememe.Color { return gothememe.Hex("#080808") }
func (t *themeCyberdyne) BorderStrong() gothememe.Color { return gothememe.Hex("#f1f1f1") }

// Semantic colors
func (t *themeCyberdyne) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00c172").WithAlpha(0.1),
		Border:     gothememe.Hex("#00c172").WithAlpha(0.3),
		Text:       gothememe.Hex("#00c172"),
	}
}

func (t *themeCyberdyne) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d2a700").WithAlpha(0.1),
		Border:     gothememe.Hex("#d2a700").WithAlpha(0.3),
		Text:       gothememe.Hex("#d2a700"),
	}
}

func (t *themeCyberdyne) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff8373").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff8373").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff8373"),
	}
}

func (t *themeCyberdyne) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#6bffdd").WithAlpha(0.1),
		Border:     gothememe.Hex("#6bffdd").WithAlpha(0.3),
		Text:       gothememe.Hex("#6bffdd"),
	}
}

// ANSI colors
func (t *themeCyberdyne) Black() gothememe.Color        { return gothememe.Hex("#080808") }
func (t *themeCyberdyne) Red() gothememe.Color          { return gothememe.Hex("#ff8373") }
func (t *themeCyberdyne) Green() gothememe.Color        { return gothememe.Hex("#00c172") }
func (t *themeCyberdyne) Yellow() gothememe.Color       { return gothememe.Hex("#d2a700") }
func (t *themeCyberdyne) Blue() gothememe.Color         { return gothememe.Hex("#0071cf") }
func (t *themeCyberdyne) Purple() gothememe.Color       { return gothememe.Hex("#ff90fe") }
func (t *themeCyberdyne) Cyan() gothememe.Color         { return gothememe.Hex("#6bffdd") }
func (t *themeCyberdyne) White() gothememe.Color        { return gothememe.Hex("#f1f1f1") }
func (t *themeCyberdyne) BrightBlack() gothememe.Color  { return gothememe.Hex("#484848") }
func (t *themeCyberdyne) BrightRed() gothememe.Color    { return gothememe.Hex("#ffc4be") }
func (t *themeCyberdyne) BrightGreen() gothememe.Color  { return gothememe.Hex("#d6fcba") }
func (t *themeCyberdyne) BrightYellow() gothememe.Color { return gothememe.Hex("#fffed5") }
func (t *themeCyberdyne) BrightBlue() gothememe.Color   { return gothememe.Hex("#c2e3ff") }
func (t *themeCyberdyne) BrightPurple() gothememe.Color { return gothememe.Hex("#ffb2fe") }
func (t *themeCyberdyne) BrightCyan() gothememe.Color   { return gothememe.Hex("#e6e7fe") }
func (t *themeCyberdyne) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeCyberdyne) CodeBackground() gothememe.Color  { return gothememe.Hex("#151144") }
func (t *themeCyberdyne) CodeText() gothememe.Color        { return gothememe.Hex("#00ff92") }
func (t *themeCyberdyne) CodeComment() gothememe.Color     { return gothememe.Hex("#484848") }
func (t *themeCyberdyne) CodeKeyword() gothememe.Color     { return gothememe.Hex("#ff90fe") }
func (t *themeCyberdyne) CodeString() gothememe.Color      { return gothememe.Hex("#00c172") }
func (t *themeCyberdyne) CodeNumber() gothememe.Color      { return gothememe.Hex("#d2a700") }
func (t *themeCyberdyne) CodeFunction() gothememe.Color    { return gothememe.Hex("#0071cf") }
func (t *themeCyberdyne) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff8373") }
func (t *themeCyberdyne) CodePunctuation() gothememe.Color { return gothememe.Hex("#00ff92") }
func (t *themeCyberdyne) CodeVariable() gothememe.Color    { return gothememe.Hex("#6bffdd") }
func (t *themeCyberdyne) CodeConstant() gothememe.Color    { return gothememe.Hex("#fffed5") }
func (t *themeCyberdyne) CodeType() gothememe.Color        { return gothememe.Hex("#e6e7fe") }
