// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSlateInstance is the Slate color theme singleton.
var themeSlateInstance gothememe.Theme = &themeSlate{}

// themeSlate implements the Slate theme.
type themeSlate struct{}

func (t *themeSlate) ID() string          { return "slate" }
func (t *themeSlate) DisplayName() string { return "Slate" }
func (t *themeSlate) Description() string { return "Slate color theme" }
func (t *themeSlate) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSlate) License() string     { return "MIT" }
func (t *themeSlate) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeSlate) IsDark() bool        { return true }

// Background colors
func (t *themeSlate) Background() gothememe.Color          { return gothememe.Hex("#222222") }
func (t *themeSlate) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#222222") }
func (t *themeSlate) Surface() gothememe.Color             { return gothememe.Hex("#0f3754") }
func (t *themeSlate) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#ffffff") }

// Text colors
func (t *themeSlate) TextPrimary() gothememe.Color   { return gothememe.Hex("#35b1d2") }
func (t *themeSlate) TextSecondary() gothememe.Color { return gothememe.Hex("#02c5e0") }
func (t *themeSlate) TextMuted() gothememe.Color     { return gothememe.Hex("#ffffff") }
func (t *themeSlate) TextInverted() gothememe.Color  { return gothememe.Hex("#222222") }

// Accent/Brand colors
func (t *themeSlate) Accent() gothememe.Color          { return gothememe.Hex("#335856") }
func (t *themeSlate) AccentSecondary() gothememe.Color { return gothememe.Hex("#a481d3") }
func (t *themeSlate) Brand() gothememe.Color           { return gothememe.Hex("#335856") }

// Border colors
func (t *themeSlate) Border() gothememe.Color       { return gothememe.Hex("#ffffff") }
func (t *themeSlate) BorderSubtle() gothememe.Color { return gothememe.Hex("#222222") }
func (t *themeSlate) BorderStrong() gothememe.Color { return gothememe.Hex("#02c5e0") }

// Semantic colors
func (t *themeSlate) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#81d778").WithAlpha(0.1),
		Border:     gothememe.Hex("#81d778").WithAlpha(0.3),
		Text:       gothememe.Hex("#81d778"),
	}
}

func (t *themeSlate) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c4c9c0").WithAlpha(0.1),
		Border:     gothememe.Hex("#c4c9c0").WithAlpha(0.3),
		Text:       gothememe.Hex("#c4c9c0"),
	}
}

func (t *themeSlate) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e2a8bf").WithAlpha(0.1),
		Border:     gothememe.Hex("#e2a8bf").WithAlpha(0.3),
		Text:       gothememe.Hex("#e2a8bf"),
	}
}

func (t *themeSlate) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#15ab9c").WithAlpha(0.1),
		Border:     gothememe.Hex("#15ab9c").WithAlpha(0.3),
		Text:       gothememe.Hex("#15ab9c"),
	}
}

// ANSI colors
func (t *themeSlate) Black() gothememe.Color        { return gothememe.Hex("#222222") }
func (t *themeSlate) Red() gothememe.Color          { return gothememe.Hex("#e2a8bf") }
func (t *themeSlate) Green() gothememe.Color        { return gothememe.Hex("#81d778") }
func (t *themeSlate) Yellow() gothememe.Color       { return gothememe.Hex("#c4c9c0") }
func (t *themeSlate) Blue() gothememe.Color         { return gothememe.Hex("#335856") }
func (t *themeSlate) Purple() gothememe.Color       { return gothememe.Hex("#a481d3") }
func (t *themeSlate) Cyan() gothememe.Color         { return gothememe.Hex("#15ab9c") }
func (t *themeSlate) White() gothememe.Color        { return gothememe.Hex("#02c5e0") }
func (t *themeSlate) BrightBlack() gothememe.Color  { return gothememe.Hex("#ffffff") }
func (t *themeSlate) BrightRed() gothememe.Color    { return gothememe.Hex("#ffcdd9") }
func (t *themeSlate) BrightGreen() gothememe.Color  { return gothememe.Hex("#beffa8") }
func (t *themeSlate) BrightYellow() gothememe.Color { return gothememe.Hex("#d0ccca") }
func (t *themeSlate) BrightBlue() gothememe.Color   { return gothememe.Hex("#7ab0d2") }
func (t *themeSlate) BrightPurple() gothememe.Color { return gothememe.Hex("#c5a7d9") }
func (t *themeSlate) BrightCyan() gothememe.Color   { return gothememe.Hex("#8cdfe0") }
func (t *themeSlate) BrightWhite() gothememe.Color  { return gothememe.Hex("#e0e0e0") }

// Code/Syntax highlighting colors
func (t *themeSlate) CodeBackground() gothememe.Color  { return gothememe.Hex("#222222") }
func (t *themeSlate) CodeText() gothememe.Color        { return gothememe.Hex("#35b1d2") }
func (t *themeSlate) CodeComment() gothememe.Color     { return gothememe.Hex("#ffffff") }
func (t *themeSlate) CodeKeyword() gothememe.Color     { return gothememe.Hex("#a481d3") }
func (t *themeSlate) CodeString() gothememe.Color      { return gothememe.Hex("#81d778") }
func (t *themeSlate) CodeNumber() gothememe.Color      { return gothememe.Hex("#c4c9c0") }
func (t *themeSlate) CodeFunction() gothememe.Color    { return gothememe.Hex("#335856") }
func (t *themeSlate) CodeOperator() gothememe.Color    { return gothememe.Hex("#e2a8bf") }
func (t *themeSlate) CodePunctuation() gothememe.Color { return gothememe.Hex("#35b1d2") }
func (t *themeSlate) CodeVariable() gothememe.Color    { return gothememe.Hex("#15ab9c") }
func (t *themeSlate) CodeConstant() gothememe.Color    { return gothememe.Hex("#d0ccca") }
func (t *themeSlate) CodeType() gothememe.Color        { return gothememe.Hex("#8cdfe0") }
