// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeRedPlanetInstance is the Red Planet color theme singleton.
var themeRedPlanetInstance gothememe.Theme = &themeRedPlanet{}

// themeRedPlanet implements the Red Planet theme.
type themeRedPlanet struct{}

func (t *themeRedPlanet) ID() string          { return "red_planet" }
func (t *themeRedPlanet) DisplayName() string { return "Red Planet" }
func (t *themeRedPlanet) Description() string { return "Red Planet color theme" }
func (t *themeRedPlanet) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeRedPlanet) License() string     { return "MIT" }
func (t *themeRedPlanet) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeRedPlanet) IsDark() bool        { return true }

// Background colors
func (t *themeRedPlanet) Background() gothememe.Color          { return gothememe.Hex("#222222") }
func (t *themeRedPlanet) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#202020") }
func (t *themeRedPlanet) Surface() gothememe.Color             { return gothememe.Hex("#1b324a") }
func (t *themeRedPlanet) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#676767") }

// Text colors
func (t *themeRedPlanet) TextPrimary() gothememe.Color   { return gothememe.Hex("#c2b790") }
func (t *themeRedPlanet) TextSecondary() gothememe.Color { return gothememe.Hex("#b9aa99") }
func (t *themeRedPlanet) TextMuted() gothememe.Color     { return gothememe.Hex("#676767") }
func (t *themeRedPlanet) TextInverted() gothememe.Color  { return gothememe.Hex("#222222") }

// Accent/Brand colors
func (t *themeRedPlanet) Accent() gothememe.Color          { return gothememe.Hex("#69819e") }
func (t *themeRedPlanet) AccentSecondary() gothememe.Color { return gothememe.Hex("#896492") }
func (t *themeRedPlanet) Brand() gothememe.Color           { return gothememe.Hex("#69819e") }

// Border colors
func (t *themeRedPlanet) Border() gothememe.Color       { return gothememe.Hex("#676767") }
func (t *themeRedPlanet) BorderSubtle() gothememe.Color { return gothememe.Hex("#202020") }
func (t *themeRedPlanet) BorderStrong() gothememe.Color { return gothememe.Hex("#b9aa99") }

// Semantic colors
func (t *themeRedPlanet) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#728271").WithAlpha(0.1),
		Border:     gothememe.Hex("#728271").WithAlpha(0.3),
		Text:       gothememe.Hex("#728271"),
	}
}

func (t *themeRedPlanet) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e8bf6a").WithAlpha(0.1),
		Border:     gothememe.Hex("#e8bf6a").WithAlpha(0.3),
		Text:       gothememe.Hex("#e8bf6a"),
	}
}

func (t *themeRedPlanet) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#8c3432").WithAlpha(0.1),
		Border:     gothememe.Hex("#8c3432").WithAlpha(0.3),
		Text:       gothememe.Hex("#8c3432"),
	}
}

func (t *themeRedPlanet) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5b8390").WithAlpha(0.1),
		Border:     gothememe.Hex("#5b8390").WithAlpha(0.3),
		Text:       gothememe.Hex("#5b8390"),
	}
}

// ANSI colors
func (t *themeRedPlanet) Black() gothememe.Color        { return gothememe.Hex("#202020") }
func (t *themeRedPlanet) Red() gothememe.Color          { return gothememe.Hex("#8c3432") }
func (t *themeRedPlanet) Green() gothememe.Color        { return gothememe.Hex("#728271") }
func (t *themeRedPlanet) Yellow() gothememe.Color       { return gothememe.Hex("#e8bf6a") }
func (t *themeRedPlanet) Blue() gothememe.Color         { return gothememe.Hex("#69819e") }
func (t *themeRedPlanet) Purple() gothememe.Color       { return gothememe.Hex("#896492") }
func (t *themeRedPlanet) Cyan() gothememe.Color         { return gothememe.Hex("#5b8390") }
func (t *themeRedPlanet) White() gothememe.Color        { return gothememe.Hex("#b9aa99") }
func (t *themeRedPlanet) BrightBlack() gothememe.Color  { return gothememe.Hex("#676767") }
func (t *themeRedPlanet) BrightRed() gothememe.Color    { return gothememe.Hex("#b55242") }
func (t *themeRedPlanet) BrightGreen() gothememe.Color  { return gothememe.Hex("#869985") }
func (t *themeRedPlanet) BrightYellow() gothememe.Color { return gothememe.Hex("#ebeb91") }
func (t *themeRedPlanet) BrightBlue() gothememe.Color   { return gothememe.Hex("#60827e") }
func (t *themeRedPlanet) BrightPurple() gothememe.Color { return gothememe.Hex("#de4974") }
func (t *themeRedPlanet) BrightCyan() gothememe.Color   { return gothememe.Hex("#38add8") }
func (t *themeRedPlanet) BrightWhite() gothememe.Color  { return gothememe.Hex("#d6bfb8") }

// Code/Syntax highlighting colors
func (t *themeRedPlanet) CodeBackground() gothememe.Color  { return gothememe.Hex("#222222") }
func (t *themeRedPlanet) CodeText() gothememe.Color        { return gothememe.Hex("#c2b790") }
func (t *themeRedPlanet) CodeComment() gothememe.Color     { return gothememe.Hex("#676767") }
func (t *themeRedPlanet) CodeKeyword() gothememe.Color     { return gothememe.Hex("#896492") }
func (t *themeRedPlanet) CodeString() gothememe.Color      { return gothememe.Hex("#728271") }
func (t *themeRedPlanet) CodeNumber() gothememe.Color      { return gothememe.Hex("#e8bf6a") }
func (t *themeRedPlanet) CodeFunction() gothememe.Color    { return gothememe.Hex("#69819e") }
func (t *themeRedPlanet) CodeOperator() gothememe.Color    { return gothememe.Hex("#8c3432") }
func (t *themeRedPlanet) CodePunctuation() gothememe.Color { return gothememe.Hex("#c2b790") }
func (t *themeRedPlanet) CodeVariable() gothememe.Color    { return gothememe.Hex("#5b8390") }
func (t *themeRedPlanet) CodeConstant() gothememe.Color    { return gothememe.Hex("#ebeb91") }
func (t *themeRedPlanet) CodeType() gothememe.Color        { return gothememe.Hex("#38add8") }
