// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeTangoHalfAdaptedInstance is the Tango Half Adapted color theme singleton.
var themeTangoHalfAdaptedInstance gothememe.Theme = &themeTangoHalfAdapted{}

// themeTangoHalfAdapted implements the Tango Half Adapted theme.
type themeTangoHalfAdapted struct{}

func (t *themeTangoHalfAdapted) ID() string          { return "tango_half_adapted" }
func (t *themeTangoHalfAdapted) DisplayName() string { return "Tango Half Adapted" }
func (t *themeTangoHalfAdapted) Description() string { return "Tango Half Adapted color theme" }
func (t *themeTangoHalfAdapted) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeTangoHalfAdapted) License() string     { return "MIT" }
func (t *themeTangoHalfAdapted) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeTangoHalfAdapted) IsDark() bool { return false }

// Background colors
func (t *themeTangoHalfAdapted) Background() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeTangoHalfAdapted) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#000000")
}
func (t *themeTangoHalfAdapted) Surface() gothememe.Color          { return gothememe.Hex("#c1deff") }
func (t *themeTangoHalfAdapted) SurfaceSecondary() gothememe.Color { return gothememe.Hex("#797d76") }

// Text colors
func (t *themeTangoHalfAdapted) TextPrimary() gothememe.Color   { return gothememe.Hex("#000000") }
func (t *themeTangoHalfAdapted) TextSecondary() gothememe.Color { return gothememe.Hex("#babfb5") }
func (t *themeTangoHalfAdapted) TextMuted() gothememe.Color     { return gothememe.Hex("#797d76") }
func (t *themeTangoHalfAdapted) TextInverted() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Accent/Brand colors
func (t *themeTangoHalfAdapted) Accent() gothememe.Color          { return gothememe.Hex("#008ef6") }
func (t *themeTangoHalfAdapted) AccentSecondary() gothememe.Color { return gothememe.Hex("#a96cb3") }
func (t *themeTangoHalfAdapted) Brand() gothememe.Color           { return gothememe.Hex("#008ef6") }

// Border colors
func (t *themeTangoHalfAdapted) Border() gothememe.Color       { return gothememe.Hex("#797d76") }
func (t *themeTangoHalfAdapted) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeTangoHalfAdapted) BorderStrong() gothememe.Color { return gothememe.Hex("#babfb5") }

// Semantic colors
func (t *themeTangoHalfAdapted) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#4cc300").WithAlpha(0.1),
		Border:     gothememe.Hex("#4cc300").WithAlpha(0.3),
		Text:       gothememe.Hex("#4cc300"),
	}
}

func (t *themeTangoHalfAdapted) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e2c000").WithAlpha(0.1),
		Border:     gothememe.Hex("#e2c000").WithAlpha(0.3),
		Text:       gothememe.Hex("#e2c000"),
	}
}

func (t *themeTangoHalfAdapted) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff0000").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff0000").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff0000"),
	}
}

func (t *themeTangoHalfAdapted) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00bdc3").WithAlpha(0.1),
		Border:     gothememe.Hex("#00bdc3").WithAlpha(0.3),
		Text:       gothememe.Hex("#00bdc3"),
	}
}

// ANSI colors
func (t *themeTangoHalfAdapted) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeTangoHalfAdapted) Red() gothememe.Color          { return gothememe.Hex("#ff0000") }
func (t *themeTangoHalfAdapted) Green() gothememe.Color        { return gothememe.Hex("#4cc300") }
func (t *themeTangoHalfAdapted) Yellow() gothememe.Color       { return gothememe.Hex("#e2c000") }
func (t *themeTangoHalfAdapted) Blue() gothememe.Color         { return gothememe.Hex("#008ef6") }
func (t *themeTangoHalfAdapted) Purple() gothememe.Color       { return gothememe.Hex("#a96cb3") }
func (t *themeTangoHalfAdapted) Cyan() gothememe.Color         { return gothememe.Hex("#00bdc3") }
func (t *themeTangoHalfAdapted) White() gothememe.Color        { return gothememe.Hex("#babfb5") }
func (t *themeTangoHalfAdapted) BrightBlack() gothememe.Color  { return gothememe.Hex("#797d76") }
func (t *themeTangoHalfAdapted) BrightRed() gothememe.Color    { return gothememe.Hex("#ff0013") }
func (t *themeTangoHalfAdapted) BrightGreen() gothememe.Color  { return gothememe.Hex("#70dc00") }
func (t *themeTangoHalfAdapted) BrightYellow() gothememe.Color { return gothememe.Hex("#d9c600") }
func (t *themeTangoHalfAdapted) BrightBlue() gothememe.Color   { return gothememe.Hex("#76bfff") }
func (t *themeTangoHalfAdapted) BrightPurple() gothememe.Color { return gothememe.Hex("#d898d1") }
func (t *themeTangoHalfAdapted) BrightCyan() gothememe.Color   { return gothememe.Hex("#00d0d4") }
func (t *themeTangoHalfAdapted) BrightWhite() gothememe.Color  { return gothememe.Hex("#f4f4f2") }

// Code/Syntax highlighting colors
func (t *themeTangoHalfAdapted) CodeBackground() gothememe.Color  { return gothememe.Hex("#ffffff") }
func (t *themeTangoHalfAdapted) CodeText() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeTangoHalfAdapted) CodeComment() gothememe.Color     { return gothememe.Hex("#797d76") }
func (t *themeTangoHalfAdapted) CodeKeyword() gothememe.Color     { return gothememe.Hex("#a96cb3") }
func (t *themeTangoHalfAdapted) CodeString() gothememe.Color      { return gothememe.Hex("#4cc300") }
func (t *themeTangoHalfAdapted) CodeNumber() gothememe.Color      { return gothememe.Hex("#e2c000") }
func (t *themeTangoHalfAdapted) CodeFunction() gothememe.Color    { return gothememe.Hex("#008ef6") }
func (t *themeTangoHalfAdapted) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff0000") }
func (t *themeTangoHalfAdapted) CodePunctuation() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeTangoHalfAdapted) CodeVariable() gothememe.Color    { return gothememe.Hex("#00bdc3") }
func (t *themeTangoHalfAdapted) CodeConstant() gothememe.Color    { return gothememe.Hex("#d9c600") }
func (t *themeTangoHalfAdapted) CodeType() gothememe.Color        { return gothememe.Hex("#00d0d4") }
