// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeVercelInstance is the Vercel color theme singleton.
var themeVercelInstance gothememe.Theme = &themeVercel{}

// themeVercel implements the Vercel theme.
type themeVercel struct{}

func (t *themeVercel) ID() string          { return "vercel" }
func (t *themeVercel) DisplayName() string { return "Vercel" }
func (t *themeVercel) Description() string { return "Vercel color theme" }
func (t *themeVercel) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeVercel) License() string     { return "MIT" }
func (t *themeVercel) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeVercel) IsDark() bool        { return true }

// Background colors
func (t *themeVercel) Background() gothememe.Color          { return gothememe.Hex("#101010") }
func (t *themeVercel) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeVercel) Surface() gothememe.Color             { return gothememe.Hex("#005be7") }
func (t *themeVercel) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#a8a8a8") }

// Text colors
func (t *themeVercel) TextPrimary() gothememe.Color   { return gothememe.Hex("#fafafa") }
func (t *themeVercel) TextSecondary() gothememe.Color { return gothememe.Hex("#feffff") }
func (t *themeVercel) TextMuted() gothememe.Color     { return gothememe.Hex("#a8a8a8") }
func (t *themeVercel) TextInverted() gothememe.Color  { return gothememe.Hex("#101010") }

// Accent/Brand colors
func (t *themeVercel) Accent() gothememe.Color          { return gothememe.Hex("#006aff") }
func (t *themeVercel) AccentSecondary() gothememe.Color { return gothememe.Hex("#f32882") }
func (t *themeVercel) Brand() gothememe.Color           { return gothememe.Hex("#006aff") }

// Border colors
func (t *themeVercel) Border() gothememe.Color       { return gothememe.Hex("#a8a8a8") }
func (t *themeVercel) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeVercel) BorderStrong() gothememe.Color { return gothememe.Hex("#feffff") }

// Semantic colors
func (t *themeVercel) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#29a948").WithAlpha(0.1),
		Border:     gothememe.Hex("#29a948").WithAlpha(0.3),
		Text:       gothememe.Hex("#29a948"),
	}
}

func (t *themeVercel) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ffae00").WithAlpha(0.1),
		Border:     gothememe.Hex("#ffae00").WithAlpha(0.3),
		Text:       gothememe.Hex("#ffae00"),
	}
}

func (t *themeVercel) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fc0036").WithAlpha(0.1),
		Border:     gothememe.Hex("#fc0036").WithAlpha(0.3),
		Text:       gothememe.Hex("#fc0036"),
	}
}

func (t *themeVercel) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00ac96").WithAlpha(0.1),
		Border:     gothememe.Hex("#00ac96").WithAlpha(0.3),
		Text:       gothememe.Hex("#00ac96"),
	}
}

// ANSI colors
func (t *themeVercel) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeVercel) Red() gothememe.Color          { return gothememe.Hex("#fc0036") }
func (t *themeVercel) Green() gothememe.Color        { return gothememe.Hex("#29a948") }
func (t *themeVercel) Yellow() gothememe.Color       { return gothememe.Hex("#ffae00") }
func (t *themeVercel) Blue() gothememe.Color         { return gothememe.Hex("#006aff") }
func (t *themeVercel) Purple() gothememe.Color       { return gothememe.Hex("#f32882") }
func (t *themeVercel) Cyan() gothememe.Color         { return gothememe.Hex("#00ac96") }
func (t *themeVercel) White() gothememe.Color        { return gothememe.Hex("#feffff") }
func (t *themeVercel) BrightBlack() gothememe.Color  { return gothememe.Hex("#a8a8a8") }
func (t *themeVercel) BrightRed() gothememe.Color    { return gothememe.Hex("#ff8080") }
func (t *themeVercel) BrightGreen() gothememe.Color  { return gothememe.Hex("#4be15d") }
func (t *themeVercel) BrightYellow() gothememe.Color { return gothememe.Hex("#ffae00") }
func (t *themeVercel) BrightBlue() gothememe.Color   { return gothememe.Hex("#49aeff") }
func (t *themeVercel) BrightPurple() gothememe.Color { return gothememe.Hex("#f97ea8") }
func (t *themeVercel) BrightCyan() gothememe.Color   { return gothememe.Hex("#00e4c4") }
func (t *themeVercel) BrightWhite() gothememe.Color  { return gothememe.Hex("#fefefe") }

// Code/Syntax highlighting colors
func (t *themeVercel) CodeBackground() gothememe.Color  { return gothememe.Hex("#101010") }
func (t *themeVercel) CodeText() gothememe.Color        { return gothememe.Hex("#fafafa") }
func (t *themeVercel) CodeComment() gothememe.Color     { return gothememe.Hex("#a8a8a8") }
func (t *themeVercel) CodeKeyword() gothememe.Color     { return gothememe.Hex("#f32882") }
func (t *themeVercel) CodeString() gothememe.Color      { return gothememe.Hex("#29a948") }
func (t *themeVercel) CodeNumber() gothememe.Color      { return gothememe.Hex("#ffae00") }
func (t *themeVercel) CodeFunction() gothememe.Color    { return gothememe.Hex("#006aff") }
func (t *themeVercel) CodeOperator() gothememe.Color    { return gothememe.Hex("#fc0036") }
func (t *themeVercel) CodePunctuation() gothememe.Color { return gothememe.Hex("#fafafa") }
func (t *themeVercel) CodeVariable() gothememe.Color    { return gothememe.Hex("#00ac96") }
func (t *themeVercel) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffae00") }
func (t *themeVercel) CodeType() gothememe.Color        { return gothememe.Hex("#00e4c4") }
