// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeKittyDefaultInstance is the Kitty Default color theme singleton.
var themeKittyDefaultInstance gothememe.Theme = &themeKittyDefault{}

// themeKittyDefault implements the Kitty Default theme.
type themeKittyDefault struct{}

func (t *themeKittyDefault) ID() string          { return "kitty_default" }
func (t *themeKittyDefault) DisplayName() string { return "Kitty Default" }
func (t *themeKittyDefault) Description() string { return "Kitty Default color theme" }
func (t *themeKittyDefault) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeKittyDefault) License() string     { return "MIT" }
func (t *themeKittyDefault) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeKittyDefault) IsDark() bool { return true }

// Background colors
func (t *themeKittyDefault) Background() gothememe.Color          { return gothememe.Hex("#000000") }
func (t *themeKittyDefault) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeKittyDefault) Surface() gothememe.Color             { return gothememe.Hex("#fffacd") }
func (t *themeKittyDefault) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#767676") }

// Text colors
func (t *themeKittyDefault) TextPrimary() gothememe.Color   { return gothememe.Hex("#dddddd") }
func (t *themeKittyDefault) TextSecondary() gothememe.Color { return gothememe.Hex("#dddddd") }
func (t *themeKittyDefault) TextMuted() gothememe.Color     { return gothememe.Hex("#767676") }
func (t *themeKittyDefault) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themeKittyDefault) Accent() gothememe.Color          { return gothememe.Hex("#0d73cc") }
func (t *themeKittyDefault) AccentSecondary() gothememe.Color { return gothememe.Hex("#cb1ed1") }
func (t *themeKittyDefault) Brand() gothememe.Color           { return gothememe.Hex("#0d73cc") }

// Border colors
func (t *themeKittyDefault) Border() gothememe.Color       { return gothememe.Hex("#767676") }
func (t *themeKittyDefault) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeKittyDefault) BorderStrong() gothememe.Color { return gothememe.Hex("#dddddd") }

// Semantic colors
func (t *themeKittyDefault) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#19cb00").WithAlpha(0.1),
		Border:     gothememe.Hex("#19cb00").WithAlpha(0.3),
		Text:       gothememe.Hex("#19cb00"),
	}
}

func (t *themeKittyDefault) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cecb00").WithAlpha(0.1),
		Border:     gothememe.Hex("#cecb00").WithAlpha(0.3),
		Text:       gothememe.Hex("#cecb00"),
	}
}

func (t *themeKittyDefault) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cc0403").WithAlpha(0.1),
		Border:     gothememe.Hex("#cc0403").WithAlpha(0.3),
		Text:       gothememe.Hex("#cc0403"),
	}
}

func (t *themeKittyDefault) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#0dcdcd").WithAlpha(0.1),
		Border:     gothememe.Hex("#0dcdcd").WithAlpha(0.3),
		Text:       gothememe.Hex("#0dcdcd"),
	}
}

// ANSI colors
func (t *themeKittyDefault) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeKittyDefault) Red() gothememe.Color          { return gothememe.Hex("#cc0403") }
func (t *themeKittyDefault) Green() gothememe.Color        { return gothememe.Hex("#19cb00") }
func (t *themeKittyDefault) Yellow() gothememe.Color       { return gothememe.Hex("#cecb00") }
func (t *themeKittyDefault) Blue() gothememe.Color         { return gothememe.Hex("#0d73cc") }
func (t *themeKittyDefault) Purple() gothememe.Color       { return gothememe.Hex("#cb1ed1") }
func (t *themeKittyDefault) Cyan() gothememe.Color         { return gothememe.Hex("#0dcdcd") }
func (t *themeKittyDefault) White() gothememe.Color        { return gothememe.Hex("#dddddd") }
func (t *themeKittyDefault) BrightBlack() gothememe.Color  { return gothememe.Hex("#767676") }
func (t *themeKittyDefault) BrightRed() gothememe.Color    { return gothememe.Hex("#f2201f") }
func (t *themeKittyDefault) BrightGreen() gothememe.Color  { return gothememe.Hex("#23fd00") }
func (t *themeKittyDefault) BrightYellow() gothememe.Color { return gothememe.Hex("#fffd00") }
func (t *themeKittyDefault) BrightBlue() gothememe.Color   { return gothememe.Hex("#1a8fff") }
func (t *themeKittyDefault) BrightPurple() gothememe.Color { return gothememe.Hex("#fd28ff") }
func (t *themeKittyDefault) BrightCyan() gothememe.Color   { return gothememe.Hex("#14ffff") }
func (t *themeKittyDefault) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeKittyDefault) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themeKittyDefault) CodeText() gothememe.Color        { return gothememe.Hex("#dddddd") }
func (t *themeKittyDefault) CodeComment() gothememe.Color     { return gothememe.Hex("#767676") }
func (t *themeKittyDefault) CodeKeyword() gothememe.Color     { return gothememe.Hex("#cb1ed1") }
func (t *themeKittyDefault) CodeString() gothememe.Color      { return gothememe.Hex("#19cb00") }
func (t *themeKittyDefault) CodeNumber() gothememe.Color      { return gothememe.Hex("#cecb00") }
func (t *themeKittyDefault) CodeFunction() gothememe.Color    { return gothememe.Hex("#0d73cc") }
func (t *themeKittyDefault) CodeOperator() gothememe.Color    { return gothememe.Hex("#cc0403") }
func (t *themeKittyDefault) CodePunctuation() gothememe.Color { return gothememe.Hex("#dddddd") }
func (t *themeKittyDefault) CodeVariable() gothememe.Color    { return gothememe.Hex("#0dcdcd") }
func (t *themeKittyDefault) CodeConstant() gothememe.Color    { return gothememe.Hex("#fffd00") }
func (t *themeKittyDefault) CodeType() gothememe.Color        { return gothememe.Hex("#14ffff") }
