// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeCatppuccinMochaInstance is the Catppuccin Mocha color theme singleton.
var themeCatppuccinMochaInstance gothememe.Theme = &themeCatppuccinMocha{}

// themeCatppuccinMocha implements the Catppuccin Mocha theme.
type themeCatppuccinMocha struct{}

func (t *themeCatppuccinMocha) ID() string          { return "catppuccin_mocha" }
func (t *themeCatppuccinMocha) DisplayName() string { return "Catppuccin Mocha" }
func (t *themeCatppuccinMocha) Description() string { return "Catppuccin Mocha color theme" }
func (t *themeCatppuccinMocha) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeCatppuccinMocha) License() string     { return "MIT" }
func (t *themeCatppuccinMocha) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeCatppuccinMocha) IsDark() bool { return true }

// Background colors
func (t *themeCatppuccinMocha) Background() gothememe.Color          { return gothememe.Hex("#1e1e2e") }
func (t *themeCatppuccinMocha) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#45475a") }
func (t *themeCatppuccinMocha) Surface() gothememe.Color             { return gothememe.Hex("#585b70") }
func (t *themeCatppuccinMocha) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#585b70") }

// Text colors
func (t *themeCatppuccinMocha) TextPrimary() gothememe.Color   { return gothememe.Hex("#cdd6f4") }
func (t *themeCatppuccinMocha) TextSecondary() gothememe.Color { return gothememe.Hex("#a6adc8") }
func (t *themeCatppuccinMocha) TextMuted() gothememe.Color     { return gothememe.Hex("#585b70") }
func (t *themeCatppuccinMocha) TextInverted() gothememe.Color  { return gothememe.Hex("#1e1e2e") }

// Accent/Brand colors
func (t *themeCatppuccinMocha) Accent() gothememe.Color          { return gothememe.Hex("#89b4fa") }
func (t *themeCatppuccinMocha) AccentSecondary() gothememe.Color { return gothememe.Hex("#f5c2e7") }
func (t *themeCatppuccinMocha) Brand() gothememe.Color           { return gothememe.Hex("#89b4fa") }

// Border colors
func (t *themeCatppuccinMocha) Border() gothememe.Color       { return gothememe.Hex("#585b70") }
func (t *themeCatppuccinMocha) BorderSubtle() gothememe.Color { return gothememe.Hex("#45475a") }
func (t *themeCatppuccinMocha) BorderStrong() gothememe.Color { return gothememe.Hex("#a6adc8") }

// Semantic colors
func (t *themeCatppuccinMocha) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a6e3a1").WithAlpha(0.1),
		Border:     gothememe.Hex("#a6e3a1").WithAlpha(0.3),
		Text:       gothememe.Hex("#a6e3a1"),
	}
}

func (t *themeCatppuccinMocha) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f9e2af").WithAlpha(0.1),
		Border:     gothememe.Hex("#f9e2af").WithAlpha(0.3),
		Text:       gothememe.Hex("#f9e2af"),
	}
}

func (t *themeCatppuccinMocha) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f38ba8").WithAlpha(0.1),
		Border:     gothememe.Hex("#f38ba8").WithAlpha(0.3),
		Text:       gothememe.Hex("#f38ba8"),
	}
}

func (t *themeCatppuccinMocha) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#94e2d5").WithAlpha(0.1),
		Border:     gothememe.Hex("#94e2d5").WithAlpha(0.3),
		Text:       gothememe.Hex("#94e2d5"),
	}
}

// ANSI colors
func (t *themeCatppuccinMocha) Black() gothememe.Color        { return gothememe.Hex("#45475a") }
func (t *themeCatppuccinMocha) Red() gothememe.Color          { return gothememe.Hex("#f38ba8") }
func (t *themeCatppuccinMocha) Green() gothememe.Color        { return gothememe.Hex("#a6e3a1") }
func (t *themeCatppuccinMocha) Yellow() gothememe.Color       { return gothememe.Hex("#f9e2af") }
func (t *themeCatppuccinMocha) Blue() gothememe.Color         { return gothememe.Hex("#89b4fa") }
func (t *themeCatppuccinMocha) Purple() gothememe.Color       { return gothememe.Hex("#f5c2e7") }
func (t *themeCatppuccinMocha) Cyan() gothememe.Color         { return gothememe.Hex("#94e2d5") }
func (t *themeCatppuccinMocha) White() gothememe.Color        { return gothememe.Hex("#a6adc8") }
func (t *themeCatppuccinMocha) BrightBlack() gothememe.Color  { return gothememe.Hex("#585b70") }
func (t *themeCatppuccinMocha) BrightRed() gothememe.Color    { return gothememe.Hex("#f37799") }
func (t *themeCatppuccinMocha) BrightGreen() gothememe.Color  { return gothememe.Hex("#89d88b") }
func (t *themeCatppuccinMocha) BrightYellow() gothememe.Color { return gothememe.Hex("#ebd391") }
func (t *themeCatppuccinMocha) BrightBlue() gothememe.Color   { return gothememe.Hex("#74a8fc") }
func (t *themeCatppuccinMocha) BrightPurple() gothememe.Color { return gothememe.Hex("#f2aede") }
func (t *themeCatppuccinMocha) BrightCyan() gothememe.Color   { return gothememe.Hex("#6bd7ca") }
func (t *themeCatppuccinMocha) BrightWhite() gothememe.Color  { return gothememe.Hex("#bac2de") }

// Code/Syntax highlighting colors
func (t *themeCatppuccinMocha) CodeBackground() gothememe.Color  { return gothememe.Hex("#1e1e2e") }
func (t *themeCatppuccinMocha) CodeText() gothememe.Color        { return gothememe.Hex("#cdd6f4") }
func (t *themeCatppuccinMocha) CodeComment() gothememe.Color     { return gothememe.Hex("#585b70") }
func (t *themeCatppuccinMocha) CodeKeyword() gothememe.Color     { return gothememe.Hex("#f5c2e7") }
func (t *themeCatppuccinMocha) CodeString() gothememe.Color      { return gothememe.Hex("#a6e3a1") }
func (t *themeCatppuccinMocha) CodeNumber() gothememe.Color      { return gothememe.Hex("#f9e2af") }
func (t *themeCatppuccinMocha) CodeFunction() gothememe.Color    { return gothememe.Hex("#89b4fa") }
func (t *themeCatppuccinMocha) CodeOperator() gothememe.Color    { return gothememe.Hex("#f38ba8") }
func (t *themeCatppuccinMocha) CodePunctuation() gothememe.Color { return gothememe.Hex("#cdd6f4") }
func (t *themeCatppuccinMocha) CodeVariable() gothememe.Color    { return gothememe.Hex("#94e2d5") }
func (t *themeCatppuccinMocha) CodeConstant() gothememe.Color    { return gothememe.Hex("#ebd391") }
func (t *themeCatppuccinMocha) CodeType() gothememe.Color        { return gothememe.Hex("#6bd7ca") }
