// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSpringInstance is the Spring color theme singleton.
var themeSpringInstance gothememe.Theme = &themeSpring{}

// themeSpring implements the Spring theme.
type themeSpring struct{}

func (t *themeSpring) ID() string          { return "spring" }
func (t *themeSpring) DisplayName() string { return "Spring" }
func (t *themeSpring) Description() string { return "Spring color theme" }
func (t *themeSpring) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSpring) License() string     { return "MIT" }
func (t *themeSpring) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeSpring) IsDark() bool        { return false }

// Background colors
func (t *themeSpring) Background() gothememe.Color          { return gothememe.Hex("#ffffff") }
func (t *themeSpring) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeSpring) Surface() gothememe.Color             { return gothememe.Hex("#d6d6d6") }
func (t *themeSpring) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#000000") }

// Text colors
func (t *themeSpring) TextPrimary() gothememe.Color   { return gothememe.Hex("#4d4d4c") }
func (t *themeSpring) TextSecondary() gothememe.Color { return gothememe.Hex("#bfbfbf") }
func (t *themeSpring) TextMuted() gothememe.Color     { return gothememe.Hex("#000000") }
func (t *themeSpring) TextInverted() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Accent/Brand colors
func (t *themeSpring) Accent() gothememe.Color          { return gothememe.Hex("#1dd3ee") }
func (t *themeSpring) AccentSecondary() gothememe.Color { return gothememe.Hex("#8959a8") }
func (t *themeSpring) Brand() gothememe.Color           { return gothememe.Hex("#1dd3ee") }

// Border colors
func (t *themeSpring) Border() gothememe.Color       { return gothememe.Hex("#000000") }
func (t *themeSpring) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeSpring) BorderStrong() gothememe.Color { return gothememe.Hex("#bfbfbf") }

// Semantic colors
func (t *themeSpring) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1f8c3b").WithAlpha(0.1),
		Border:     gothememe.Hex("#1f8c3b").WithAlpha(0.3),
		Text:       gothememe.Hex("#1f8c3b"),
	}
}

func (t *themeSpring) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1fc95b").WithAlpha(0.1),
		Border:     gothememe.Hex("#1fc95b").WithAlpha(0.3),
		Text:       gothememe.Hex("#1fc95b"),
	}
}

func (t *themeSpring) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff4d83").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff4d83").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff4d83"),
	}
}

func (t *themeSpring) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#3e999f").WithAlpha(0.1),
		Border:     gothememe.Hex("#3e999f").WithAlpha(0.3),
		Text:       gothememe.Hex("#3e999f"),
	}
}

// ANSI colors
func (t *themeSpring) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeSpring) Red() gothememe.Color          { return gothememe.Hex("#ff4d83") }
func (t *themeSpring) Green() gothememe.Color        { return gothememe.Hex("#1f8c3b") }
func (t *themeSpring) Yellow() gothememe.Color       { return gothememe.Hex("#1fc95b") }
func (t *themeSpring) Blue() gothememe.Color         { return gothememe.Hex("#1dd3ee") }
func (t *themeSpring) Purple() gothememe.Color       { return gothememe.Hex("#8959a8") }
func (t *themeSpring) Cyan() gothememe.Color         { return gothememe.Hex("#3e999f") }
func (t *themeSpring) White() gothememe.Color        { return gothememe.Hex("#bfbfbf") }
func (t *themeSpring) BrightBlack() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themeSpring) BrightRed() gothememe.Color    { return gothememe.Hex("#ff0021") }
func (t *themeSpring) BrightGreen() gothememe.Color  { return gothememe.Hex("#1fc231") }
func (t *themeSpring) BrightYellow() gothememe.Color { return gothememe.Hex("#d5b807") }
func (t *themeSpring) BrightBlue() gothememe.Color   { return gothememe.Hex("#15a9fd") }
func (t *themeSpring) BrightPurple() gothememe.Color { return gothememe.Hex("#8959a8") }
func (t *themeSpring) BrightCyan() gothememe.Color   { return gothememe.Hex("#3e999f") }
func (t *themeSpring) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeSpring) CodeBackground() gothememe.Color  { return gothememe.Hex("#ffffff") }
func (t *themeSpring) CodeText() gothememe.Color        { return gothememe.Hex("#4d4d4c") }
func (t *themeSpring) CodeComment() gothememe.Color     { return gothememe.Hex("#000000") }
func (t *themeSpring) CodeKeyword() gothememe.Color     { return gothememe.Hex("#8959a8") }
func (t *themeSpring) CodeString() gothememe.Color      { return gothememe.Hex("#1f8c3b") }
func (t *themeSpring) CodeNumber() gothememe.Color      { return gothememe.Hex("#1fc95b") }
func (t *themeSpring) CodeFunction() gothememe.Color    { return gothememe.Hex("#1dd3ee") }
func (t *themeSpring) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff4d83") }
func (t *themeSpring) CodePunctuation() gothememe.Color { return gothememe.Hex("#4d4d4c") }
func (t *themeSpring) CodeVariable() gothememe.Color    { return gothememe.Hex("#3e999f") }
func (t *themeSpring) CodeConstant() gothememe.Color    { return gothememe.Hex("#d5b807") }
func (t *themeSpring) CodeType() gothememe.Color        { return gothememe.Hex("#3e999f") }
