// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeIcebergLightInstance is the Iceberg Light color theme singleton.
var themeIcebergLightInstance gothememe.Theme = &themeIcebergLight{}

// themeIcebergLight implements the Iceberg Light theme.
type themeIcebergLight struct{}

func (t *themeIcebergLight) ID() string          { return "iceberg_light" }
func (t *themeIcebergLight) DisplayName() string { return "Iceberg Light" }
func (t *themeIcebergLight) Description() string { return "Iceberg Light color theme" }
func (t *themeIcebergLight) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeIcebergLight) License() string     { return "MIT" }
func (t *themeIcebergLight) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeIcebergLight) IsDark() bool { return false }

// Background colors
func (t *themeIcebergLight) Background() gothememe.Color          { return gothememe.Hex("#e8e9ec") }
func (t *themeIcebergLight) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#dcdfe7") }
func (t *themeIcebergLight) Surface() gothememe.Color             { return gothememe.Hex("#33374c") }
func (t *themeIcebergLight) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#8389a3") }

// Text colors
func (t *themeIcebergLight) TextPrimary() gothememe.Color   { return gothememe.Hex("#33374c") }
func (t *themeIcebergLight) TextSecondary() gothememe.Color { return gothememe.Hex("#33374c") }
func (t *themeIcebergLight) TextMuted() gothememe.Color     { return gothememe.Hex("#8389a3") }
func (t *themeIcebergLight) TextInverted() gothememe.Color  { return gothememe.Hex("#e8e9ec") }

// Accent/Brand colors
func (t *themeIcebergLight) Accent() gothememe.Color          { return gothememe.Hex("#2d539e") }
func (t *themeIcebergLight) AccentSecondary() gothememe.Color { return gothememe.Hex("#7759b4") }
func (t *themeIcebergLight) Brand() gothememe.Color           { return gothememe.Hex("#2d539e") }

// Border colors
func (t *themeIcebergLight) Border() gothememe.Color       { return gothememe.Hex("#8389a3") }
func (t *themeIcebergLight) BorderSubtle() gothememe.Color { return gothememe.Hex("#dcdfe7") }
func (t *themeIcebergLight) BorderStrong() gothememe.Color { return gothememe.Hex("#33374c") }

// Semantic colors
func (t *themeIcebergLight) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#668e3d").WithAlpha(0.1),
		Border:     gothememe.Hex("#668e3d").WithAlpha(0.3),
		Text:       gothememe.Hex("#668e3d"),
	}
}

func (t *themeIcebergLight) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c57339").WithAlpha(0.1),
		Border:     gothememe.Hex("#c57339").WithAlpha(0.3),
		Text:       gothememe.Hex("#c57339"),
	}
}

func (t *themeIcebergLight) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cc517a").WithAlpha(0.1),
		Border:     gothememe.Hex("#cc517a").WithAlpha(0.3),
		Text:       gothememe.Hex("#cc517a"),
	}
}

func (t *themeIcebergLight) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#3f83a6").WithAlpha(0.1),
		Border:     gothememe.Hex("#3f83a6").WithAlpha(0.3),
		Text:       gothememe.Hex("#3f83a6"),
	}
}

// ANSI colors
func (t *themeIcebergLight) Black() gothememe.Color        { return gothememe.Hex("#dcdfe7") }
func (t *themeIcebergLight) Red() gothememe.Color          { return gothememe.Hex("#cc517a") }
func (t *themeIcebergLight) Green() gothememe.Color        { return gothememe.Hex("#668e3d") }
func (t *themeIcebergLight) Yellow() gothememe.Color       { return gothememe.Hex("#c57339") }
func (t *themeIcebergLight) Blue() gothememe.Color         { return gothememe.Hex("#2d539e") }
func (t *themeIcebergLight) Purple() gothememe.Color       { return gothememe.Hex("#7759b4") }
func (t *themeIcebergLight) Cyan() gothememe.Color         { return gothememe.Hex("#3f83a6") }
func (t *themeIcebergLight) White() gothememe.Color        { return gothememe.Hex("#33374c") }
func (t *themeIcebergLight) BrightBlack() gothememe.Color  { return gothememe.Hex("#8389a3") }
func (t *themeIcebergLight) BrightRed() gothememe.Color    { return gothememe.Hex("#cc3768") }
func (t *themeIcebergLight) BrightGreen() gothememe.Color  { return gothememe.Hex("#598030") }
func (t *themeIcebergLight) BrightYellow() gothememe.Color { return gothememe.Hex("#b6662d") }
func (t *themeIcebergLight) BrightBlue() gothememe.Color   { return gothememe.Hex("#22478e") }
func (t *themeIcebergLight) BrightPurple() gothememe.Color { return gothememe.Hex("#6845ad") }
func (t *themeIcebergLight) BrightCyan() gothememe.Color   { return gothememe.Hex("#327698") }
func (t *themeIcebergLight) BrightWhite() gothememe.Color  { return gothememe.Hex("#262a3f") }

// Code/Syntax highlighting colors
func (t *themeIcebergLight) CodeBackground() gothememe.Color  { return gothememe.Hex("#e8e9ec") }
func (t *themeIcebergLight) CodeText() gothememe.Color        { return gothememe.Hex("#33374c") }
func (t *themeIcebergLight) CodeComment() gothememe.Color     { return gothememe.Hex("#8389a3") }
func (t *themeIcebergLight) CodeKeyword() gothememe.Color     { return gothememe.Hex("#7759b4") }
func (t *themeIcebergLight) CodeString() gothememe.Color      { return gothememe.Hex("#668e3d") }
func (t *themeIcebergLight) CodeNumber() gothememe.Color      { return gothememe.Hex("#c57339") }
func (t *themeIcebergLight) CodeFunction() gothememe.Color    { return gothememe.Hex("#2d539e") }
func (t *themeIcebergLight) CodeOperator() gothememe.Color    { return gothememe.Hex("#cc517a") }
func (t *themeIcebergLight) CodePunctuation() gothememe.Color { return gothememe.Hex("#33374c") }
func (t *themeIcebergLight) CodeVariable() gothememe.Color    { return gothememe.Hex("#3f83a6") }
func (t *themeIcebergLight) CodeConstant() gothememe.Color    { return gothememe.Hex("#b6662d") }
func (t *themeIcebergLight) CodeType() gothememe.Color        { return gothememe.Hex("#327698") }
