// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeBlueBerryPieInstance is the Blue Berry Pie color theme singleton.
var themeBlueBerryPieInstance gothememe.Theme = &themeBlueBerryPie{}

// themeBlueBerryPie implements the Blue Berry Pie theme.
type themeBlueBerryPie struct{}

func (t *themeBlueBerryPie) ID() string          { return "blue_berry_pie" }
func (t *themeBlueBerryPie) DisplayName() string { return "Blue Berry Pie" }
func (t *themeBlueBerryPie) Description() string { return "Blue Berry Pie color theme" }
func (t *themeBlueBerryPie) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeBlueBerryPie) License() string     { return "MIT" }
func (t *themeBlueBerryPie) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeBlueBerryPie) IsDark() bool { return true }

// Background colors
func (t *themeBlueBerryPie) Background() gothememe.Color          { return gothememe.Hex("#1c0c28") }
func (t *themeBlueBerryPie) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#0a4c62") }
func (t *themeBlueBerryPie) Surface() gothememe.Color             { return gothememe.Hex("#606060") }
func (t *themeBlueBerryPie) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#463c5d") }

// Text colors
func (t *themeBlueBerryPie) TextPrimary() gothememe.Color   { return gothememe.Hex("#babab9") }
func (t *themeBlueBerryPie) TextSecondary() gothememe.Color { return gothememe.Hex("#f0e8d6") }
func (t *themeBlueBerryPie) TextMuted() gothememe.Color     { return gothememe.Hex("#463c5d") }
func (t *themeBlueBerryPie) TextInverted() gothememe.Color  { return gothememe.Hex("#1c0c28") }

// Accent/Brand colors
func (t *themeBlueBerryPie) Accent() gothememe.Color          { return gothememe.Hex("#90a5bd") }
func (t *themeBlueBerryPie) AccentSecondary() gothememe.Color { return gothememe.Hex("#9d54a7") }
func (t *themeBlueBerryPie) Brand() gothememe.Color           { return gothememe.Hex("#90a5bd") }

// Border colors
func (t *themeBlueBerryPie) Border() gothememe.Color       { return gothememe.Hex("#463c5d") }
func (t *themeBlueBerryPie) BorderSubtle() gothememe.Color { return gothememe.Hex("#0a4c62") }
func (t *themeBlueBerryPie) BorderStrong() gothememe.Color { return gothememe.Hex("#f0e8d6") }

// Semantic colors
func (t *themeBlueBerryPie) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5cb1b3").WithAlpha(0.1),
		Border:     gothememe.Hex("#5cb1b3").WithAlpha(0.3),
		Text:       gothememe.Hex("#5cb1b3"),
	}
}

func (t *themeBlueBerryPie) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#eab9a8").WithAlpha(0.1),
		Border:     gothememe.Hex("#eab9a8").WithAlpha(0.3),
		Text:       gothememe.Hex("#eab9a8"),
	}
}

func (t *themeBlueBerryPie) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#99246e").WithAlpha(0.1),
		Border:     gothememe.Hex("#99246e").WithAlpha(0.3),
		Text:       gothememe.Hex("#99246e"),
	}
}

func (t *themeBlueBerryPie) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#7e83cc").WithAlpha(0.1),
		Border:     gothememe.Hex("#7e83cc").WithAlpha(0.3),
		Text:       gothememe.Hex("#7e83cc"),
	}
}

// ANSI colors
func (t *themeBlueBerryPie) Black() gothememe.Color        { return gothememe.Hex("#0a4c62") }
func (t *themeBlueBerryPie) Red() gothememe.Color          { return gothememe.Hex("#99246e") }
func (t *themeBlueBerryPie) Green() gothememe.Color        { return gothememe.Hex("#5cb1b3") }
func (t *themeBlueBerryPie) Yellow() gothememe.Color       { return gothememe.Hex("#eab9a8") }
func (t *themeBlueBerryPie) Blue() gothememe.Color         { return gothememe.Hex("#90a5bd") }
func (t *themeBlueBerryPie) Purple() gothememe.Color       { return gothememe.Hex("#9d54a7") }
func (t *themeBlueBerryPie) Cyan() gothememe.Color         { return gothememe.Hex("#7e83cc") }
func (t *themeBlueBerryPie) White() gothememe.Color        { return gothememe.Hex("#f0e8d6") }
func (t *themeBlueBerryPie) BrightBlack() gothememe.Color  { return gothememe.Hex("#463c5d") }
func (t *themeBlueBerryPie) BrightRed() gothememe.Color    { return gothememe.Hex("#c87272") }
func (t *themeBlueBerryPie) BrightGreen() gothememe.Color  { return gothememe.Hex("#0a6c7e") }
func (t *themeBlueBerryPie) BrightYellow() gothememe.Color { return gothememe.Hex("#7a3188") }
func (t *themeBlueBerryPie) BrightBlue() gothememe.Color   { return gothememe.Hex("#5f3d63") }
func (t *themeBlueBerryPie) BrightPurple() gothememe.Color { return gothememe.Hex("#bc94b7") }
func (t *themeBlueBerryPie) BrightCyan() gothememe.Color   { return gothememe.Hex("#5e6071") }
func (t *themeBlueBerryPie) BrightWhite() gothememe.Color  { return gothememe.Hex("#0a6c7e") }

// Code/Syntax highlighting colors
func (t *themeBlueBerryPie) CodeBackground() gothememe.Color  { return gothememe.Hex("#1c0c28") }
func (t *themeBlueBerryPie) CodeText() gothememe.Color        { return gothememe.Hex("#babab9") }
func (t *themeBlueBerryPie) CodeComment() gothememe.Color     { return gothememe.Hex("#463c5d") }
func (t *themeBlueBerryPie) CodeKeyword() gothememe.Color     { return gothememe.Hex("#9d54a7") }
func (t *themeBlueBerryPie) CodeString() gothememe.Color      { return gothememe.Hex("#5cb1b3") }
func (t *themeBlueBerryPie) CodeNumber() gothememe.Color      { return gothememe.Hex("#eab9a8") }
func (t *themeBlueBerryPie) CodeFunction() gothememe.Color    { return gothememe.Hex("#90a5bd") }
func (t *themeBlueBerryPie) CodeOperator() gothememe.Color    { return gothememe.Hex("#99246e") }
func (t *themeBlueBerryPie) CodePunctuation() gothememe.Color { return gothememe.Hex("#babab9") }
func (t *themeBlueBerryPie) CodeVariable() gothememe.Color    { return gothememe.Hex("#7e83cc") }
func (t *themeBlueBerryPie) CodeConstant() gothememe.Color    { return gothememe.Hex("#7a3188") }
func (t *themeBlueBerryPie) CodeType() gothememe.Color        { return gothememe.Hex("#5e6071") }
