// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeIbm5153CgaBlackInstance is the IBM 5153 CGA (Black) color theme singleton.
var themeIbm5153CgaBlackInstance gothememe.Theme = &themeIbm5153CgaBlack{}

// themeIbm5153CgaBlack implements the IBM 5153 CGA (Black) theme.
type themeIbm5153CgaBlack struct{}

func (t *themeIbm5153CgaBlack) ID() string          { return "ibm_5153_cga_black" }
func (t *themeIbm5153CgaBlack) DisplayName() string { return "IBM 5153 CGA (Black)" }
func (t *themeIbm5153CgaBlack) Description() string { return "IBM 5153 CGA (Black) color theme" }
func (t *themeIbm5153CgaBlack) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeIbm5153CgaBlack) License() string     { return "MIT" }
func (t *themeIbm5153CgaBlack) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeIbm5153CgaBlack) IsDark() bool { return true }

// Background colors
func (t *themeIbm5153CgaBlack) Background() gothememe.Color          { return gothememe.Hex("#000000") }
func (t *themeIbm5153CgaBlack) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeIbm5153CgaBlack) Surface() gothememe.Color             { return gothememe.Hex("#c4c4c4") }
func (t *themeIbm5153CgaBlack) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4e4e4e") }

// Text colors
func (t *themeIbm5153CgaBlack) TextPrimary() gothememe.Color   { return gothememe.Hex("#c4c4c4") }
func (t *themeIbm5153CgaBlack) TextSecondary() gothememe.Color { return gothememe.Hex("#c4c4c4") }
func (t *themeIbm5153CgaBlack) TextMuted() gothememe.Color     { return gothememe.Hex("#4e4e4e") }
func (t *themeIbm5153CgaBlack) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themeIbm5153CgaBlack) Accent() gothememe.Color          { return gothememe.Hex("#0000c4") }
func (t *themeIbm5153CgaBlack) AccentSecondary() gothememe.Color { return gothememe.Hex("#c400c4") }
func (t *themeIbm5153CgaBlack) Brand() gothememe.Color           { return gothememe.Hex("#0000c4") }

// Border colors
func (t *themeIbm5153CgaBlack) Border() gothememe.Color       { return gothememe.Hex("#4e4e4e") }
func (t *themeIbm5153CgaBlack) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeIbm5153CgaBlack) BorderStrong() gothememe.Color { return gothememe.Hex("#c4c4c4") }

// Semantic colors
func (t *themeIbm5153CgaBlack) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00c400").WithAlpha(0.1),
		Border:     gothememe.Hex("#00c400").WithAlpha(0.3),
		Text:       gothememe.Hex("#00c400"),
	}
}

func (t *themeIbm5153CgaBlack) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c47e00").WithAlpha(0.1),
		Border:     gothememe.Hex("#c47e00").WithAlpha(0.3),
		Text:       gothememe.Hex("#c47e00"),
	}
}

func (t *themeIbm5153CgaBlack) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c40000").WithAlpha(0.1),
		Border:     gothememe.Hex("#c40000").WithAlpha(0.3),
		Text:       gothememe.Hex("#c40000"),
	}
}

func (t *themeIbm5153CgaBlack) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00c4c4").WithAlpha(0.1),
		Border:     gothememe.Hex("#00c4c4").WithAlpha(0.3),
		Text:       gothememe.Hex("#00c4c4"),
	}
}

// ANSI colors
func (t *themeIbm5153CgaBlack) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeIbm5153CgaBlack) Red() gothememe.Color          { return gothememe.Hex("#c40000") }
func (t *themeIbm5153CgaBlack) Green() gothememe.Color        { return gothememe.Hex("#00c400") }
func (t *themeIbm5153CgaBlack) Yellow() gothememe.Color       { return gothememe.Hex("#c47e00") }
func (t *themeIbm5153CgaBlack) Blue() gothememe.Color         { return gothememe.Hex("#0000c4") }
func (t *themeIbm5153CgaBlack) Purple() gothememe.Color       { return gothememe.Hex("#c400c4") }
func (t *themeIbm5153CgaBlack) Cyan() gothememe.Color         { return gothememe.Hex("#00c4c4") }
func (t *themeIbm5153CgaBlack) White() gothememe.Color        { return gothememe.Hex("#c4c4c4") }
func (t *themeIbm5153CgaBlack) BrightBlack() gothememe.Color  { return gothememe.Hex("#4e4e4e") }
func (t *themeIbm5153CgaBlack) BrightRed() gothememe.Color    { return gothememe.Hex("#dc4e4e") }
func (t *themeIbm5153CgaBlack) BrightGreen() gothememe.Color  { return gothememe.Hex("#4edc4e") }
func (t *themeIbm5153CgaBlack) BrightYellow() gothememe.Color { return gothememe.Hex("#f3f34e") }
func (t *themeIbm5153CgaBlack) BrightBlue() gothememe.Color   { return gothememe.Hex("#4e4edc") }
func (t *themeIbm5153CgaBlack) BrightPurple() gothememe.Color { return gothememe.Hex("#f34ef3") }
func (t *themeIbm5153CgaBlack) BrightCyan() gothememe.Color   { return gothememe.Hex("#4ef3f3") }
func (t *themeIbm5153CgaBlack) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeIbm5153CgaBlack) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themeIbm5153CgaBlack) CodeText() gothememe.Color        { return gothememe.Hex("#c4c4c4") }
func (t *themeIbm5153CgaBlack) CodeComment() gothememe.Color     { return gothememe.Hex("#4e4e4e") }
func (t *themeIbm5153CgaBlack) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c400c4") }
func (t *themeIbm5153CgaBlack) CodeString() gothememe.Color      { return gothememe.Hex("#00c400") }
func (t *themeIbm5153CgaBlack) CodeNumber() gothememe.Color      { return gothememe.Hex("#c47e00") }
func (t *themeIbm5153CgaBlack) CodeFunction() gothememe.Color    { return gothememe.Hex("#0000c4") }
func (t *themeIbm5153CgaBlack) CodeOperator() gothememe.Color    { return gothememe.Hex("#c40000") }
func (t *themeIbm5153CgaBlack) CodePunctuation() gothememe.Color { return gothememe.Hex("#c4c4c4") }
func (t *themeIbm5153CgaBlack) CodeVariable() gothememe.Color    { return gothememe.Hex("#00c4c4") }
func (t *themeIbm5153CgaBlack) CodeConstant() gothememe.Color    { return gothememe.Hex("#f3f34e") }
func (t *themeIbm5153CgaBlack) CodeType() gothememe.Color        { return gothememe.Hex("#4ef3f3") }
