// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeZenburnedInstance is the Zenburned color theme singleton.
var themeZenburnedInstance gothememe.Theme = &themeZenburned{}

// themeZenburned implements the Zenburned theme.
type themeZenburned struct{}

func (t *themeZenburned) ID() string          { return "zenburned" }
func (t *themeZenburned) DisplayName() string { return "Zenburned" }
func (t *themeZenburned) Description() string { return "Zenburned color theme" }
func (t *themeZenburned) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeZenburned) License() string     { return "MIT" }
func (t *themeZenburned) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeZenburned) IsDark() bool        { return true }

// Background colors
func (t *themeZenburned) Background() gothememe.Color          { return gothememe.Hex("#404040") }
func (t *themeZenburned) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#404040") }
func (t *themeZenburned) Surface() gothememe.Color             { return gothememe.Hex("#746956") }
func (t *themeZenburned) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#6f6768") }

// Text colors
func (t *themeZenburned) TextPrimary() gothememe.Color   { return gothememe.Hex("#f0e4cf") }
func (t *themeZenburned) TextSecondary() gothememe.Color { return gothememe.Hex("#f0e4cf") }
func (t *themeZenburned) TextMuted() gothememe.Color     { return gothememe.Hex("#6f6768") }
func (t *themeZenburned) TextInverted() gothememe.Color  { return gothememe.Hex("#404040") }

// Accent/Brand colors
func (t *themeZenburned) Accent() gothememe.Color          { return gothememe.Hex("#6099c0") }
func (t *themeZenburned) AccentSecondary() gothememe.Color { return gothememe.Hex("#b279a7") }
func (t *themeZenburned) Brand() gothememe.Color           { return gothememe.Hex("#6099c0") }

// Border colors
func (t *themeZenburned) Border() gothememe.Color       { return gothememe.Hex("#6f6768") }
func (t *themeZenburned) BorderSubtle() gothememe.Color { return gothememe.Hex("#404040") }
func (t *themeZenburned) BorderStrong() gothememe.Color { return gothememe.Hex("#f0e4cf") }

// Semantic colors
func (t *themeZenburned) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#819b69").WithAlpha(0.1),
		Border:     gothememe.Hex("#819b69").WithAlpha(0.3),
		Text:       gothememe.Hex("#819b69"),
	}
}

func (t *themeZenburned) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#b77e64").WithAlpha(0.1),
		Border:     gothememe.Hex("#b77e64").WithAlpha(0.3),
		Text:       gothememe.Hex("#b77e64"),
	}
}

func (t *themeZenburned) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e3716e").WithAlpha(0.1),
		Border:     gothememe.Hex("#e3716e").WithAlpha(0.3),
		Text:       gothememe.Hex("#e3716e"),
	}
}

func (t *themeZenburned) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#66a5ad").WithAlpha(0.1),
		Border:     gothememe.Hex("#66a5ad").WithAlpha(0.3),
		Text:       gothememe.Hex("#66a5ad"),
	}
}

// ANSI colors
func (t *themeZenburned) Black() gothememe.Color        { return gothememe.Hex("#404040") }
func (t *themeZenburned) Red() gothememe.Color          { return gothememe.Hex("#e3716e") }
func (t *themeZenburned) Green() gothememe.Color        { return gothememe.Hex("#819b69") }
func (t *themeZenburned) Yellow() gothememe.Color       { return gothememe.Hex("#b77e64") }
func (t *themeZenburned) Blue() gothememe.Color         { return gothememe.Hex("#6099c0") }
func (t *themeZenburned) Purple() gothememe.Color       { return gothememe.Hex("#b279a7") }
func (t *themeZenburned) Cyan() gothememe.Color         { return gothememe.Hex("#66a5ad") }
func (t *themeZenburned) White() gothememe.Color        { return gothememe.Hex("#f0e4cf") }
func (t *themeZenburned) BrightBlack() gothememe.Color  { return gothememe.Hex("#6f6768") }
func (t *themeZenburned) BrightRed() gothememe.Color    { return gothememe.Hex("#ec8685") }
func (t *themeZenburned) BrightGreen() gothememe.Color  { return gothememe.Hex("#8bae68") }
func (t *themeZenburned) BrightYellow() gothememe.Color { return gothememe.Hex("#d68c67") }
func (t *themeZenburned) BrightBlue() gothememe.Color   { return gothememe.Hex("#61abda") }
func (t *themeZenburned) BrightPurple() gothememe.Color { return gothememe.Hex("#cf86c1") }
func (t *themeZenburned) BrightCyan() gothememe.Color   { return gothememe.Hex("#65b8c1") }
func (t *themeZenburned) BrightWhite() gothememe.Color  { return gothememe.Hex("#c0ab86") }

// Code/Syntax highlighting colors
func (t *themeZenburned) CodeBackground() gothememe.Color  { return gothememe.Hex("#404040") }
func (t *themeZenburned) CodeText() gothememe.Color        { return gothememe.Hex("#f0e4cf") }
func (t *themeZenburned) CodeComment() gothememe.Color     { return gothememe.Hex("#6f6768") }
func (t *themeZenburned) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b279a7") }
func (t *themeZenburned) CodeString() gothememe.Color      { return gothememe.Hex("#819b69") }
func (t *themeZenburned) CodeNumber() gothememe.Color      { return gothememe.Hex("#b77e64") }
func (t *themeZenburned) CodeFunction() gothememe.Color    { return gothememe.Hex("#6099c0") }
func (t *themeZenburned) CodeOperator() gothememe.Color    { return gothememe.Hex("#e3716e") }
func (t *themeZenburned) CodePunctuation() gothememe.Color { return gothememe.Hex("#f0e4cf") }
func (t *themeZenburned) CodeVariable() gothememe.Color    { return gothememe.Hex("#66a5ad") }
func (t *themeZenburned) CodeConstant() gothememe.Color    { return gothememe.Hex("#d68c67") }
func (t *themeZenburned) CodeType() gothememe.Color        { return gothememe.Hex("#65b8c1") }
