// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeDarkInstance is the Dark+ color theme singleton.
var themeDarkInstance gothememe.Theme = &themeDark{}

// themeDark implements the Dark+ theme.
type themeDark struct{}

func (t *themeDark) ID() string          { return "dark" }
func (t *themeDark) DisplayName() string { return "Dark+" }
func (t *themeDark) Description() string { return "Dark+ color theme" }
func (t *themeDark) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeDark) License() string     { return "MIT" }
func (t *themeDark) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeDark) IsDark() bool        { return true }

// Background colors
func (t *themeDark) Background() gothememe.Color          { return gothememe.Hex("#1e1e1e") }
func (t *themeDark) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeDark) Surface() gothememe.Color             { return gothememe.Hex("#3a3d41") }
func (t *themeDark) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#666666") }

// Text colors
func (t *themeDark) TextPrimary() gothememe.Color   { return gothememe.Hex("#cccccc") }
func (t *themeDark) TextSecondary() gothememe.Color { return gothememe.Hex("#e5e5e5") }
func (t *themeDark) TextMuted() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeDark) TextInverted() gothememe.Color  { return gothememe.Hex("#1e1e1e") }

// Accent/Brand colors
func (t *themeDark) Accent() gothememe.Color          { return gothememe.Hex("#2472c8") }
func (t *themeDark) AccentSecondary() gothememe.Color { return gothememe.Hex("#bc3fbc") }
func (t *themeDark) Brand() gothememe.Color           { return gothememe.Hex("#2472c8") }

// Border colors
func (t *themeDark) Border() gothememe.Color       { return gothememe.Hex("#666666") }
func (t *themeDark) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeDark) BorderStrong() gothememe.Color { return gothememe.Hex("#e5e5e5") }

// Semantic colors
func (t *themeDark) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#0dbc79").WithAlpha(0.1),
		Border:     gothememe.Hex("#0dbc79").WithAlpha(0.3),
		Text:       gothememe.Hex("#0dbc79"),
	}
}

func (t *themeDark) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e5e510").WithAlpha(0.1),
		Border:     gothememe.Hex("#e5e510").WithAlpha(0.3),
		Text:       gothememe.Hex("#e5e510"),
	}
}

func (t *themeDark) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cd3131").WithAlpha(0.1),
		Border:     gothememe.Hex("#cd3131").WithAlpha(0.3),
		Text:       gothememe.Hex("#cd3131"),
	}
}

func (t *themeDark) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#11a8cd").WithAlpha(0.1),
		Border:     gothememe.Hex("#11a8cd").WithAlpha(0.3),
		Text:       gothememe.Hex("#11a8cd"),
	}
}

// ANSI colors
func (t *themeDark) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeDark) Red() gothememe.Color          { return gothememe.Hex("#cd3131") }
func (t *themeDark) Green() gothememe.Color        { return gothememe.Hex("#0dbc79") }
func (t *themeDark) Yellow() gothememe.Color       { return gothememe.Hex("#e5e510") }
func (t *themeDark) Blue() gothememe.Color         { return gothememe.Hex("#2472c8") }
func (t *themeDark) Purple() gothememe.Color       { return gothememe.Hex("#bc3fbc") }
func (t *themeDark) Cyan() gothememe.Color         { return gothememe.Hex("#11a8cd") }
func (t *themeDark) White() gothememe.Color        { return gothememe.Hex("#e5e5e5") }
func (t *themeDark) BrightBlack() gothememe.Color  { return gothememe.Hex("#666666") }
func (t *themeDark) BrightRed() gothememe.Color    { return gothememe.Hex("#f14c4c") }
func (t *themeDark) BrightGreen() gothememe.Color  { return gothememe.Hex("#23d18b") }
func (t *themeDark) BrightYellow() gothememe.Color { return gothememe.Hex("#f5f543") }
func (t *themeDark) BrightBlue() gothememe.Color   { return gothememe.Hex("#3b8eea") }
func (t *themeDark) BrightPurple() gothememe.Color { return gothememe.Hex("#d670d6") }
func (t *themeDark) BrightCyan() gothememe.Color   { return gothememe.Hex("#29b8db") }
func (t *themeDark) BrightWhite() gothememe.Color  { return gothememe.Hex("#e5e5e5") }

// Code/Syntax highlighting colors
func (t *themeDark) CodeBackground() gothememe.Color  { return gothememe.Hex("#1e1e1e") }
func (t *themeDark) CodeText() gothememe.Color        { return gothememe.Hex("#cccccc") }
func (t *themeDark) CodeComment() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeDark) CodeKeyword() gothememe.Color     { return gothememe.Hex("#bc3fbc") }
func (t *themeDark) CodeString() gothememe.Color      { return gothememe.Hex("#0dbc79") }
func (t *themeDark) CodeNumber() gothememe.Color      { return gothememe.Hex("#e5e510") }
func (t *themeDark) CodeFunction() gothememe.Color    { return gothememe.Hex("#2472c8") }
func (t *themeDark) CodeOperator() gothememe.Color    { return gothememe.Hex("#cd3131") }
func (t *themeDark) CodePunctuation() gothememe.Color { return gothememe.Hex("#cccccc") }
func (t *themeDark) CodeVariable() gothememe.Color    { return gothememe.Hex("#11a8cd") }
func (t *themeDark) CodeConstant() gothememe.Color    { return gothememe.Hex("#f5f543") }
func (t *themeDark) CodeType() gothememe.Color        { return gothememe.Hex("#29b8db") }
