// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeMonokaiSodaInstance is the Monokai Soda color theme singleton.
var themeMonokaiSodaInstance gothememe.Theme = &themeMonokaiSoda{}

// themeMonokaiSoda implements the Monokai Soda theme.
type themeMonokaiSoda struct{}

func (t *themeMonokaiSoda) ID() string          { return "monokai_soda" }
func (t *themeMonokaiSoda) DisplayName() string { return "Monokai Soda" }
func (t *themeMonokaiSoda) Description() string { return "Monokai Soda color theme" }
func (t *themeMonokaiSoda) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeMonokaiSoda) License() string     { return "MIT" }
func (t *themeMonokaiSoda) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeMonokaiSoda) IsDark() bool { return true }

// Background colors
func (t *themeMonokaiSoda) Background() gothememe.Color          { return gothememe.Hex("#1a1a1a") }
func (t *themeMonokaiSoda) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#1a1a1a") }
func (t *themeMonokaiSoda) Surface() gothememe.Color             { return gothememe.Hex("#343434") }
func (t *themeMonokaiSoda) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#625e4c") }

// Text colors
func (t *themeMonokaiSoda) TextPrimary() gothememe.Color   { return gothememe.Hex("#c4c5b5") }
func (t *themeMonokaiSoda) TextSecondary() gothememe.Color { return gothememe.Hex("#c4c5b5") }
func (t *themeMonokaiSoda) TextMuted() gothememe.Color     { return gothememe.Hex("#625e4c") }
func (t *themeMonokaiSoda) TextInverted() gothememe.Color  { return gothememe.Hex("#1a1a1a") }

// Accent/Brand colors
func (t *themeMonokaiSoda) Accent() gothememe.Color          { return gothememe.Hex("#9d65ff") }
func (t *themeMonokaiSoda) AccentSecondary() gothememe.Color { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) Brand() gothememe.Color           { return gothememe.Hex("#9d65ff") }

// Border colors
func (t *themeMonokaiSoda) Border() gothememe.Color       { return gothememe.Hex("#625e4c") }
func (t *themeMonokaiSoda) BorderSubtle() gothememe.Color { return gothememe.Hex("#1a1a1a") }
func (t *themeMonokaiSoda) BorderStrong() gothememe.Color { return gothememe.Hex("#c4c5b5") }

// Semantic colors
func (t *themeMonokaiSoda) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#98e024").WithAlpha(0.1),
		Border:     gothememe.Hex("#98e024").WithAlpha(0.3),
		Text:       gothememe.Hex("#98e024"),
	}
}

func (t *themeMonokaiSoda) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fa8419").WithAlpha(0.1),
		Border:     gothememe.Hex("#fa8419").WithAlpha(0.3),
		Text:       gothememe.Hex("#fa8419"),
	}
}

func (t *themeMonokaiSoda) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f4005f").WithAlpha(0.1),
		Border:     gothememe.Hex("#f4005f").WithAlpha(0.3),
		Text:       gothememe.Hex("#f4005f"),
	}
}

func (t *themeMonokaiSoda) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#58d1eb").WithAlpha(0.1),
		Border:     gothememe.Hex("#58d1eb").WithAlpha(0.3),
		Text:       gothememe.Hex("#58d1eb"),
	}
}

// ANSI colors
func (t *themeMonokaiSoda) Black() gothememe.Color        { return gothememe.Hex("#1a1a1a") }
func (t *themeMonokaiSoda) Red() gothememe.Color          { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) Green() gothememe.Color        { return gothememe.Hex("#98e024") }
func (t *themeMonokaiSoda) Yellow() gothememe.Color       { return gothememe.Hex("#fa8419") }
func (t *themeMonokaiSoda) Blue() gothememe.Color         { return gothememe.Hex("#9d65ff") }
func (t *themeMonokaiSoda) Purple() gothememe.Color       { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) Cyan() gothememe.Color         { return gothememe.Hex("#58d1eb") }
func (t *themeMonokaiSoda) White() gothememe.Color        { return gothememe.Hex("#c4c5b5") }
func (t *themeMonokaiSoda) BrightBlack() gothememe.Color  { return gothememe.Hex("#625e4c") }
func (t *themeMonokaiSoda) BrightRed() gothememe.Color    { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) BrightGreen() gothememe.Color  { return gothememe.Hex("#98e024") }
func (t *themeMonokaiSoda) BrightYellow() gothememe.Color { return gothememe.Hex("#e0d561") }
func (t *themeMonokaiSoda) BrightBlue() gothememe.Color   { return gothememe.Hex("#9d65ff") }
func (t *themeMonokaiSoda) BrightPurple() gothememe.Color { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) BrightCyan() gothememe.Color   { return gothememe.Hex("#58d1eb") }
func (t *themeMonokaiSoda) BrightWhite() gothememe.Color  { return gothememe.Hex("#f6f6ef") }

// Code/Syntax highlighting colors
func (t *themeMonokaiSoda) CodeBackground() gothememe.Color  { return gothememe.Hex("#1a1a1a") }
func (t *themeMonokaiSoda) CodeText() gothememe.Color        { return gothememe.Hex("#c4c5b5") }
func (t *themeMonokaiSoda) CodeComment() gothememe.Color     { return gothememe.Hex("#625e4c") }
func (t *themeMonokaiSoda) CodeKeyword() gothememe.Color     { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) CodeString() gothememe.Color      { return gothememe.Hex("#98e024") }
func (t *themeMonokaiSoda) CodeNumber() gothememe.Color      { return gothememe.Hex("#fa8419") }
func (t *themeMonokaiSoda) CodeFunction() gothememe.Color    { return gothememe.Hex("#9d65ff") }
func (t *themeMonokaiSoda) CodeOperator() gothememe.Color    { return gothememe.Hex("#f4005f") }
func (t *themeMonokaiSoda) CodePunctuation() gothememe.Color { return gothememe.Hex("#c4c5b5") }
func (t *themeMonokaiSoda) CodeVariable() gothememe.Color    { return gothememe.Hex("#58d1eb") }
func (t *themeMonokaiSoda) CodeConstant() gothememe.Color    { return gothememe.Hex("#e0d561") }
func (t *themeMonokaiSoda) CodeType() gothememe.Color        { return gothememe.Hex("#58d1eb") }
