// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeBlackMetalGorgorothInstance is the Black Metal (Gorgoroth) color theme singleton.
var themeBlackMetalGorgorothInstance gothememe.Theme = &themeBlackMetalGorgoroth{}

// themeBlackMetalGorgoroth implements the Black Metal (Gorgoroth) theme.
type themeBlackMetalGorgoroth struct{}

func (t *themeBlackMetalGorgoroth) ID() string          { return "black_metal_gorgoroth" }
func (t *themeBlackMetalGorgoroth) DisplayName() string { return "Black Metal (Gorgoroth)" }
func (t *themeBlackMetalGorgoroth) Description() string { return "Black Metal (Gorgoroth) color theme" }
func (t *themeBlackMetalGorgoroth) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeBlackMetalGorgoroth) License() string     { return "MIT" }
func (t *themeBlackMetalGorgoroth) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeBlackMetalGorgoroth) IsDark() bool { return true }

// Background colors
func (t *themeBlackMetalGorgoroth) Background() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeBlackMetalGorgoroth) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#000000")
}
func (t *themeBlackMetalGorgoroth) Surface() gothememe.Color { return gothememe.Hex("#c1c1c1") }
func (t *themeBlackMetalGorgoroth) SurfaceSecondary() gothememe.Color {
	return gothememe.Hex("#404040")
}

// Text colors
func (t *themeBlackMetalGorgoroth) TextPrimary() gothememe.Color   { return gothememe.Hex("#c1c1c1") }
func (t *themeBlackMetalGorgoroth) TextSecondary() gothememe.Color { return gothememe.Hex("#c1c1c1") }
func (t *themeBlackMetalGorgoroth) TextMuted() gothememe.Color     { return gothememe.Hex("#404040") }
func (t *themeBlackMetalGorgoroth) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themeBlackMetalGorgoroth) Accent() gothememe.Color          { return gothememe.Hex("#888888") }
func (t *themeBlackMetalGorgoroth) AccentSecondary() gothememe.Color { return gothememe.Hex("#999999") }
func (t *themeBlackMetalGorgoroth) Brand() gothememe.Color           { return gothememe.Hex("#888888") }

// Border colors
func (t *themeBlackMetalGorgoroth) Border() gothememe.Color       { return gothememe.Hex("#404040") }
func (t *themeBlackMetalGorgoroth) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeBlackMetalGorgoroth) BorderStrong() gothememe.Color { return gothememe.Hex("#c1c1c1") }

// Semantic colors
func (t *themeBlackMetalGorgoroth) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#9b8d7f").WithAlpha(0.1),
		Border:     gothememe.Hex("#9b8d7f").WithAlpha(0.3),
		Text:       gothememe.Hex("#9b8d7f"),
	}
}

func (t *themeBlackMetalGorgoroth) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#8c7f70").WithAlpha(0.1),
		Border:     gothememe.Hex("#8c7f70").WithAlpha(0.3),
		Text:       gothememe.Hex("#8c7f70"),
	}
}

func (t *themeBlackMetalGorgoroth) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#5f8787").WithAlpha(0.1),
		Border:     gothememe.Hex("#5f8787").WithAlpha(0.3),
		Text:       gothememe.Hex("#5f8787"),
	}
}

func (t *themeBlackMetalGorgoroth) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#aaaaaa").WithAlpha(0.1),
		Border:     gothememe.Hex("#aaaaaa").WithAlpha(0.3),
		Text:       gothememe.Hex("#aaaaaa"),
	}
}

// ANSI colors
func (t *themeBlackMetalGorgoroth) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeBlackMetalGorgoroth) Red() gothememe.Color          { return gothememe.Hex("#5f8787") }
func (t *themeBlackMetalGorgoroth) Green() gothememe.Color        { return gothememe.Hex("#9b8d7f") }
func (t *themeBlackMetalGorgoroth) Yellow() gothememe.Color       { return gothememe.Hex("#8c7f70") }
func (t *themeBlackMetalGorgoroth) Blue() gothememe.Color         { return gothememe.Hex("#888888") }
func (t *themeBlackMetalGorgoroth) Purple() gothememe.Color       { return gothememe.Hex("#999999") }
func (t *themeBlackMetalGorgoroth) Cyan() gothememe.Color         { return gothememe.Hex("#aaaaaa") }
func (t *themeBlackMetalGorgoroth) White() gothememe.Color        { return gothememe.Hex("#c1c1c1") }
func (t *themeBlackMetalGorgoroth) BrightBlack() gothememe.Color  { return gothememe.Hex("#404040") }
func (t *themeBlackMetalGorgoroth) BrightRed() gothememe.Color    { return gothememe.Hex("#5f8787") }
func (t *themeBlackMetalGorgoroth) BrightGreen() gothememe.Color  { return gothememe.Hex("#9b8d7f") }
func (t *themeBlackMetalGorgoroth) BrightYellow() gothememe.Color { return gothememe.Hex("#8c7f70") }
func (t *themeBlackMetalGorgoroth) BrightBlue() gothememe.Color   { return gothememe.Hex("#888888") }
func (t *themeBlackMetalGorgoroth) BrightPurple() gothememe.Color { return gothememe.Hex("#999999") }
func (t *themeBlackMetalGorgoroth) BrightCyan() gothememe.Color   { return gothememe.Hex("#aaaaaa") }
func (t *themeBlackMetalGorgoroth) BrightWhite() gothememe.Color  { return gothememe.Hex("#c1c1c1") }

// Code/Syntax highlighting colors
func (t *themeBlackMetalGorgoroth) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themeBlackMetalGorgoroth) CodeText() gothememe.Color        { return gothememe.Hex("#c1c1c1") }
func (t *themeBlackMetalGorgoroth) CodeComment() gothememe.Color     { return gothememe.Hex("#404040") }
func (t *themeBlackMetalGorgoroth) CodeKeyword() gothememe.Color     { return gothememe.Hex("#999999") }
func (t *themeBlackMetalGorgoroth) CodeString() gothememe.Color      { return gothememe.Hex("#9b8d7f") }
func (t *themeBlackMetalGorgoroth) CodeNumber() gothememe.Color      { return gothememe.Hex("#8c7f70") }
func (t *themeBlackMetalGorgoroth) CodeFunction() gothememe.Color    { return gothememe.Hex("#888888") }
func (t *themeBlackMetalGorgoroth) CodeOperator() gothememe.Color    { return gothememe.Hex("#5f8787") }
func (t *themeBlackMetalGorgoroth) CodePunctuation() gothememe.Color { return gothememe.Hex("#c1c1c1") }
func (t *themeBlackMetalGorgoroth) CodeVariable() gothememe.Color    { return gothememe.Hex("#aaaaaa") }
func (t *themeBlackMetalGorgoroth) CodeConstant() gothememe.Color    { return gothememe.Hex("#8c7f70") }
func (t *themeBlackMetalGorgoroth) CodeType() gothememe.Color        { return gothememe.Hex("#aaaaaa") }
