// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeNightOwlInstance is the Night Owl color theme singleton.
var themeNightOwlInstance gothememe.Theme = &themeNightOwl{}

// themeNightOwl implements the Night Owl theme.
type themeNightOwl struct{}

func (t *themeNightOwl) ID() string          { return "night_owl" }
func (t *themeNightOwl) DisplayName() string { return "Night Owl" }
func (t *themeNightOwl) Description() string { return "Night Owl color theme" }
func (t *themeNightOwl) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeNightOwl) License() string     { return "MIT" }
func (t *themeNightOwl) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeNightOwl) IsDark() bool        { return true }

// Background colors
func (t *themeNightOwl) Background() gothememe.Color          { return gothememe.Hex("#011627") }
func (t *themeNightOwl) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#011627") }
func (t *themeNightOwl) Surface() gothememe.Color             { return gothememe.Hex("#5f7e97") }
func (t *themeNightOwl) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#575656") }

// Text colors
func (t *themeNightOwl) TextPrimary() gothememe.Color   { return gothememe.Hex("#d6deeb") }
func (t *themeNightOwl) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeNightOwl) TextMuted() gothememe.Color     { return gothememe.Hex("#575656") }
func (t *themeNightOwl) TextInverted() gothememe.Color  { return gothememe.Hex("#011627") }

// Accent/Brand colors
func (t *themeNightOwl) Accent() gothememe.Color          { return gothememe.Hex("#82aaff") }
func (t *themeNightOwl) AccentSecondary() gothememe.Color { return gothememe.Hex("#c792ea") }
func (t *themeNightOwl) Brand() gothememe.Color           { return gothememe.Hex("#82aaff") }

// Border colors
func (t *themeNightOwl) Border() gothememe.Color       { return gothememe.Hex("#575656") }
func (t *themeNightOwl) BorderSubtle() gothememe.Color { return gothememe.Hex("#011627") }
func (t *themeNightOwl) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeNightOwl) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#22da6e").WithAlpha(0.1),
		Border:     gothememe.Hex("#22da6e").WithAlpha(0.3),
		Text:       gothememe.Hex("#22da6e"),
	}
}

func (t *themeNightOwl) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#addb67").WithAlpha(0.1),
		Border:     gothememe.Hex("#addb67").WithAlpha(0.3),
		Text:       gothememe.Hex("#addb67"),
	}
}

func (t *themeNightOwl) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ef5350").WithAlpha(0.1),
		Border:     gothememe.Hex("#ef5350").WithAlpha(0.3),
		Text:       gothememe.Hex("#ef5350"),
	}
}

func (t *themeNightOwl) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#21c7a8").WithAlpha(0.1),
		Border:     gothememe.Hex("#21c7a8").WithAlpha(0.3),
		Text:       gothememe.Hex("#21c7a8"),
	}
}

// ANSI colors
func (t *themeNightOwl) Black() gothememe.Color        { return gothememe.Hex("#011627") }
func (t *themeNightOwl) Red() gothememe.Color          { return gothememe.Hex("#ef5350") }
func (t *themeNightOwl) Green() gothememe.Color        { return gothememe.Hex("#22da6e") }
func (t *themeNightOwl) Yellow() gothememe.Color       { return gothememe.Hex("#addb67") }
func (t *themeNightOwl) Blue() gothememe.Color         { return gothememe.Hex("#82aaff") }
func (t *themeNightOwl) Purple() gothememe.Color       { return gothememe.Hex("#c792ea") }
func (t *themeNightOwl) Cyan() gothememe.Color         { return gothememe.Hex("#21c7a8") }
func (t *themeNightOwl) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeNightOwl) BrightBlack() gothememe.Color  { return gothememe.Hex("#575656") }
func (t *themeNightOwl) BrightRed() gothememe.Color    { return gothememe.Hex("#ef5350") }
func (t *themeNightOwl) BrightGreen() gothememe.Color  { return gothememe.Hex("#22da6e") }
func (t *themeNightOwl) BrightYellow() gothememe.Color { return gothememe.Hex("#ffeb95") }
func (t *themeNightOwl) BrightBlue() gothememe.Color   { return gothememe.Hex("#82aaff") }
func (t *themeNightOwl) BrightPurple() gothememe.Color { return gothememe.Hex("#c792ea") }
func (t *themeNightOwl) BrightCyan() gothememe.Color   { return gothememe.Hex("#7fdbca") }
func (t *themeNightOwl) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeNightOwl) CodeBackground() gothememe.Color  { return gothememe.Hex("#011627") }
func (t *themeNightOwl) CodeText() gothememe.Color        { return gothememe.Hex("#d6deeb") }
func (t *themeNightOwl) CodeComment() gothememe.Color     { return gothememe.Hex("#575656") }
func (t *themeNightOwl) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c792ea") }
func (t *themeNightOwl) CodeString() gothememe.Color      { return gothememe.Hex("#22da6e") }
func (t *themeNightOwl) CodeNumber() gothememe.Color      { return gothememe.Hex("#addb67") }
func (t *themeNightOwl) CodeFunction() gothememe.Color    { return gothememe.Hex("#82aaff") }
func (t *themeNightOwl) CodeOperator() gothememe.Color    { return gothememe.Hex("#ef5350") }
func (t *themeNightOwl) CodePunctuation() gothememe.Color { return gothememe.Hex("#d6deeb") }
func (t *themeNightOwl) CodeVariable() gothememe.Color    { return gothememe.Hex("#21c7a8") }
func (t *themeNightOwl) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffeb95") }
func (t *themeNightOwl) CodeType() gothememe.Color        { return gothememe.Hex("#7fdbca") }
