// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeHeelerInstance is the Heeler color theme singleton.
var themeHeelerInstance gothememe.Theme = &themeHeeler{}

// themeHeeler implements the Heeler theme.
type themeHeeler struct{}

func (t *themeHeeler) ID() string          { return "heeler" }
func (t *themeHeeler) DisplayName() string { return "Heeler" }
func (t *themeHeeler) Description() string { return "Heeler color theme" }
func (t *themeHeeler) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeHeeler) License() string     { return "MIT" }
func (t *themeHeeler) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeHeeler) IsDark() bool        { return true }

// Background colors
func (t *themeHeeler) Background() gothememe.Color          { return gothememe.Hex("#211f46") }
func (t *themeHeeler) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeHeeler) Surface() gothememe.Color             { return gothememe.Hex("#2b2c41") }
func (t *themeHeeler) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4c4c4c") }

// Text colors
func (t *themeHeeler) TextPrimary() gothememe.Color   { return gothememe.Hex("#fdfdfd") }
func (t *themeHeeler) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeHeeler) TextMuted() gothememe.Color     { return gothememe.Hex("#4c4c4c") }
func (t *themeHeeler) TextInverted() gothememe.Color  { return gothememe.Hex("#211f46") }

// Accent/Brand colors
func (t *themeHeeler) Accent() gothememe.Color          { return gothememe.Hex("#5ba5f2") }
func (t *themeHeeler) AccentSecondary() gothememe.Color { return gothememe.Hex("#ff95c2") }
func (t *themeHeeler) Brand() gothememe.Color           { return gothememe.Hex("#5ba5f2") }

// Border colors
func (t *themeHeeler) Border() gothememe.Color       { return gothememe.Hex("#4c4c4c") }
func (t *themeHeeler) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeHeeler) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeHeeler) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#bdd100").WithAlpha(0.1),
		Border:     gothememe.Hex("#bdd100").WithAlpha(0.3),
		Text:       gothememe.Hex("#bdd100"),
	}
}

func (t *themeHeeler) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f4ce65").WithAlpha(0.1),
		Border:     gothememe.Hex("#f4ce65").WithAlpha(0.3),
		Text:       gothememe.Hex("#f4ce65"),
	}
}

func (t *themeHeeler) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e44c2e").WithAlpha(0.1),
		Border:     gothememe.Hex("#e44c2e").WithAlpha(0.3),
		Text:       gothememe.Hex("#e44c2e"),
	}
}

func (t *themeHeeler) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff9763").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff9763").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff9763"),
	}
}

// ANSI colors
func (t *themeHeeler) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeHeeler) Red() gothememe.Color          { return gothememe.Hex("#e44c2e") }
func (t *themeHeeler) Green() gothememe.Color        { return gothememe.Hex("#bdd100") }
func (t *themeHeeler) Yellow() gothememe.Color       { return gothememe.Hex("#f4ce65") }
func (t *themeHeeler) Blue() gothememe.Color         { return gothememe.Hex("#5ba5f2") }
func (t *themeHeeler) Purple() gothememe.Color       { return gothememe.Hex("#ff95c2") }
func (t *themeHeeler) Cyan() gothememe.Color         { return gothememe.Hex("#ff9763") }
func (t *themeHeeler) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeHeeler) BrightBlack() gothememe.Color  { return gothememe.Hex("#4c4c4c") }
func (t *themeHeeler) BrightRed() gothememe.Color    { return gothememe.Hex("#e44c2e") }
func (t *themeHeeler) BrightGreen() gothememe.Color  { return gothememe.Hex("#bdd100") }
func (t *themeHeeler) BrightYellow() gothememe.Color { return gothememe.Hex("#f4ce65") }
func (t *themeHeeler) BrightBlue() gothememe.Color   { return gothememe.Hex("#0088ff") }
func (t *themeHeeler) BrightPurple() gothememe.Color { return gothememe.Hex("#ff95c2") }
func (t *themeHeeler) BrightCyan() gothememe.Color   { return gothememe.Hex("#8da6e4") }
func (t *themeHeeler) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeHeeler) CodeBackground() gothememe.Color  { return gothememe.Hex("#211f46") }
func (t *themeHeeler) CodeText() gothememe.Color        { return gothememe.Hex("#fdfdfd") }
func (t *themeHeeler) CodeComment() gothememe.Color     { return gothememe.Hex("#4c4c4c") }
func (t *themeHeeler) CodeKeyword() gothememe.Color     { return gothememe.Hex("#ff95c2") }
func (t *themeHeeler) CodeString() gothememe.Color      { return gothememe.Hex("#bdd100") }
func (t *themeHeeler) CodeNumber() gothememe.Color      { return gothememe.Hex("#f4ce65") }
func (t *themeHeeler) CodeFunction() gothememe.Color    { return gothememe.Hex("#5ba5f2") }
func (t *themeHeeler) CodeOperator() gothememe.Color    { return gothememe.Hex("#e44c2e") }
func (t *themeHeeler) CodePunctuation() gothememe.Color { return gothememe.Hex("#fdfdfd") }
func (t *themeHeeler) CodeVariable() gothememe.Color    { return gothememe.Hex("#ff9763") }
func (t *themeHeeler) CodeConstant() gothememe.Color    { return gothememe.Hex("#f4ce65") }
func (t *themeHeeler) CodeType() gothememe.Color        { return gothememe.Hex("#8da6e4") }
