// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeNightfoxInstance is the Nightfox color theme singleton.
var themeNightfoxInstance gothememe.Theme = &themeNightfox{}

// themeNightfox implements the Nightfox theme.
type themeNightfox struct{}

func (t *themeNightfox) ID() string          { return "nightfox" }
func (t *themeNightfox) DisplayName() string { return "Nightfox" }
func (t *themeNightfox) Description() string { return "Nightfox color theme" }
func (t *themeNightfox) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeNightfox) License() string     { return "MIT" }
func (t *themeNightfox) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeNightfox) IsDark() bool        { return true }

// Background colors
func (t *themeNightfox) Background() gothememe.Color          { return gothememe.Hex("#192330") }
func (t *themeNightfox) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#393b44") }
func (t *themeNightfox) Surface() gothememe.Color             { return gothememe.Hex("#2b3b51") }
func (t *themeNightfox) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#575860") }

// Text colors
func (t *themeNightfox) TextPrimary() gothememe.Color   { return gothememe.Hex("#cdcecf") }
func (t *themeNightfox) TextSecondary() gothememe.Color { return gothememe.Hex("#dfdfe0") }
func (t *themeNightfox) TextMuted() gothememe.Color     { return gothememe.Hex("#575860") }
func (t *themeNightfox) TextInverted() gothememe.Color  { return gothememe.Hex("#192330") }

// Accent/Brand colors
func (t *themeNightfox) Accent() gothememe.Color          { return gothememe.Hex("#719cd6") }
func (t *themeNightfox) AccentSecondary() gothememe.Color { return gothememe.Hex("#9d79d6") }
func (t *themeNightfox) Brand() gothememe.Color           { return gothememe.Hex("#719cd6") }

// Border colors
func (t *themeNightfox) Border() gothememe.Color       { return gothememe.Hex("#575860") }
func (t *themeNightfox) BorderSubtle() gothememe.Color { return gothememe.Hex("#393b44") }
func (t *themeNightfox) BorderStrong() gothememe.Color { return gothememe.Hex("#dfdfe0") }

// Semantic colors
func (t *themeNightfox) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#81b29a").WithAlpha(0.1),
		Border:     gothememe.Hex("#81b29a").WithAlpha(0.3),
		Text:       gothememe.Hex("#81b29a"),
	}
}

func (t *themeNightfox) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#dbc074").WithAlpha(0.1),
		Border:     gothememe.Hex("#dbc074").WithAlpha(0.3),
		Text:       gothememe.Hex("#dbc074"),
	}
}

func (t *themeNightfox) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c94f6d").WithAlpha(0.1),
		Border:     gothememe.Hex("#c94f6d").WithAlpha(0.3),
		Text:       gothememe.Hex("#c94f6d"),
	}
}

func (t *themeNightfox) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#63cdcf").WithAlpha(0.1),
		Border:     gothememe.Hex("#63cdcf").WithAlpha(0.3),
		Text:       gothememe.Hex("#63cdcf"),
	}
}

// ANSI colors
func (t *themeNightfox) Black() gothememe.Color        { return gothememe.Hex("#393b44") }
func (t *themeNightfox) Red() gothememe.Color          { return gothememe.Hex("#c94f6d") }
func (t *themeNightfox) Green() gothememe.Color        { return gothememe.Hex("#81b29a") }
func (t *themeNightfox) Yellow() gothememe.Color       { return gothememe.Hex("#dbc074") }
func (t *themeNightfox) Blue() gothememe.Color         { return gothememe.Hex("#719cd6") }
func (t *themeNightfox) Purple() gothememe.Color       { return gothememe.Hex("#9d79d6") }
func (t *themeNightfox) Cyan() gothememe.Color         { return gothememe.Hex("#63cdcf") }
func (t *themeNightfox) White() gothememe.Color        { return gothememe.Hex("#dfdfe0") }
func (t *themeNightfox) BrightBlack() gothememe.Color  { return gothememe.Hex("#575860") }
func (t *themeNightfox) BrightRed() gothememe.Color    { return gothememe.Hex("#d16983") }
func (t *themeNightfox) BrightGreen() gothememe.Color  { return gothememe.Hex("#8ebaa4") }
func (t *themeNightfox) BrightYellow() gothememe.Color { return gothememe.Hex("#e0c989") }
func (t *themeNightfox) BrightBlue() gothememe.Color   { return gothememe.Hex("#86abdc") }
func (t *themeNightfox) BrightPurple() gothememe.Color { return gothememe.Hex("#baa1e2") }
func (t *themeNightfox) BrightCyan() gothememe.Color   { return gothememe.Hex("#7ad5d6") }
func (t *themeNightfox) BrightWhite() gothememe.Color  { return gothememe.Hex("#e4e4e5") }

// Code/Syntax highlighting colors
func (t *themeNightfox) CodeBackground() gothememe.Color  { return gothememe.Hex("#192330") }
func (t *themeNightfox) CodeText() gothememe.Color        { return gothememe.Hex("#cdcecf") }
func (t *themeNightfox) CodeComment() gothememe.Color     { return gothememe.Hex("#575860") }
func (t *themeNightfox) CodeKeyword() gothememe.Color     { return gothememe.Hex("#9d79d6") }
func (t *themeNightfox) CodeString() gothememe.Color      { return gothememe.Hex("#81b29a") }
func (t *themeNightfox) CodeNumber() gothememe.Color      { return gothememe.Hex("#dbc074") }
func (t *themeNightfox) CodeFunction() gothememe.Color    { return gothememe.Hex("#719cd6") }
func (t *themeNightfox) CodeOperator() gothememe.Color    { return gothememe.Hex("#c94f6d") }
func (t *themeNightfox) CodePunctuation() gothememe.Color { return gothememe.Hex("#cdcecf") }
func (t *themeNightfox) CodeVariable() gothememe.Color    { return gothememe.Hex("#63cdcf") }
func (t *themeNightfox) CodeConstant() gothememe.Color    { return gothememe.Hex("#e0c989") }
func (t *themeNightfox) CodeType() gothememe.Color        { return gothememe.Hex("#7ad5d6") }
