// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themePhalaGreenDarkInstance is the Phala Green Dark color theme singleton.
var themePhalaGreenDarkInstance gothememe.Theme = &themePhalaGreenDark{}

// themePhalaGreenDark implements the Phala Green Dark theme.
type themePhalaGreenDark struct{}

func (t *themePhalaGreenDark) ID() string          { return "phala_green_dark" }
func (t *themePhalaGreenDark) DisplayName() string { return "Phala Green Dark" }
func (t *themePhalaGreenDark) Description() string { return "Phala Green Dark color theme" }
func (t *themePhalaGreenDark) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themePhalaGreenDark) License() string     { return "MIT" }
func (t *themePhalaGreenDark) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themePhalaGreenDark) IsDark() bool { return true }

// Background colors
func (t *themePhalaGreenDark) Background() gothememe.Color          { return gothememe.Hex("#000000") }
func (t *themePhalaGreenDark) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themePhalaGreenDark) Surface() gothememe.Color             { return gothememe.Hex("#014804") }
func (t *themePhalaGreenDark) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#797979") }

// Text colors
func (t *themePhalaGreenDark) TextPrimary() gothememe.Color   { return gothememe.Hex("#c1fc03") }
func (t *themePhalaGreenDark) TextSecondary() gothememe.Color { return gothememe.Hex("#cbcbcb") }
func (t *themePhalaGreenDark) TextMuted() gothememe.Color     { return gothememe.Hex("#797979") }
func (t *themePhalaGreenDark) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themePhalaGreenDark) Accent() gothememe.Color          { return gothememe.Hex("#0223c0") }
func (t *themePhalaGreenDark) AccentSecondary() gothememe.Color { return gothememe.Hex("#c22ec0") }
func (t *themePhalaGreenDark) Brand() gothememe.Color           { return gothememe.Hex("#0223c0") }

// Border colors
func (t *themePhalaGreenDark) Border() gothememe.Color       { return gothememe.Hex("#797979") }
func (t *themePhalaGreenDark) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themePhalaGreenDark) BorderStrong() gothememe.Color { return gothememe.Hex("#cbcbcb") }

// Semantic colors
func (t *themePhalaGreenDark) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00b100").WithAlpha(0.1),
		Border:     gothememe.Hex("#00b100").WithAlpha(0.3),
		Text:       gothememe.Hex("#00b100"),
	}
}

func (t *themePhalaGreenDark) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a9a700").WithAlpha(0.1),
		Border:     gothememe.Hex("#a9a700").WithAlpha(0.3),
		Text:       gothememe.Hex("#a9a700"),
	}
}

func (t *themePhalaGreenDark) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ab1500").WithAlpha(0.1),
		Border:     gothememe.Hex("#ab1500").WithAlpha(0.3),
		Text:       gothememe.Hex("#ab1500"),
	}
}

func (t *themePhalaGreenDark) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00b4c0").WithAlpha(0.1),
		Border:     gothememe.Hex("#00b4c0").WithAlpha(0.3),
		Text:       gothememe.Hex("#00b4c0"),
	}
}

// ANSI colors
func (t *themePhalaGreenDark) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themePhalaGreenDark) Red() gothememe.Color          { return gothememe.Hex("#ab1500") }
func (t *themePhalaGreenDark) Green() gothememe.Color        { return gothememe.Hex("#00b100") }
func (t *themePhalaGreenDark) Yellow() gothememe.Color       { return gothememe.Hex("#a9a700") }
func (t *themePhalaGreenDark) Blue() gothememe.Color         { return gothememe.Hex("#0223c0") }
func (t *themePhalaGreenDark) Purple() gothememe.Color       { return gothememe.Hex("#c22ec0") }
func (t *themePhalaGreenDark) Cyan() gothememe.Color         { return gothememe.Hex("#00b4c0") }
func (t *themePhalaGreenDark) White() gothememe.Color        { return gothememe.Hex("#cbcbcb") }
func (t *themePhalaGreenDark) BrightBlack() gothememe.Color  { return gothememe.Hex("#797979") }
func (t *themePhalaGreenDark) BrightRed() gothememe.Color    { return gothememe.Hex("#ed2200") }
func (t *themePhalaGreenDark) BrightGreen() gothememe.Color  { return gothememe.Hex("#00db00") }
func (t *themePhalaGreenDark) BrightYellow() gothememe.Color { return gothememe.Hex("#eae700") }
func (t *themePhalaGreenDark) BrightBlue() gothememe.Color   { return gothememe.Hex("#0433ff") }
func (t *themePhalaGreenDark) BrightPurple() gothememe.Color { return gothememe.Hex("#ed3aea") }
func (t *themePhalaGreenDark) BrightCyan() gothememe.Color   { return gothememe.Hex("#00e8ea") }
func (t *themePhalaGreenDark) BrightWhite() gothememe.Color  { return gothememe.Hex("#eaeaea") }

// Code/Syntax highlighting colors
func (t *themePhalaGreenDark) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themePhalaGreenDark) CodeText() gothememe.Color        { return gothememe.Hex("#c1fc03") }
func (t *themePhalaGreenDark) CodeComment() gothememe.Color     { return gothememe.Hex("#797979") }
func (t *themePhalaGreenDark) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c22ec0") }
func (t *themePhalaGreenDark) CodeString() gothememe.Color      { return gothememe.Hex("#00b100") }
func (t *themePhalaGreenDark) CodeNumber() gothememe.Color      { return gothememe.Hex("#a9a700") }
func (t *themePhalaGreenDark) CodeFunction() gothememe.Color    { return gothememe.Hex("#0223c0") }
func (t *themePhalaGreenDark) CodeOperator() gothememe.Color    { return gothememe.Hex("#ab1500") }
func (t *themePhalaGreenDark) CodePunctuation() gothememe.Color { return gothememe.Hex("#c1fc03") }
func (t *themePhalaGreenDark) CodeVariable() gothememe.Color    { return gothememe.Hex("#00b4c0") }
func (t *themePhalaGreenDark) CodeConstant() gothememe.Color    { return gothememe.Hex("#eae700") }
func (t *themePhalaGreenDark) CodeType() gothememe.Color        { return gothememe.Hex("#00e8ea") }
