// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeSpacegrayBrightInstance is the Spacegray Bright color theme singleton.
var themeSpacegrayBrightInstance gothememe.Theme = &themeSpacegrayBright{}

// themeSpacegrayBright implements the Spacegray Bright theme.
type themeSpacegrayBright struct{}

func (t *themeSpacegrayBright) ID() string          { return "spacegray_bright" }
func (t *themeSpacegrayBright) DisplayName() string { return "Spacegray Bright" }
func (t *themeSpacegrayBright) Description() string { return "Spacegray Bright color theme" }
func (t *themeSpacegrayBright) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeSpacegrayBright) License() string     { return "MIT" }
func (t *themeSpacegrayBright) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeSpacegrayBright) IsDark() bool { return true }

// Background colors
func (t *themeSpacegrayBright) Background() gothememe.Color          { return gothememe.Hex("#2a2e3a") }
func (t *themeSpacegrayBright) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#080808") }
func (t *themeSpacegrayBright) Surface() gothememe.Color             { return gothememe.Hex("#cacaca") }
func (t *themeSpacegrayBright) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#626262") }

// Text colors
func (t *themeSpacegrayBright) TextPrimary() gothememe.Color   { return gothememe.Hex("#f3f3f3") }
func (t *themeSpacegrayBright) TextSecondary() gothememe.Color { return gothememe.Hex("#d8d8d8") }
func (t *themeSpacegrayBright) TextMuted() gothememe.Color     { return gothememe.Hex("#626262") }
func (t *themeSpacegrayBright) TextInverted() gothememe.Color  { return gothememe.Hex("#2a2e3a") }

// Accent/Brand colors
func (t *themeSpacegrayBright) Accent() gothememe.Color          { return gothememe.Hex("#7baec1") }
func (t *themeSpacegrayBright) AccentSecondary() gothememe.Color { return gothememe.Hex("#b98aae") }
func (t *themeSpacegrayBright) Brand() gothememe.Color           { return gothememe.Hex("#7baec1") }

// Border colors
func (t *themeSpacegrayBright) Border() gothememe.Color       { return gothememe.Hex("#626262") }
func (t *themeSpacegrayBright) BorderSubtle() gothememe.Color { return gothememe.Hex("#080808") }
func (t *themeSpacegrayBright) BorderStrong() gothememe.Color { return gothememe.Hex("#d8d8d8") }

// Semantic colors
func (t *themeSpacegrayBright) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a0b56c").WithAlpha(0.1),
		Border:     gothememe.Hex("#a0b56c").WithAlpha(0.3),
		Text:       gothememe.Hex("#a0b56c"),
	}
}

func (t *themeSpacegrayBright) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f6c987").WithAlpha(0.1),
		Border:     gothememe.Hex("#f6c987").WithAlpha(0.3),
		Text:       gothememe.Hex("#f6c987"),
	}
}

func (t *themeSpacegrayBright) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#bc5553").WithAlpha(0.1),
		Border:     gothememe.Hex("#bc5553").WithAlpha(0.3),
		Text:       gothememe.Hex("#bc5553"),
	}
}

func (t *themeSpacegrayBright) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#85c9b8").WithAlpha(0.1),
		Border:     gothememe.Hex("#85c9b8").WithAlpha(0.3),
		Text:       gothememe.Hex("#85c9b8"),
	}
}

// ANSI colors
func (t *themeSpacegrayBright) Black() gothememe.Color        { return gothememe.Hex("#080808") }
func (t *themeSpacegrayBright) Red() gothememe.Color          { return gothememe.Hex("#bc5553") }
func (t *themeSpacegrayBright) Green() gothememe.Color        { return gothememe.Hex("#a0b56c") }
func (t *themeSpacegrayBright) Yellow() gothememe.Color       { return gothememe.Hex("#f6c987") }
func (t *themeSpacegrayBright) Blue() gothememe.Color         { return gothememe.Hex("#7baec1") }
func (t *themeSpacegrayBright) Purple() gothememe.Color       { return gothememe.Hex("#b98aae") }
func (t *themeSpacegrayBright) Cyan() gothememe.Color         { return gothememe.Hex("#85c9b8") }
func (t *themeSpacegrayBright) White() gothememe.Color        { return gothememe.Hex("#d8d8d8") }
func (t *themeSpacegrayBright) BrightBlack() gothememe.Color  { return gothememe.Hex("#626262") }
func (t *themeSpacegrayBright) BrightRed() gothememe.Color    { return gothememe.Hex("#bc5553") }
func (t *themeSpacegrayBright) BrightGreen() gothememe.Color  { return gothememe.Hex("#a0b56c") }
func (t *themeSpacegrayBright) BrightYellow() gothememe.Color { return gothememe.Hex("#f6c987") }
func (t *themeSpacegrayBright) BrightBlue() gothememe.Color   { return gothememe.Hex("#7baec1") }
func (t *themeSpacegrayBright) BrightPurple() gothememe.Color { return gothememe.Hex("#b98aae") }
func (t *themeSpacegrayBright) BrightCyan() gothememe.Color   { return gothememe.Hex("#85c9b8") }
func (t *themeSpacegrayBright) BrightWhite() gothememe.Color  { return gothememe.Hex("#f7f7f7") }

// Code/Syntax highlighting colors
func (t *themeSpacegrayBright) CodeBackground() gothememe.Color  { return gothememe.Hex("#2a2e3a") }
func (t *themeSpacegrayBright) CodeText() gothememe.Color        { return gothememe.Hex("#f3f3f3") }
func (t *themeSpacegrayBright) CodeComment() gothememe.Color     { return gothememe.Hex("#626262") }
func (t *themeSpacegrayBright) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b98aae") }
func (t *themeSpacegrayBright) CodeString() gothememe.Color      { return gothememe.Hex("#a0b56c") }
func (t *themeSpacegrayBright) CodeNumber() gothememe.Color      { return gothememe.Hex("#f6c987") }
func (t *themeSpacegrayBright) CodeFunction() gothememe.Color    { return gothememe.Hex("#7baec1") }
func (t *themeSpacegrayBright) CodeOperator() gothememe.Color    { return gothememe.Hex("#bc5553") }
func (t *themeSpacegrayBright) CodePunctuation() gothememe.Color { return gothememe.Hex("#f3f3f3") }
func (t *themeSpacegrayBright) CodeVariable() gothememe.Color    { return gothememe.Hex("#85c9b8") }
func (t *themeSpacegrayBright) CodeConstant() gothememe.Color    { return gothememe.Hex("#f6c987") }
func (t *themeSpacegrayBright) CodeType() gothememe.Color        { return gothememe.Hex("#85c9b8") }
