// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeDoomOneInstance is the Doom One color theme singleton.
var themeDoomOneInstance gothememe.Theme = &themeDoomOne{}

// themeDoomOne implements the Doom One theme.
type themeDoomOne struct{}

func (t *themeDoomOne) ID() string          { return "doom_one" }
func (t *themeDoomOne) DisplayName() string { return "Doom One" }
func (t *themeDoomOne) Description() string { return "Doom One color theme" }
func (t *themeDoomOne) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeDoomOne) License() string     { return "MIT" }
func (t *themeDoomOne) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeDoomOne) IsDark() bool        { return true }

// Background colors
func (t *themeDoomOne) Background() gothememe.Color          { return gothememe.Hex("#282c34") }
func (t *themeDoomOne) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeDoomOne) Surface() gothememe.Color             { return gothememe.Hex("#42444b") }
func (t *themeDoomOne) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#595959") }

// Text colors
func (t *themeDoomOne) TextPrimary() gothememe.Color   { return gothememe.Hex("#bbc2cf") }
func (t *themeDoomOne) TextSecondary() gothememe.Color { return gothememe.Hex("#bbc2cf") }
func (t *themeDoomOne) TextMuted() gothememe.Color     { return gothememe.Hex("#595959") }
func (t *themeDoomOne) TextInverted() gothememe.Color  { return gothememe.Hex("#282c34") }

// Accent/Brand colors
func (t *themeDoomOne) Accent() gothememe.Color          { return gothememe.Hex("#a9a1e1") }
func (t *themeDoomOne) AccentSecondary() gothememe.Color { return gothememe.Hex("#c678dd") }
func (t *themeDoomOne) Brand() gothememe.Color           { return gothememe.Hex("#a9a1e1") }

// Border colors
func (t *themeDoomOne) Border() gothememe.Color       { return gothememe.Hex("#595959") }
func (t *themeDoomOne) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeDoomOne) BorderStrong() gothememe.Color { return gothememe.Hex("#bbc2cf") }

// Semantic colors
func (t *themeDoomOne) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#98be65").WithAlpha(0.1),
		Border:     gothememe.Hex("#98be65").WithAlpha(0.3),
		Text:       gothememe.Hex("#98be65"),
	}
}

func (t *themeDoomOne) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ecbe7b").WithAlpha(0.1),
		Border:     gothememe.Hex("#ecbe7b").WithAlpha(0.3),
		Text:       gothememe.Hex("#ecbe7b"),
	}
}

func (t *themeDoomOne) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff6c6b").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff6c6b").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff6c6b"),
	}
}

func (t *themeDoomOne) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#51afef").WithAlpha(0.1),
		Border:     gothememe.Hex("#51afef").WithAlpha(0.3),
		Text:       gothememe.Hex("#51afef"),
	}
}

// ANSI colors
func (t *themeDoomOne) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeDoomOne) Red() gothememe.Color          { return gothememe.Hex("#ff6c6b") }
func (t *themeDoomOne) Green() gothememe.Color        { return gothememe.Hex("#98be65") }
func (t *themeDoomOne) Yellow() gothememe.Color       { return gothememe.Hex("#ecbe7b") }
func (t *themeDoomOne) Blue() gothememe.Color         { return gothememe.Hex("#a9a1e1") }
func (t *themeDoomOne) Purple() gothememe.Color       { return gothememe.Hex("#c678dd") }
func (t *themeDoomOne) Cyan() gothememe.Color         { return gothememe.Hex("#51afef") }
func (t *themeDoomOne) White() gothememe.Color        { return gothememe.Hex("#bbc2cf") }
func (t *themeDoomOne) BrightBlack() gothememe.Color  { return gothememe.Hex("#595959") }
func (t *themeDoomOne) BrightRed() gothememe.Color    { return gothememe.Hex("#ff6655") }
func (t *themeDoomOne) BrightGreen() gothememe.Color  { return gothememe.Hex("#99bb66") }
func (t *themeDoomOne) BrightYellow() gothememe.Color { return gothememe.Hex("#ecbe7b") }
func (t *themeDoomOne) BrightBlue() gothememe.Color   { return gothememe.Hex("#a9a1e1") }
func (t *themeDoomOne) BrightPurple() gothememe.Color { return gothememe.Hex("#c678dd") }
func (t *themeDoomOne) BrightCyan() gothememe.Color   { return gothememe.Hex("#51afef") }
func (t *themeDoomOne) BrightWhite() gothememe.Color  { return gothememe.Hex("#bfbfbf") }

// Code/Syntax highlighting colors
func (t *themeDoomOne) CodeBackground() gothememe.Color  { return gothememe.Hex("#282c34") }
func (t *themeDoomOne) CodeText() gothememe.Color        { return gothememe.Hex("#bbc2cf") }
func (t *themeDoomOne) CodeComment() gothememe.Color     { return gothememe.Hex("#595959") }
func (t *themeDoomOne) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c678dd") }
func (t *themeDoomOne) CodeString() gothememe.Color      { return gothememe.Hex("#98be65") }
func (t *themeDoomOne) CodeNumber() gothememe.Color      { return gothememe.Hex("#ecbe7b") }
func (t *themeDoomOne) CodeFunction() gothememe.Color    { return gothememe.Hex("#a9a1e1") }
func (t *themeDoomOne) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff6c6b") }
func (t *themeDoomOne) CodePunctuation() gothememe.Color { return gothememe.Hex("#bbc2cf") }
func (t *themeDoomOne) CodeVariable() gothememe.Color    { return gothememe.Hex("#51afef") }
func (t *themeDoomOne) CodeConstant() gothememe.Color    { return gothememe.Hex("#ecbe7b") }
func (t *themeDoomOne) CodeType() gothememe.Color        { return gothememe.Hex("#51afef") }
