// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeBlueMatrixInstance is the Blue Matrix color theme singleton.
var themeBlueMatrixInstance gothememe.Theme = &themeBlueMatrix{}

// themeBlueMatrix implements the Blue Matrix theme.
type themeBlueMatrix struct{}

func (t *themeBlueMatrix) ID() string          { return "blue_matrix" }
func (t *themeBlueMatrix) DisplayName() string { return "Blue Matrix" }
func (t *themeBlueMatrix) Description() string { return "Blue Matrix color theme" }
func (t *themeBlueMatrix) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeBlueMatrix) License() string     { return "MIT" }
func (t *themeBlueMatrix) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeBlueMatrix) IsDark() bool        { return true }

// Background colors
func (t *themeBlueMatrix) Background() gothememe.Color          { return gothememe.Hex("#101116") }
func (t *themeBlueMatrix) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#101116") }
func (t *themeBlueMatrix) Surface() gothememe.Color             { return gothememe.Hex("#c1deff") }
func (t *themeBlueMatrix) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#686868") }

// Text colors
func (t *themeBlueMatrix) TextPrimary() gothememe.Color   { return gothememe.Hex("#00a2ff") }
func (t *themeBlueMatrix) TextSecondary() gothememe.Color { return gothememe.Hex("#c7c7c7") }
func (t *themeBlueMatrix) TextMuted() gothememe.Color     { return gothememe.Hex("#686868") }
func (t *themeBlueMatrix) TextInverted() gothememe.Color  { return gothememe.Hex("#101116") }

// Accent/Brand colors
func (t *themeBlueMatrix) Accent() gothememe.Color          { return gothememe.Hex("#00b0ff") }
func (t *themeBlueMatrix) AccentSecondary() gothememe.Color { return gothememe.Hex("#d57bff") }
func (t *themeBlueMatrix) Brand() gothememe.Color           { return gothememe.Hex("#00b0ff") }

// Border colors
func (t *themeBlueMatrix) Border() gothememe.Color       { return gothememe.Hex("#686868") }
func (t *themeBlueMatrix) BorderSubtle() gothememe.Color { return gothememe.Hex("#101116") }
func (t *themeBlueMatrix) BorderStrong() gothememe.Color { return gothememe.Hex("#c7c7c7") }

// Semantic colors
func (t *themeBlueMatrix) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00ff9c").WithAlpha(0.1),
		Border:     gothememe.Hex("#00ff9c").WithAlpha(0.3),
		Text:       gothememe.Hex("#00ff9c"),
	}
}

func (t *themeBlueMatrix) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fffc58").WithAlpha(0.1),
		Border:     gothememe.Hex("#fffc58").WithAlpha(0.3),
		Text:       gothememe.Hex("#fffc58"),
	}
}

func (t *themeBlueMatrix) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff5680").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff5680").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff5680"),
	}
}

func (t *themeBlueMatrix) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#76c1ff").WithAlpha(0.1),
		Border:     gothememe.Hex("#76c1ff").WithAlpha(0.3),
		Text:       gothememe.Hex("#76c1ff"),
	}
}

// ANSI colors
func (t *themeBlueMatrix) Black() gothememe.Color        { return gothememe.Hex("#101116") }
func (t *themeBlueMatrix) Red() gothememe.Color          { return gothememe.Hex("#ff5680") }
func (t *themeBlueMatrix) Green() gothememe.Color        { return gothememe.Hex("#00ff9c") }
func (t *themeBlueMatrix) Yellow() gothememe.Color       { return gothememe.Hex("#fffc58") }
func (t *themeBlueMatrix) Blue() gothememe.Color         { return gothememe.Hex("#00b0ff") }
func (t *themeBlueMatrix) Purple() gothememe.Color       { return gothememe.Hex("#d57bff") }
func (t *themeBlueMatrix) Cyan() gothememe.Color         { return gothememe.Hex("#76c1ff") }
func (t *themeBlueMatrix) White() gothememe.Color        { return gothememe.Hex("#c7c7c7") }
func (t *themeBlueMatrix) BrightBlack() gothememe.Color  { return gothememe.Hex("#686868") }
func (t *themeBlueMatrix) BrightRed() gothememe.Color    { return gothememe.Hex("#ff6e67") }
func (t *themeBlueMatrix) BrightGreen() gothememe.Color  { return gothememe.Hex("#5ffa68") }
func (t *themeBlueMatrix) BrightYellow() gothememe.Color { return gothememe.Hex("#fffc67") }
func (t *themeBlueMatrix) BrightBlue() gothememe.Color   { return gothememe.Hex("#6871ff") }
func (t *themeBlueMatrix) BrightPurple() gothememe.Color { return gothememe.Hex("#d682ec") }
func (t *themeBlueMatrix) BrightCyan() gothememe.Color   { return gothememe.Hex("#60fdff") }
func (t *themeBlueMatrix) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeBlueMatrix) CodeBackground() gothememe.Color  { return gothememe.Hex("#101116") }
func (t *themeBlueMatrix) CodeText() gothememe.Color        { return gothememe.Hex("#00a2ff") }
func (t *themeBlueMatrix) CodeComment() gothememe.Color     { return gothememe.Hex("#686868") }
func (t *themeBlueMatrix) CodeKeyword() gothememe.Color     { return gothememe.Hex("#d57bff") }
func (t *themeBlueMatrix) CodeString() gothememe.Color      { return gothememe.Hex("#00ff9c") }
func (t *themeBlueMatrix) CodeNumber() gothememe.Color      { return gothememe.Hex("#fffc58") }
func (t *themeBlueMatrix) CodeFunction() gothememe.Color    { return gothememe.Hex("#00b0ff") }
func (t *themeBlueMatrix) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff5680") }
func (t *themeBlueMatrix) CodePunctuation() gothememe.Color { return gothememe.Hex("#00a2ff") }
func (t *themeBlueMatrix) CodeVariable() gothememe.Color    { return gothememe.Hex("#76c1ff") }
func (t *themeBlueMatrix) CodeConstant() gothememe.Color    { return gothememe.Hex("#fffc67") }
func (t *themeBlueMatrix) CodeType() gothememe.Color        { return gothememe.Hex("#60fdff") }
