// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeGalaxyInstance is the Galaxy color theme singleton.
var themeGalaxyInstance gothememe.Theme = &themeGalaxy{}

// themeGalaxy implements the Galaxy theme.
type themeGalaxy struct{}

func (t *themeGalaxy) ID() string          { return "galaxy" }
func (t *themeGalaxy) DisplayName() string { return "Galaxy" }
func (t *themeGalaxy) Description() string { return "Galaxy color theme" }
func (t *themeGalaxy) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeGalaxy) License() string     { return "MIT" }
func (t *themeGalaxy) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeGalaxy) IsDark() bool        { return true }

// Background colors
func (t *themeGalaxy) Background() gothememe.Color          { return gothememe.Hex("#1d2837") }
func (t *themeGalaxy) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeGalaxy) Surface() gothememe.Color             { return gothememe.Hex("#b5d5ff") }
func (t *themeGalaxy) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#555555") }

// Text colors
func (t *themeGalaxy) TextPrimary() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeGalaxy) TextSecondary() gothememe.Color { return gothememe.Hex("#bbbbbb") }
func (t *themeGalaxy) TextMuted() gothememe.Color     { return gothememe.Hex("#555555") }
func (t *themeGalaxy) TextInverted() gothememe.Color  { return gothememe.Hex("#1d2837") }

// Accent/Brand colors
func (t *themeGalaxy) Accent() gothememe.Color          { return gothememe.Hex("#589df6") }
func (t *themeGalaxy) AccentSecondary() gothememe.Color { return gothememe.Hex("#944d95") }
func (t *themeGalaxy) Brand() gothememe.Color           { return gothememe.Hex("#589df6") }

// Border colors
func (t *themeGalaxy) Border() gothememe.Color       { return gothememe.Hex("#555555") }
func (t *themeGalaxy) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeGalaxy) BorderStrong() gothememe.Color { return gothememe.Hex("#bbbbbb") }

// Semantic colors
func (t *themeGalaxy) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#21b089").WithAlpha(0.1),
		Border:     gothememe.Hex("#21b089").WithAlpha(0.3),
		Text:       gothememe.Hex("#21b089"),
	}
}

func (t *themeGalaxy) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fef02a").WithAlpha(0.1),
		Border:     gothememe.Hex("#fef02a").WithAlpha(0.3),
		Text:       gothememe.Hex("#fef02a"),
	}
}

func (t *themeGalaxy) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f9555f").WithAlpha(0.1),
		Border:     gothememe.Hex("#f9555f").WithAlpha(0.3),
		Text:       gothememe.Hex("#f9555f"),
	}
}

func (t *themeGalaxy) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1f9ee7").WithAlpha(0.1),
		Border:     gothememe.Hex("#1f9ee7").WithAlpha(0.3),
		Text:       gothememe.Hex("#1f9ee7"),
	}
}

// ANSI colors
func (t *themeGalaxy) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeGalaxy) Red() gothememe.Color          { return gothememe.Hex("#f9555f") }
func (t *themeGalaxy) Green() gothememe.Color        { return gothememe.Hex("#21b089") }
func (t *themeGalaxy) Yellow() gothememe.Color       { return gothememe.Hex("#fef02a") }
func (t *themeGalaxy) Blue() gothememe.Color         { return gothememe.Hex("#589df6") }
func (t *themeGalaxy) Purple() gothememe.Color       { return gothememe.Hex("#944d95") }
func (t *themeGalaxy) Cyan() gothememe.Color         { return gothememe.Hex("#1f9ee7") }
func (t *themeGalaxy) White() gothememe.Color        { return gothememe.Hex("#bbbbbb") }
func (t *themeGalaxy) BrightBlack() gothememe.Color  { return gothememe.Hex("#555555") }
func (t *themeGalaxy) BrightRed() gothememe.Color    { return gothememe.Hex("#fa8c8f") }
func (t *themeGalaxy) BrightGreen() gothememe.Color  { return gothememe.Hex("#35bb9a") }
func (t *themeGalaxy) BrightYellow() gothememe.Color { return gothememe.Hex("#ffff55") }
func (t *themeGalaxy) BrightBlue() gothememe.Color   { return gothememe.Hex("#589df6") }
func (t *themeGalaxy) BrightPurple() gothememe.Color { return gothememe.Hex("#e75699") }
func (t *themeGalaxy) BrightCyan() gothememe.Color   { return gothememe.Hex("#3979bc") }
func (t *themeGalaxy) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeGalaxy) CodeBackground() gothememe.Color  { return gothememe.Hex("#1d2837") }
func (t *themeGalaxy) CodeText() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeGalaxy) CodeComment() gothememe.Color     { return gothememe.Hex("#555555") }
func (t *themeGalaxy) CodeKeyword() gothememe.Color     { return gothememe.Hex("#944d95") }
func (t *themeGalaxy) CodeString() gothememe.Color      { return gothememe.Hex("#21b089") }
func (t *themeGalaxy) CodeNumber() gothememe.Color      { return gothememe.Hex("#fef02a") }
func (t *themeGalaxy) CodeFunction() gothememe.Color    { return gothememe.Hex("#589df6") }
func (t *themeGalaxy) CodeOperator() gothememe.Color    { return gothememe.Hex("#f9555f") }
func (t *themeGalaxy) CodePunctuation() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeGalaxy) CodeVariable() gothememe.Color    { return gothememe.Hex("#1f9ee7") }
func (t *themeGalaxy) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffff55") }
func (t *themeGalaxy) CodeType() gothememe.Color        { return gothememe.Hex("#3979bc") }
