// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeTerminalBasicInstance is the Terminal Basic color theme singleton.
var themeTerminalBasicInstance gothememe.Theme = &themeTerminalBasic{}

// themeTerminalBasic implements the Terminal Basic theme.
type themeTerminalBasic struct{}

func (t *themeTerminalBasic) ID() string          { return "terminal_basic" }
func (t *themeTerminalBasic) DisplayName() string { return "Terminal Basic" }
func (t *themeTerminalBasic) Description() string { return "Terminal Basic color theme" }
func (t *themeTerminalBasic) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeTerminalBasic) License() string     { return "MIT" }
func (t *themeTerminalBasic) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeTerminalBasic) IsDark() bool { return false }

// Background colors
func (t *themeTerminalBasic) Background() gothememe.Color          { return gothememe.Hex("#ffffff") }
func (t *themeTerminalBasic) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeTerminalBasic) Surface() gothememe.Color             { return gothememe.Hex("#a4c9ff") }
func (t *themeTerminalBasic) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#666666") }

// Text colors
func (t *themeTerminalBasic) TextPrimary() gothememe.Color   { return gothememe.Hex("#000000") }
func (t *themeTerminalBasic) TextSecondary() gothememe.Color { return gothememe.Hex("#bfbfbf") }
func (t *themeTerminalBasic) TextMuted() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeTerminalBasic) TextInverted() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Accent/Brand colors
func (t *themeTerminalBasic) Accent() gothememe.Color          { return gothememe.Hex("#0000b2") }
func (t *themeTerminalBasic) AccentSecondary() gothememe.Color { return gothememe.Hex("#b200b2") }
func (t *themeTerminalBasic) Brand() gothememe.Color           { return gothememe.Hex("#0000b2") }

// Border colors
func (t *themeTerminalBasic) Border() gothememe.Color       { return gothememe.Hex("#666666") }
func (t *themeTerminalBasic) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeTerminalBasic) BorderStrong() gothememe.Color { return gothememe.Hex("#bfbfbf") }

// Semantic colors
func (t *themeTerminalBasic) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00a600").WithAlpha(0.1),
		Border:     gothememe.Hex("#00a600").WithAlpha(0.3),
		Text:       gothememe.Hex("#00a600"),
	}
}

func (t *themeTerminalBasic) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#999900").WithAlpha(0.1),
		Border:     gothememe.Hex("#999900").WithAlpha(0.3),
		Text:       gothememe.Hex("#999900"),
	}
}

func (t *themeTerminalBasic) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#990000").WithAlpha(0.1),
		Border:     gothememe.Hex("#990000").WithAlpha(0.3),
		Text:       gothememe.Hex("#990000"),
	}
}

func (t *themeTerminalBasic) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00a6b2").WithAlpha(0.1),
		Border:     gothememe.Hex("#00a6b2").WithAlpha(0.3),
		Text:       gothememe.Hex("#00a6b2"),
	}
}

// ANSI colors
func (t *themeTerminalBasic) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeTerminalBasic) Red() gothememe.Color          { return gothememe.Hex("#990000") }
func (t *themeTerminalBasic) Green() gothememe.Color        { return gothememe.Hex("#00a600") }
func (t *themeTerminalBasic) Yellow() gothememe.Color       { return gothememe.Hex("#999900") }
func (t *themeTerminalBasic) Blue() gothememe.Color         { return gothememe.Hex("#0000b2") }
func (t *themeTerminalBasic) Purple() gothememe.Color       { return gothememe.Hex("#b200b2") }
func (t *themeTerminalBasic) Cyan() gothememe.Color         { return gothememe.Hex("#00a6b2") }
func (t *themeTerminalBasic) White() gothememe.Color        { return gothememe.Hex("#bfbfbf") }
func (t *themeTerminalBasic) BrightBlack() gothememe.Color  { return gothememe.Hex("#666666") }
func (t *themeTerminalBasic) BrightRed() gothememe.Color    { return gothememe.Hex("#e50000") }
func (t *themeTerminalBasic) BrightGreen() gothememe.Color  { return gothememe.Hex("#00d900") }
func (t *themeTerminalBasic) BrightYellow() gothememe.Color { return gothememe.Hex("#bfbf00") }
func (t *themeTerminalBasic) BrightBlue() gothememe.Color   { return gothememe.Hex("#0000ff") }
func (t *themeTerminalBasic) BrightPurple() gothememe.Color { return gothememe.Hex("#e500e5") }
func (t *themeTerminalBasic) BrightCyan() gothememe.Color   { return gothememe.Hex("#00d8d8") }
func (t *themeTerminalBasic) BrightWhite() gothememe.Color  { return gothememe.Hex("#e5e5e5") }

// Code/Syntax highlighting colors
func (t *themeTerminalBasic) CodeBackground() gothememe.Color  { return gothememe.Hex("#ffffff") }
func (t *themeTerminalBasic) CodeText() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeTerminalBasic) CodeComment() gothememe.Color     { return gothememe.Hex("#666666") }
func (t *themeTerminalBasic) CodeKeyword() gothememe.Color     { return gothememe.Hex("#b200b2") }
func (t *themeTerminalBasic) CodeString() gothememe.Color      { return gothememe.Hex("#00a600") }
func (t *themeTerminalBasic) CodeNumber() gothememe.Color      { return gothememe.Hex("#999900") }
func (t *themeTerminalBasic) CodeFunction() gothememe.Color    { return gothememe.Hex("#0000b2") }
func (t *themeTerminalBasic) CodeOperator() gothememe.Color    { return gothememe.Hex("#990000") }
func (t *themeTerminalBasic) CodePunctuation() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeTerminalBasic) CodeVariable() gothememe.Color    { return gothememe.Hex("#00a6b2") }
func (t *themeTerminalBasic) CodeConstant() gothememe.Color    { return gothememe.Hex("#bfbf00") }
func (t *themeTerminalBasic) CodeType() gothememe.Color        { return gothememe.Hex("#00d8d8") }
