// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeDarkModernInstance is the Dark Modern color theme singleton.
var themeDarkModernInstance gothememe.Theme = &themeDarkModern{}

// themeDarkModern implements the Dark Modern theme.
type themeDarkModern struct{}

func (t *themeDarkModern) ID() string          { return "dark_modern" }
func (t *themeDarkModern) DisplayName() string { return "Dark Modern" }
func (t *themeDarkModern) Description() string { return "Dark Modern color theme" }
func (t *themeDarkModern) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeDarkModern) License() string     { return "MIT" }
func (t *themeDarkModern) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeDarkModern) IsDark() bool        { return true }

// Background colors
func (t *themeDarkModern) Background() gothememe.Color          { return gothememe.Hex("#1f1f1f") }
func (t *themeDarkModern) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#272727") }
func (t *themeDarkModern) Surface() gothememe.Color             { return gothememe.Hex("#3a3d41") }
func (t *themeDarkModern) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#5d5d5d") }

// Text colors
func (t *themeDarkModern) TextPrimary() gothememe.Color   { return gothememe.Hex("#cccccc") }
func (t *themeDarkModern) TextSecondary() gothememe.Color { return gothememe.Hex("#cccccc") }
func (t *themeDarkModern) TextMuted() gothememe.Color     { return gothememe.Hex("#5d5d5d") }
func (t *themeDarkModern) TextInverted() gothememe.Color  { return gothememe.Hex("#1f1f1f") }

// Accent/Brand colors
func (t *themeDarkModern) Accent() gothememe.Color          { return gothememe.Hex("#0078d4") }
func (t *themeDarkModern) AccentSecondary() gothememe.Color { return gothememe.Hex("#d01273") }
func (t *themeDarkModern) Brand() gothememe.Color           { return gothememe.Hex("#0078d4") }

// Border colors
func (t *themeDarkModern) Border() gothememe.Color       { return gothememe.Hex("#5d5d5d") }
func (t *themeDarkModern) BorderSubtle() gothememe.Color { return gothememe.Hex("#272727") }
func (t *themeDarkModern) BorderStrong() gothememe.Color { return gothememe.Hex("#cccccc") }

// Semantic colors
func (t *themeDarkModern) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#2ea043").WithAlpha(0.1),
		Border:     gothememe.Hex("#2ea043").WithAlpha(0.3),
		Text:       gothememe.Hex("#2ea043"),
	}
}

func (t *themeDarkModern) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#9e6a03").WithAlpha(0.1),
		Border:     gothememe.Hex("#9e6a03").WithAlpha(0.3),
		Text:       gothememe.Hex("#9e6a03"),
	}
}

func (t *themeDarkModern) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f74949").WithAlpha(0.1),
		Border:     gothememe.Hex("#f74949").WithAlpha(0.3),
		Text:       gothememe.Hex("#f74949"),
	}
}

func (t *themeDarkModern) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1db4d6").WithAlpha(0.1),
		Border:     gothememe.Hex("#1db4d6").WithAlpha(0.3),
		Text:       gothememe.Hex("#1db4d6"),
	}
}

// ANSI colors
func (t *themeDarkModern) Black() gothememe.Color        { return gothememe.Hex("#272727") }
func (t *themeDarkModern) Red() gothememe.Color          { return gothememe.Hex("#f74949") }
func (t *themeDarkModern) Green() gothememe.Color        { return gothememe.Hex("#2ea043") }
func (t *themeDarkModern) Yellow() gothememe.Color       { return gothememe.Hex("#9e6a03") }
func (t *themeDarkModern) Blue() gothememe.Color         { return gothememe.Hex("#0078d4") }
func (t *themeDarkModern) Purple() gothememe.Color       { return gothememe.Hex("#d01273") }
func (t *themeDarkModern) Cyan() gothememe.Color         { return gothememe.Hex("#1db4d6") }
func (t *themeDarkModern) White() gothememe.Color        { return gothememe.Hex("#cccccc") }
func (t *themeDarkModern) BrightBlack() gothememe.Color  { return gothememe.Hex("#5d5d5d") }
func (t *themeDarkModern) BrightRed() gothememe.Color    { return gothememe.Hex("#dc5452") }
func (t *themeDarkModern) BrightGreen() gothememe.Color  { return gothememe.Hex("#23d18b") }
func (t *themeDarkModern) BrightYellow() gothememe.Color { return gothememe.Hex("#f5f543") }
func (t *themeDarkModern) BrightBlue() gothememe.Color   { return gothememe.Hex("#3b8eea") }
func (t *themeDarkModern) BrightPurple() gothememe.Color { return gothememe.Hex("#d670d6") }
func (t *themeDarkModern) BrightCyan() gothememe.Color   { return gothememe.Hex("#29b8db") }
func (t *themeDarkModern) BrightWhite() gothememe.Color  { return gothememe.Hex("#e5e5e5") }

// Code/Syntax highlighting colors
func (t *themeDarkModern) CodeBackground() gothememe.Color  { return gothememe.Hex("#1f1f1f") }
func (t *themeDarkModern) CodeText() gothememe.Color        { return gothememe.Hex("#cccccc") }
func (t *themeDarkModern) CodeComment() gothememe.Color     { return gothememe.Hex("#5d5d5d") }
func (t *themeDarkModern) CodeKeyword() gothememe.Color     { return gothememe.Hex("#d01273") }
func (t *themeDarkModern) CodeString() gothememe.Color      { return gothememe.Hex("#2ea043") }
func (t *themeDarkModern) CodeNumber() gothememe.Color      { return gothememe.Hex("#9e6a03") }
func (t *themeDarkModern) CodeFunction() gothememe.Color    { return gothememe.Hex("#0078d4") }
func (t *themeDarkModern) CodeOperator() gothememe.Color    { return gothememe.Hex("#f74949") }
func (t *themeDarkModern) CodePunctuation() gothememe.Color { return gothememe.Hex("#cccccc") }
func (t *themeDarkModern) CodeVariable() gothememe.Color    { return gothememe.Hex("#1db4d6") }
func (t *themeDarkModern) CodeConstant() gothememe.Color    { return gothememe.Hex("#f5f543") }
func (t *themeDarkModern) CodeType() gothememe.Color        { return gothememe.Hex("#29b8db") }
