// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeCarbonfoxInstance is the Carbonfox color theme singleton.
var themeCarbonfoxInstance gothememe.Theme = &themeCarbonfox{}

// themeCarbonfox implements the Carbonfox theme.
type themeCarbonfox struct{}

func (t *themeCarbonfox) ID() string          { return "carbonfox" }
func (t *themeCarbonfox) DisplayName() string { return "Carbonfox" }
func (t *themeCarbonfox) Description() string { return "Carbonfox color theme" }
func (t *themeCarbonfox) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeCarbonfox) License() string     { return "MIT" }
func (t *themeCarbonfox) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeCarbonfox) IsDark() bool        { return true }

// Background colors
func (t *themeCarbonfox) Background() gothememe.Color          { return gothememe.Hex("#161616") }
func (t *themeCarbonfox) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#282828") }
func (t *themeCarbonfox) Surface() gothememe.Color             { return gothememe.Hex("#2a2a2a") }
func (t *themeCarbonfox) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#484848") }

// Text colors
func (t *themeCarbonfox) TextPrimary() gothememe.Color   { return gothememe.Hex("#f2f4f8") }
func (t *themeCarbonfox) TextSecondary() gothememe.Color { return gothememe.Hex("#dfdfe0") }
func (t *themeCarbonfox) TextMuted() gothememe.Color     { return gothememe.Hex("#484848") }
func (t *themeCarbonfox) TextInverted() gothememe.Color  { return gothememe.Hex("#161616") }

// Accent/Brand colors
func (t *themeCarbonfox) Accent() gothememe.Color          { return gothememe.Hex("#78a9ff") }
func (t *themeCarbonfox) AccentSecondary() gothememe.Color { return gothememe.Hex("#be95ff") }
func (t *themeCarbonfox) Brand() gothememe.Color           { return gothememe.Hex("#78a9ff") }

// Border colors
func (t *themeCarbonfox) Border() gothememe.Color       { return gothememe.Hex("#484848") }
func (t *themeCarbonfox) BorderSubtle() gothememe.Color { return gothememe.Hex("#282828") }
func (t *themeCarbonfox) BorderStrong() gothememe.Color { return gothememe.Hex("#dfdfe0") }

// Semantic colors
func (t *themeCarbonfox) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#25be6a").WithAlpha(0.1),
		Border:     gothememe.Hex("#25be6a").WithAlpha(0.3),
		Text:       gothememe.Hex("#25be6a"),
	}
}

func (t *themeCarbonfox) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#08bdba").WithAlpha(0.1),
		Border:     gothememe.Hex("#08bdba").WithAlpha(0.3),
		Text:       gothememe.Hex("#08bdba"),
	}
}

func (t *themeCarbonfox) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ee5396").WithAlpha(0.1),
		Border:     gothememe.Hex("#ee5396").WithAlpha(0.3),
		Text:       gothememe.Hex("#ee5396"),
	}
}

func (t *themeCarbonfox) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#33b1ff").WithAlpha(0.1),
		Border:     gothememe.Hex("#33b1ff").WithAlpha(0.3),
		Text:       gothememe.Hex("#33b1ff"),
	}
}

// ANSI colors
func (t *themeCarbonfox) Black() gothememe.Color        { return gothememe.Hex("#282828") }
func (t *themeCarbonfox) Red() gothememe.Color          { return gothememe.Hex("#ee5396") }
func (t *themeCarbonfox) Green() gothememe.Color        { return gothememe.Hex("#25be6a") }
func (t *themeCarbonfox) Yellow() gothememe.Color       { return gothememe.Hex("#08bdba") }
func (t *themeCarbonfox) Blue() gothememe.Color         { return gothememe.Hex("#78a9ff") }
func (t *themeCarbonfox) Purple() gothememe.Color       { return gothememe.Hex("#be95ff") }
func (t *themeCarbonfox) Cyan() gothememe.Color         { return gothememe.Hex("#33b1ff") }
func (t *themeCarbonfox) White() gothememe.Color        { return gothememe.Hex("#dfdfe0") }
func (t *themeCarbonfox) BrightBlack() gothememe.Color  { return gothememe.Hex("#484848") }
func (t *themeCarbonfox) BrightRed() gothememe.Color    { return gothememe.Hex("#f16da6") }
func (t *themeCarbonfox) BrightGreen() gothememe.Color  { return gothememe.Hex("#46c880") }
func (t *themeCarbonfox) BrightYellow() gothememe.Color { return gothememe.Hex("#2dc7c4") }
func (t *themeCarbonfox) BrightBlue() gothememe.Color   { return gothememe.Hex("#8cb6ff") }
func (t *themeCarbonfox) BrightPurple() gothememe.Color { return gothememe.Hex("#c8a5ff") }
func (t *themeCarbonfox) BrightCyan() gothememe.Color   { return gothememe.Hex("#52bdff") }
func (t *themeCarbonfox) BrightWhite() gothememe.Color  { return gothememe.Hex("#e4e4e5") }

// Code/Syntax highlighting colors
func (t *themeCarbonfox) CodeBackground() gothememe.Color  { return gothememe.Hex("#161616") }
func (t *themeCarbonfox) CodeText() gothememe.Color        { return gothememe.Hex("#f2f4f8") }
func (t *themeCarbonfox) CodeComment() gothememe.Color     { return gothememe.Hex("#484848") }
func (t *themeCarbonfox) CodeKeyword() gothememe.Color     { return gothememe.Hex("#be95ff") }
func (t *themeCarbonfox) CodeString() gothememe.Color      { return gothememe.Hex("#25be6a") }
func (t *themeCarbonfox) CodeNumber() gothememe.Color      { return gothememe.Hex("#08bdba") }
func (t *themeCarbonfox) CodeFunction() gothememe.Color    { return gothememe.Hex("#78a9ff") }
func (t *themeCarbonfox) CodeOperator() gothememe.Color    { return gothememe.Hex("#ee5396") }
func (t *themeCarbonfox) CodePunctuation() gothememe.Color { return gothememe.Hex("#f2f4f8") }
func (t *themeCarbonfox) CodeVariable() gothememe.Color    { return gothememe.Hex("#33b1ff") }
func (t *themeCarbonfox) CodeConstant() gothememe.Color    { return gothememe.Hex("#2dc7c4") }
func (t *themeCarbonfox) CodeType() gothememe.Color        { return gothememe.Hex("#52bdff") }
