// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themePnevmaInstance is the Pnevma color theme singleton.
var themePnevmaInstance gothememe.Theme = &themePnevma{}

// themePnevma implements the Pnevma theme.
type themePnevma struct{}

func (t *themePnevma) ID() string          { return "pnevma" }
func (t *themePnevma) DisplayName() string { return "Pnevma" }
func (t *themePnevma) Description() string { return "Pnevma color theme" }
func (t *themePnevma) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themePnevma) License() string     { return "MIT" }
func (t *themePnevma) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themePnevma) IsDark() bool        { return true }

// Background colors
func (t *themePnevma) Background() gothememe.Color          { return gothememe.Hex("#1c1c1c") }
func (t *themePnevma) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#2f2e2d") }
func (t *themePnevma) Surface() gothememe.Color             { return gothememe.Hex("#4d4d4d") }
func (t *themePnevma) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4a4845") }

// Text colors
func (t *themePnevma) TextPrimary() gothememe.Color   { return gothememe.Hex("#d0d0d0") }
func (t *themePnevma) TextSecondary() gothememe.Color { return gothememe.Hex("#d0d0d0") }
func (t *themePnevma) TextMuted() gothememe.Color     { return gothememe.Hex("#4a4845") }
func (t *themePnevma) TextInverted() gothememe.Color  { return gothememe.Hex("#1c1c1c") }

// Accent/Brand colors
func (t *themePnevma) Accent() gothememe.Color          { return gothememe.Hex("#7fa5bd") }
func (t *themePnevma) AccentSecondary() gothememe.Color { return gothememe.Hex("#c79ec4") }
func (t *themePnevma) Brand() gothememe.Color           { return gothememe.Hex("#7fa5bd") }

// Border colors
func (t *themePnevma) Border() gothememe.Color       { return gothememe.Hex("#4a4845") }
func (t *themePnevma) BorderSubtle() gothememe.Color { return gothememe.Hex("#2f2e2d") }
func (t *themePnevma) BorderStrong() gothememe.Color { return gothememe.Hex("#d0d0d0") }

// Semantic colors
func (t *themePnevma) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#90a57d").WithAlpha(0.1),
		Border:     gothememe.Hex("#90a57d").WithAlpha(0.3),
		Text:       gothememe.Hex("#90a57d"),
	}
}

func (t *themePnevma) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#d7af87").WithAlpha(0.1),
		Border:     gothememe.Hex("#d7af87").WithAlpha(0.3),
		Text:       gothememe.Hex("#d7af87"),
	}
}

func (t *themePnevma) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a36666").WithAlpha(0.1),
		Border:     gothememe.Hex("#a36666").WithAlpha(0.3),
		Text:       gothememe.Hex("#a36666"),
	}
}

func (t *themePnevma) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#8adbb4").WithAlpha(0.1),
		Border:     gothememe.Hex("#8adbb4").WithAlpha(0.3),
		Text:       gothememe.Hex("#8adbb4"),
	}
}

// ANSI colors
func (t *themePnevma) Black() gothememe.Color        { return gothememe.Hex("#2f2e2d") }
func (t *themePnevma) Red() gothememe.Color          { return gothememe.Hex("#a36666") }
func (t *themePnevma) Green() gothememe.Color        { return gothememe.Hex("#90a57d") }
func (t *themePnevma) Yellow() gothememe.Color       { return gothememe.Hex("#d7af87") }
func (t *themePnevma) Blue() gothememe.Color         { return gothememe.Hex("#7fa5bd") }
func (t *themePnevma) Purple() gothememe.Color       { return gothememe.Hex("#c79ec4") }
func (t *themePnevma) Cyan() gothememe.Color         { return gothememe.Hex("#8adbb4") }
func (t *themePnevma) White() gothememe.Color        { return gothememe.Hex("#d0d0d0") }
func (t *themePnevma) BrightBlack() gothememe.Color  { return gothememe.Hex("#4a4845") }
func (t *themePnevma) BrightRed() gothememe.Color    { return gothememe.Hex("#d78787") }
func (t *themePnevma) BrightGreen() gothememe.Color  { return gothememe.Hex("#afbea2") }
func (t *themePnevma) BrightYellow() gothememe.Color { return gothememe.Hex("#e4c9af") }
func (t *themePnevma) BrightBlue() gothememe.Color   { return gothememe.Hex("#a1bdce") }
func (t *themePnevma) BrightPurple() gothememe.Color { return gothememe.Hex("#d7beda") }
func (t *themePnevma) BrightCyan() gothememe.Color   { return gothememe.Hex("#b1e7dd") }
func (t *themePnevma) BrightWhite() gothememe.Color  { return gothememe.Hex("#efefef") }

// Code/Syntax highlighting colors
func (t *themePnevma) CodeBackground() gothememe.Color  { return gothememe.Hex("#1c1c1c") }
func (t *themePnevma) CodeText() gothememe.Color        { return gothememe.Hex("#d0d0d0") }
func (t *themePnevma) CodeComment() gothememe.Color     { return gothememe.Hex("#4a4845") }
func (t *themePnevma) CodeKeyword() gothememe.Color     { return gothememe.Hex("#c79ec4") }
func (t *themePnevma) CodeString() gothememe.Color      { return gothememe.Hex("#90a57d") }
func (t *themePnevma) CodeNumber() gothememe.Color      { return gothememe.Hex("#d7af87") }
func (t *themePnevma) CodeFunction() gothememe.Color    { return gothememe.Hex("#7fa5bd") }
func (t *themePnevma) CodeOperator() gothememe.Color    { return gothememe.Hex("#a36666") }
func (t *themePnevma) CodePunctuation() gothememe.Color { return gothememe.Hex("#d0d0d0") }
func (t *themePnevma) CodeVariable() gothememe.Color    { return gothememe.Hex("#8adbb4") }
func (t *themePnevma) CodeConstant() gothememe.Color    { return gothememe.Hex("#e4c9af") }
func (t *themePnevma) CodeType() gothememe.Color        { return gothememe.Hex("#b1e7dd") }
