// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeRaycastDarkInstance is the Raycast Dark color theme singleton.
var themeRaycastDarkInstance gothememe.Theme = &themeRaycastDark{}

// themeRaycastDark implements the Raycast Dark theme.
type themeRaycastDark struct{}

func (t *themeRaycastDark) ID() string          { return "raycast_dark" }
func (t *themeRaycastDark) DisplayName() string { return "Raycast Dark" }
func (t *themeRaycastDark) Description() string { return "Raycast Dark color theme" }
func (t *themeRaycastDark) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeRaycastDark) License() string     { return "MIT" }
func (t *themeRaycastDark) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeRaycastDark) IsDark() bool { return true }

// Background colors
func (t *themeRaycastDark) Background() gothememe.Color          { return gothememe.Hex("#1a1a1a") }
func (t *themeRaycastDark) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeRaycastDark) Surface() gothememe.Color             { return gothememe.Hex("#333333") }
func (t *themeRaycastDark) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#4c4c4c") }

// Text colors
func (t *themeRaycastDark) TextPrimary() gothememe.Color   { return gothememe.Hex("#ffffff") }
func (t *themeRaycastDark) TextSecondary() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeRaycastDark) TextMuted() gothememe.Color     { return gothememe.Hex("#4c4c4c") }
func (t *themeRaycastDark) TextInverted() gothememe.Color  { return gothememe.Hex("#1a1a1a") }

// Accent/Brand colors
func (t *themeRaycastDark) Accent() gothememe.Color          { return gothememe.Hex("#56c2ff") }
func (t *themeRaycastDark) AccentSecondary() gothememe.Color { return gothememe.Hex("#cf2f98") }
func (t *themeRaycastDark) Brand() gothememe.Color           { return gothememe.Hex("#56c2ff") }

// Border colors
func (t *themeRaycastDark) Border() gothememe.Color       { return gothememe.Hex("#4c4c4c") }
func (t *themeRaycastDark) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeRaycastDark) BorderStrong() gothememe.Color { return gothememe.Hex("#ffffff") }

// Semantic colors
func (t *themeRaycastDark) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#59d499").WithAlpha(0.1),
		Border:     gothememe.Hex("#59d499").WithAlpha(0.3),
		Text:       gothememe.Hex("#59d499"),
	}
}

func (t *themeRaycastDark) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ffc531").WithAlpha(0.1),
		Border:     gothememe.Hex("#ffc531").WithAlpha(0.3),
		Text:       gothememe.Hex("#ffc531"),
	}
}

func (t *themeRaycastDark) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ff5360").WithAlpha(0.1),
		Border:     gothememe.Hex("#ff5360").WithAlpha(0.3),
		Text:       gothememe.Hex("#ff5360"),
	}
}

func (t *themeRaycastDark) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#52eee5").WithAlpha(0.1),
		Border:     gothememe.Hex("#52eee5").WithAlpha(0.3),
		Text:       gothememe.Hex("#52eee5"),
	}
}

// ANSI colors
func (t *themeRaycastDark) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeRaycastDark) Red() gothememe.Color          { return gothememe.Hex("#ff5360") }
func (t *themeRaycastDark) Green() gothememe.Color        { return gothememe.Hex("#59d499") }
func (t *themeRaycastDark) Yellow() gothememe.Color       { return gothememe.Hex("#ffc531") }
func (t *themeRaycastDark) Blue() gothememe.Color         { return gothememe.Hex("#56c2ff") }
func (t *themeRaycastDark) Purple() gothememe.Color       { return gothememe.Hex("#cf2f98") }
func (t *themeRaycastDark) Cyan() gothememe.Color         { return gothememe.Hex("#52eee5") }
func (t *themeRaycastDark) White() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeRaycastDark) BrightBlack() gothememe.Color  { return gothememe.Hex("#4c4c4c") }
func (t *themeRaycastDark) BrightRed() gothememe.Color    { return gothememe.Hex("#ff6363") }
func (t *themeRaycastDark) BrightGreen() gothememe.Color  { return gothememe.Hex("#59d499") }
func (t *themeRaycastDark) BrightYellow() gothememe.Color { return gothememe.Hex("#ffc531") }
func (t *themeRaycastDark) BrightBlue() gothememe.Color   { return gothememe.Hex("#56c2ff") }
func (t *themeRaycastDark) BrightPurple() gothememe.Color { return gothememe.Hex("#cf2f98") }
func (t *themeRaycastDark) BrightCyan() gothememe.Color   { return gothememe.Hex("#52eee5") }
func (t *themeRaycastDark) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeRaycastDark) CodeBackground() gothememe.Color  { return gothememe.Hex("#1a1a1a") }
func (t *themeRaycastDark) CodeText() gothememe.Color        { return gothememe.Hex("#ffffff") }
func (t *themeRaycastDark) CodeComment() gothememe.Color     { return gothememe.Hex("#4c4c4c") }
func (t *themeRaycastDark) CodeKeyword() gothememe.Color     { return gothememe.Hex("#cf2f98") }
func (t *themeRaycastDark) CodeString() gothememe.Color      { return gothememe.Hex("#59d499") }
func (t *themeRaycastDark) CodeNumber() gothememe.Color      { return gothememe.Hex("#ffc531") }
func (t *themeRaycastDark) CodeFunction() gothememe.Color    { return gothememe.Hex("#56c2ff") }
func (t *themeRaycastDark) CodeOperator() gothememe.Color    { return gothememe.Hex("#ff5360") }
func (t *themeRaycastDark) CodePunctuation() gothememe.Color { return gothememe.Hex("#ffffff") }
func (t *themeRaycastDark) CodeVariable() gothememe.Color    { return gothememe.Hex("#52eee5") }
func (t *themeRaycastDark) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffc531") }
func (t *themeRaycastDark) CodeType() gothememe.Color        { return gothememe.Hex("#52eee5") }
