// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeMathiasInstance is the Mathias color theme singleton.
var themeMathiasInstance gothememe.Theme = &themeMathias{}

// themeMathias implements the Mathias theme.
type themeMathias struct{}

func (t *themeMathias) ID() string          { return "mathias" }
func (t *themeMathias) DisplayName() string { return "Mathias" }
func (t *themeMathias) Description() string { return "Mathias color theme" }
func (t *themeMathias) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeMathias) License() string     { return "MIT" }
func (t *themeMathias) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themeMathias) IsDark() bool        { return true }

// Background colors
func (t *themeMathias) Background() gothememe.Color          { return gothememe.Hex("#000000") }
func (t *themeMathias) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeMathias) Surface() gothememe.Color             { return gothememe.Hex("#555555") }
func (t *themeMathias) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#555555") }

// Text colors
func (t *themeMathias) TextPrimary() gothememe.Color   { return gothememe.Hex("#bbbbbb") }
func (t *themeMathias) TextSecondary() gothememe.Color { return gothememe.Hex("#f2f2f2") }
func (t *themeMathias) TextMuted() gothememe.Color     { return gothememe.Hex("#555555") }
func (t *themeMathias) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themeMathias) Accent() gothememe.Color          { return gothememe.Hex("#c48dff") }
func (t *themeMathias) AccentSecondary() gothememe.Color { return gothememe.Hex("#fa2573") }
func (t *themeMathias) Brand() gothememe.Color           { return gothememe.Hex("#c48dff") }

// Border colors
func (t *themeMathias) Border() gothememe.Color       { return gothememe.Hex("#555555") }
func (t *themeMathias) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeMathias) BorderStrong() gothememe.Color { return gothememe.Hex("#f2f2f2") }

// Semantic colors
func (t *themeMathias) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#a6e32d").WithAlpha(0.1),
		Border:     gothememe.Hex("#a6e32d").WithAlpha(0.3),
		Text:       gothememe.Hex("#a6e32d"),
	}
}

func (t *themeMathias) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#fc951e").WithAlpha(0.1),
		Border:     gothememe.Hex("#fc951e").WithAlpha(0.3),
		Text:       gothememe.Hex("#fc951e"),
	}
}

func (t *themeMathias) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e52222").WithAlpha(0.1),
		Border:     gothememe.Hex("#e52222").WithAlpha(0.3),
		Text:       gothememe.Hex("#e52222"),
	}
}

func (t *themeMathias) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#67d9f0").WithAlpha(0.1),
		Border:     gothememe.Hex("#67d9f0").WithAlpha(0.3),
		Text:       gothememe.Hex("#67d9f0"),
	}
}

// ANSI colors
func (t *themeMathias) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeMathias) Red() gothememe.Color          { return gothememe.Hex("#e52222") }
func (t *themeMathias) Green() gothememe.Color        { return gothememe.Hex("#a6e32d") }
func (t *themeMathias) Yellow() gothememe.Color       { return gothememe.Hex("#fc951e") }
func (t *themeMathias) Blue() gothememe.Color         { return gothememe.Hex("#c48dff") }
func (t *themeMathias) Purple() gothememe.Color       { return gothememe.Hex("#fa2573") }
func (t *themeMathias) Cyan() gothememe.Color         { return gothememe.Hex("#67d9f0") }
func (t *themeMathias) White() gothememe.Color        { return gothememe.Hex("#f2f2f2") }
func (t *themeMathias) BrightBlack() gothememe.Color  { return gothememe.Hex("#555555") }
func (t *themeMathias) BrightRed() gothememe.Color    { return gothememe.Hex("#ff5555") }
func (t *themeMathias) BrightGreen() gothememe.Color  { return gothememe.Hex("#55ff55") }
func (t *themeMathias) BrightYellow() gothememe.Color { return gothememe.Hex("#ffff55") }
func (t *themeMathias) BrightBlue() gothememe.Color   { return gothememe.Hex("#5555ff") }
func (t *themeMathias) BrightPurple() gothememe.Color { return gothememe.Hex("#ff55ff") }
func (t *themeMathias) BrightCyan() gothememe.Color   { return gothememe.Hex("#55ffff") }
func (t *themeMathias) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeMathias) CodeBackground() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themeMathias) CodeText() gothememe.Color        { return gothememe.Hex("#bbbbbb") }
func (t *themeMathias) CodeComment() gothememe.Color     { return gothememe.Hex("#555555") }
func (t *themeMathias) CodeKeyword() gothememe.Color     { return gothememe.Hex("#fa2573") }
func (t *themeMathias) CodeString() gothememe.Color      { return gothememe.Hex("#a6e32d") }
func (t *themeMathias) CodeNumber() gothememe.Color      { return gothememe.Hex("#fc951e") }
func (t *themeMathias) CodeFunction() gothememe.Color    { return gothememe.Hex("#c48dff") }
func (t *themeMathias) CodeOperator() gothememe.Color    { return gothememe.Hex("#e52222") }
func (t *themeMathias) CodePunctuation() gothememe.Color { return gothememe.Hex("#bbbbbb") }
func (t *themeMathias) CodeVariable() gothememe.Color    { return gothememe.Hex("#67d9f0") }
func (t *themeMathias) CodeConstant() gothememe.Color    { return gothememe.Hex("#ffff55") }
func (t *themeMathias) CodeType() gothememe.Color        { return gothememe.Hex("#55ffff") }
