// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeMonokaiProLightInstance is the Monokai Pro Light color theme singleton.
var themeMonokaiProLightInstance gothememe.Theme = &themeMonokaiProLight{}

// themeMonokaiProLight implements the Monokai Pro Light theme.
type themeMonokaiProLight struct{}

func (t *themeMonokaiProLight) ID() string          { return "monokai_pro_light" }
func (t *themeMonokaiProLight) DisplayName() string { return "Monokai Pro Light" }
func (t *themeMonokaiProLight) Description() string { return "Monokai Pro Light color theme" }
func (t *themeMonokaiProLight) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeMonokaiProLight) License() string     { return "MIT" }
func (t *themeMonokaiProLight) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeMonokaiProLight) IsDark() bool { return false }

// Background colors
func (t *themeMonokaiProLight) Background() gothememe.Color          { return gothememe.Hex("#faf4f2") }
func (t *themeMonokaiProLight) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#faf4f2") }
func (t *themeMonokaiProLight) Surface() gothememe.Color             { return gothememe.Hex("#bfb9ba") }
func (t *themeMonokaiProLight) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#a59fa0") }

// Text colors
func (t *themeMonokaiProLight) TextPrimary() gothememe.Color   { return gothememe.Hex("#29242a") }
func (t *themeMonokaiProLight) TextSecondary() gothememe.Color { return gothememe.Hex("#29242a") }
func (t *themeMonokaiProLight) TextMuted() gothememe.Color     { return gothememe.Hex("#a59fa0") }
func (t *themeMonokaiProLight) TextInverted() gothememe.Color  { return gothememe.Hex("#faf4f2") }

// Accent/Brand colors
func (t *themeMonokaiProLight) Accent() gothememe.Color          { return gothememe.Hex("#e16032") }
func (t *themeMonokaiProLight) AccentSecondary() gothememe.Color { return gothememe.Hex("#7058be") }
func (t *themeMonokaiProLight) Brand() gothememe.Color           { return gothememe.Hex("#e16032") }

// Border colors
func (t *themeMonokaiProLight) Border() gothememe.Color       { return gothememe.Hex("#a59fa0") }
func (t *themeMonokaiProLight) BorderSubtle() gothememe.Color { return gothememe.Hex("#faf4f2") }
func (t *themeMonokaiProLight) BorderStrong() gothememe.Color { return gothememe.Hex("#29242a") }

// Semantic colors
func (t *themeMonokaiProLight) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#269d69").WithAlpha(0.1),
		Border:     gothememe.Hex("#269d69").WithAlpha(0.3),
		Text:       gothememe.Hex("#269d69"),
	}
}

func (t *themeMonokaiProLight) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#cc7a0a").WithAlpha(0.1),
		Border:     gothememe.Hex("#cc7a0a").WithAlpha(0.3),
		Text:       gothememe.Hex("#cc7a0a"),
	}
}

func (t *themeMonokaiProLight) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#e14775").WithAlpha(0.1),
		Border:     gothememe.Hex("#e14775").WithAlpha(0.3),
		Text:       gothememe.Hex("#e14775"),
	}
}

func (t *themeMonokaiProLight) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#1c8ca8").WithAlpha(0.1),
		Border:     gothememe.Hex("#1c8ca8").WithAlpha(0.3),
		Text:       gothememe.Hex("#1c8ca8"),
	}
}

// ANSI colors
func (t *themeMonokaiProLight) Black() gothememe.Color        { return gothememe.Hex("#faf4f2") }
func (t *themeMonokaiProLight) Red() gothememe.Color          { return gothememe.Hex("#e14775") }
func (t *themeMonokaiProLight) Green() gothememe.Color        { return gothememe.Hex("#269d69") }
func (t *themeMonokaiProLight) Yellow() gothememe.Color       { return gothememe.Hex("#cc7a0a") }
func (t *themeMonokaiProLight) Blue() gothememe.Color         { return gothememe.Hex("#e16032") }
func (t *themeMonokaiProLight) Purple() gothememe.Color       { return gothememe.Hex("#7058be") }
func (t *themeMonokaiProLight) Cyan() gothememe.Color         { return gothememe.Hex("#1c8ca8") }
func (t *themeMonokaiProLight) White() gothememe.Color        { return gothememe.Hex("#29242a") }
func (t *themeMonokaiProLight) BrightBlack() gothememe.Color  { return gothememe.Hex("#a59fa0") }
func (t *themeMonokaiProLight) BrightRed() gothememe.Color    { return gothememe.Hex("#e14775") }
func (t *themeMonokaiProLight) BrightGreen() gothememe.Color  { return gothememe.Hex("#269d69") }
func (t *themeMonokaiProLight) BrightYellow() gothememe.Color { return gothememe.Hex("#cc7a0a") }
func (t *themeMonokaiProLight) BrightBlue() gothememe.Color   { return gothememe.Hex("#e16032") }
func (t *themeMonokaiProLight) BrightPurple() gothememe.Color { return gothememe.Hex("#7058be") }
func (t *themeMonokaiProLight) BrightCyan() gothememe.Color   { return gothememe.Hex("#1c8ca8") }
func (t *themeMonokaiProLight) BrightWhite() gothememe.Color  { return gothememe.Hex("#29242a") }

// Code/Syntax highlighting colors
func (t *themeMonokaiProLight) CodeBackground() gothememe.Color  { return gothememe.Hex("#faf4f2") }
func (t *themeMonokaiProLight) CodeText() gothememe.Color        { return gothememe.Hex("#29242a") }
func (t *themeMonokaiProLight) CodeComment() gothememe.Color     { return gothememe.Hex("#a59fa0") }
func (t *themeMonokaiProLight) CodeKeyword() gothememe.Color     { return gothememe.Hex("#7058be") }
func (t *themeMonokaiProLight) CodeString() gothememe.Color      { return gothememe.Hex("#269d69") }
func (t *themeMonokaiProLight) CodeNumber() gothememe.Color      { return gothememe.Hex("#cc7a0a") }
func (t *themeMonokaiProLight) CodeFunction() gothememe.Color    { return gothememe.Hex("#e16032") }
func (t *themeMonokaiProLight) CodeOperator() gothememe.Color    { return gothememe.Hex("#e14775") }
func (t *themeMonokaiProLight) CodePunctuation() gothememe.Color { return gothememe.Hex("#29242a") }
func (t *themeMonokaiProLight) CodeVariable() gothememe.Color    { return gothememe.Hex("#1c8ca8") }
func (t *themeMonokaiProLight) CodeConstant() gothememe.Color    { return gothememe.Hex("#cc7a0a") }
func (t *themeMonokaiProLight) CodeType() gothememe.Color        { return gothememe.Hex("#1c8ca8") }
