// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeIterm2DarkBackgroundInstance is the iTerm2 Dark Background color theme singleton.
var themeIterm2DarkBackgroundInstance gothememe.Theme = &themeIterm2DarkBackground{}

// themeIterm2DarkBackground implements the iTerm2 Dark Background theme.
type themeIterm2DarkBackground struct{}

func (t *themeIterm2DarkBackground) ID() string          { return "iterm2_dark_background" }
func (t *themeIterm2DarkBackground) DisplayName() string { return "iTerm2 Dark Background" }
func (t *themeIterm2DarkBackground) Description() string { return "iTerm2 Dark Background color theme" }
func (t *themeIterm2DarkBackground) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeIterm2DarkBackground) License() string     { return "MIT" }
func (t *themeIterm2DarkBackground) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeIterm2DarkBackground) IsDark() bool { return true }

// Background colors
func (t *themeIterm2DarkBackground) Background() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeIterm2DarkBackground) BackgroundSecondary() gothememe.Color {
	return gothememe.Hex("#000000")
}
func (t *themeIterm2DarkBackground) Surface() gothememe.Color { return gothememe.Hex("#c1deff") }
func (t *themeIterm2DarkBackground) SurfaceSecondary() gothememe.Color {
	return gothememe.Hex("#686868")
}

// Text colors
func (t *themeIterm2DarkBackground) TextPrimary() gothememe.Color   { return gothememe.Hex("#c7c7c7") }
func (t *themeIterm2DarkBackground) TextSecondary() gothememe.Color { return gothememe.Hex("#c7c7c7") }
func (t *themeIterm2DarkBackground) TextMuted() gothememe.Color     { return gothememe.Hex("#686868") }
func (t *themeIterm2DarkBackground) TextInverted() gothememe.Color  { return gothememe.Hex("#000000") }

// Accent/Brand colors
func (t *themeIterm2DarkBackground) Accent() gothememe.Color { return gothememe.Hex("#0225c7") }
func (t *themeIterm2DarkBackground) AccentSecondary() gothememe.Color {
	return gothememe.Hex("#ca30c7")
}
func (t *themeIterm2DarkBackground) Brand() gothememe.Color { return gothememe.Hex("#0225c7") }

// Border colors
func (t *themeIterm2DarkBackground) Border() gothememe.Color       { return gothememe.Hex("#686868") }
func (t *themeIterm2DarkBackground) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeIterm2DarkBackground) BorderStrong() gothememe.Color { return gothememe.Hex("#c7c7c7") }

// Semantic colors
func (t *themeIterm2DarkBackground) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00c200").WithAlpha(0.1),
		Border:     gothememe.Hex("#00c200").WithAlpha(0.3),
		Text:       gothememe.Hex("#00c200"),
	}
}

func (t *themeIterm2DarkBackground) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c7c400").WithAlpha(0.1),
		Border:     gothememe.Hex("#c7c400").WithAlpha(0.3),
		Text:       gothememe.Hex("#c7c400"),
	}
}

func (t *themeIterm2DarkBackground) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#c91b00").WithAlpha(0.1),
		Border:     gothememe.Hex("#c91b00").WithAlpha(0.3),
		Text:       gothememe.Hex("#c91b00"),
	}
}

func (t *themeIterm2DarkBackground) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#00c5c7").WithAlpha(0.1),
		Border:     gothememe.Hex("#00c5c7").WithAlpha(0.3),
		Text:       gothememe.Hex("#00c5c7"),
	}
}

// ANSI colors
func (t *themeIterm2DarkBackground) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeIterm2DarkBackground) Red() gothememe.Color          { return gothememe.Hex("#c91b00") }
func (t *themeIterm2DarkBackground) Green() gothememe.Color        { return gothememe.Hex("#00c200") }
func (t *themeIterm2DarkBackground) Yellow() gothememe.Color       { return gothememe.Hex("#c7c400") }
func (t *themeIterm2DarkBackground) Blue() gothememe.Color         { return gothememe.Hex("#0225c7") }
func (t *themeIterm2DarkBackground) Purple() gothememe.Color       { return gothememe.Hex("#ca30c7") }
func (t *themeIterm2DarkBackground) Cyan() gothememe.Color         { return gothememe.Hex("#00c5c7") }
func (t *themeIterm2DarkBackground) White() gothememe.Color        { return gothememe.Hex("#c7c7c7") }
func (t *themeIterm2DarkBackground) BrightBlack() gothememe.Color  { return gothememe.Hex("#686868") }
func (t *themeIterm2DarkBackground) BrightRed() gothememe.Color    { return gothememe.Hex("#ff6e67") }
func (t *themeIterm2DarkBackground) BrightGreen() gothememe.Color  { return gothememe.Hex("#5ffa68") }
func (t *themeIterm2DarkBackground) BrightYellow() gothememe.Color { return gothememe.Hex("#fffc67") }
func (t *themeIterm2DarkBackground) BrightBlue() gothememe.Color   { return gothememe.Hex("#6871ff") }
func (t *themeIterm2DarkBackground) BrightPurple() gothememe.Color { return gothememe.Hex("#ff77ff") }
func (t *themeIterm2DarkBackground) BrightCyan() gothememe.Color   { return gothememe.Hex("#60fdff") }
func (t *themeIterm2DarkBackground) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themeIterm2DarkBackground) CodeBackground() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeIterm2DarkBackground) CodeText() gothememe.Color       { return gothememe.Hex("#c7c7c7") }
func (t *themeIterm2DarkBackground) CodeComment() gothememe.Color    { return gothememe.Hex("#686868") }
func (t *themeIterm2DarkBackground) CodeKeyword() gothememe.Color    { return gothememe.Hex("#ca30c7") }
func (t *themeIterm2DarkBackground) CodeString() gothememe.Color     { return gothememe.Hex("#00c200") }
func (t *themeIterm2DarkBackground) CodeNumber() gothememe.Color     { return gothememe.Hex("#c7c400") }
func (t *themeIterm2DarkBackground) CodeFunction() gothememe.Color   { return gothememe.Hex("#0225c7") }
func (t *themeIterm2DarkBackground) CodeOperator() gothememe.Color   { return gothememe.Hex("#c91b00") }
func (t *themeIterm2DarkBackground) CodePunctuation() gothememe.Color {
	return gothememe.Hex("#c7c7c7")
}
func (t *themeIterm2DarkBackground) CodeVariable() gothememe.Color { return gothememe.Hex("#00c5c7") }
func (t *themeIterm2DarkBackground) CodeConstant() gothememe.Color { return gothememe.Hex("#fffc67") }
func (t *themeIterm2DarkBackground) CodeType() gothememe.Color     { return gothememe.Hex("#60fdff") }
