// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themePrimaryInstance is the Primary color theme singleton.
var themePrimaryInstance gothememe.Theme = &themePrimary{}

// themePrimary implements the Primary theme.
type themePrimary struct{}

func (t *themePrimary) ID() string          { return "primary" }
func (t *themePrimary) DisplayName() string { return "Primary" }
func (t *themePrimary) Description() string { return "Primary color theme" }
func (t *themePrimary) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themePrimary) License() string     { return "MIT" }
func (t *themePrimary) Source() string      { return "https://github.com/mbadolato/iTerm2-Color-Schemes" }
func (t *themePrimary) IsDark() bool        { return false }

// Background colors
func (t *themePrimary) Background() gothememe.Color          { return gothememe.Hex("#ffffff") }
func (t *themePrimary) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themePrimary) Surface() gothememe.Color             { return gothememe.Hex("#656565") }
func (t *themePrimary) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#000000") }

// Text colors
func (t *themePrimary) TextPrimary() gothememe.Color   { return gothememe.Hex("#000000") }
func (t *themePrimary) TextSecondary() gothememe.Color { return gothememe.Hex("#bfbfbf") }
func (t *themePrimary) TextMuted() gothememe.Color     { return gothememe.Hex("#000000") }
func (t *themePrimary) TextInverted() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Accent/Brand colors
func (t *themePrimary) Accent() gothememe.Color          { return gothememe.Hex("#4285f4") }
func (t *themePrimary) AccentSecondary() gothememe.Color { return gothememe.Hex("#db4437") }
func (t *themePrimary) Brand() gothememe.Color           { return gothememe.Hex("#4285f4") }

// Border colors
func (t *themePrimary) Border() gothememe.Color       { return gothememe.Hex("#000000") }
func (t *themePrimary) BorderSubtle() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themePrimary) BorderStrong() gothememe.Color { return gothememe.Hex("#bfbfbf") }

// Semantic colors
func (t *themePrimary) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#0f9d58").WithAlpha(0.1),
		Border:     gothememe.Hex("#0f9d58").WithAlpha(0.3),
		Text:       gothememe.Hex("#0f9d58"),
	}
}

func (t *themePrimary) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#f4b400").WithAlpha(0.1),
		Border:     gothememe.Hex("#f4b400").WithAlpha(0.3),
		Text:       gothememe.Hex("#f4b400"),
	}
}

func (t *themePrimary) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#db4437").WithAlpha(0.1),
		Border:     gothememe.Hex("#db4437").WithAlpha(0.3),
		Text:       gothememe.Hex("#db4437"),
	}
}

func (t *themePrimary) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#4285f4").WithAlpha(0.1),
		Border:     gothememe.Hex("#4285f4").WithAlpha(0.3),
		Text:       gothememe.Hex("#4285f4"),
	}
}

// ANSI colors
func (t *themePrimary) Black() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themePrimary) Red() gothememe.Color          { return gothememe.Hex("#db4437") }
func (t *themePrimary) Green() gothememe.Color        { return gothememe.Hex("#0f9d58") }
func (t *themePrimary) Yellow() gothememe.Color       { return gothememe.Hex("#f4b400") }
func (t *themePrimary) Blue() gothememe.Color         { return gothememe.Hex("#4285f4") }
func (t *themePrimary) Purple() gothememe.Color       { return gothememe.Hex("#db4437") }
func (t *themePrimary) Cyan() gothememe.Color         { return gothememe.Hex("#4285f4") }
func (t *themePrimary) White() gothememe.Color        { return gothememe.Hex("#bfbfbf") }
func (t *themePrimary) BrightBlack() gothememe.Color  { return gothememe.Hex("#000000") }
func (t *themePrimary) BrightRed() gothememe.Color    { return gothememe.Hex("#db4437") }
func (t *themePrimary) BrightGreen() gothememe.Color  { return gothememe.Hex("#0f9d58") }
func (t *themePrimary) BrightYellow() gothememe.Color { return gothememe.Hex("#f4b400") }
func (t *themePrimary) BrightBlue() gothememe.Color   { return gothememe.Hex("#4285f4") }
func (t *themePrimary) BrightPurple() gothememe.Color { return gothememe.Hex("#4285f4") }
func (t *themePrimary) BrightCyan() gothememe.Color   { return gothememe.Hex("#0f9d58") }
func (t *themePrimary) BrightWhite() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Code/Syntax highlighting colors
func (t *themePrimary) CodeBackground() gothememe.Color  { return gothememe.Hex("#ffffff") }
func (t *themePrimary) CodeText() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themePrimary) CodeComment() gothememe.Color     { return gothememe.Hex("#000000") }
func (t *themePrimary) CodeKeyword() gothememe.Color     { return gothememe.Hex("#db4437") }
func (t *themePrimary) CodeString() gothememe.Color      { return gothememe.Hex("#0f9d58") }
func (t *themePrimary) CodeNumber() gothememe.Color      { return gothememe.Hex("#f4b400") }
func (t *themePrimary) CodeFunction() gothememe.Color    { return gothememe.Hex("#4285f4") }
func (t *themePrimary) CodeOperator() gothememe.Color    { return gothememe.Hex("#db4437") }
func (t *themePrimary) CodePunctuation() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themePrimary) CodeVariable() gothememe.Color    { return gothememe.Hex("#4285f4") }
func (t *themePrimary) CodeConstant() gothememe.Color    { return gothememe.Hex("#f4b400") }
func (t *themePrimary) CodeType() gothememe.Color        { return gothememe.Hex("#0f9d58") }
