// Code generated by themegen. DO NOT EDIT.

package themes

import "github.com/tj-smith47/gothememe"

// themeXcodeLightHcInstance is the Xcode Light hc color theme singleton.
var themeXcodeLightHcInstance gothememe.Theme = &themeXcodeLightHc{}

// themeXcodeLightHc implements the Xcode Light hc theme.
type themeXcodeLightHc struct{}

func (t *themeXcodeLightHc) ID() string          { return "xcode_light_hc" }
func (t *themeXcodeLightHc) DisplayName() string { return "Xcode Light hc" }
func (t *themeXcodeLightHc) Description() string { return "Xcode Light hc color theme" }
func (t *themeXcodeLightHc) Author() string      { return "iTerm2-Color-Schemes" }
func (t *themeXcodeLightHc) License() string     { return "MIT" }
func (t *themeXcodeLightHc) Source() string {
	return "https://github.com/mbadolato/iTerm2-Color-Schemes"
}
func (t *themeXcodeLightHc) IsDark() bool { return false }

// Background colors
func (t *themeXcodeLightHc) Background() gothememe.Color          { return gothememe.Hex("#ffffff") }
func (t *themeXcodeLightHc) BackgroundSecondary() gothememe.Color { return gothememe.Hex("#b4d8fd") }
func (t *themeXcodeLightHc) Surface() gothememe.Color             { return gothememe.Hex("#b4d8fd") }
func (t *themeXcodeLightHc) SurfaceSecondary() gothememe.Color    { return gothememe.Hex("#8a99a6") }

// Text colors
func (t *themeXcodeLightHc) TextPrimary() gothememe.Color   { return gothememe.Hex("#000000") }
func (t *themeXcodeLightHc) TextSecondary() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeXcodeLightHc) TextMuted() gothememe.Color     { return gothememe.Hex("#8a99a6") }
func (t *themeXcodeLightHc) TextInverted() gothememe.Color  { return gothememe.Hex("#ffffff") }

// Accent/Brand colors
func (t *themeXcodeLightHc) Accent() gothememe.Color          { return gothememe.Hex("#0058a1") }
func (t *themeXcodeLightHc) AccentSecondary() gothememe.Color { return gothememe.Hex("#9c2191") }
func (t *themeXcodeLightHc) Brand() gothememe.Color           { return gothememe.Hex("#0058a1") }

// Border colors
func (t *themeXcodeLightHc) Border() gothememe.Color       { return gothememe.Hex("#8a99a6") }
func (t *themeXcodeLightHc) BorderSubtle() gothememe.Color { return gothememe.Hex("#b4d8fd") }
func (t *themeXcodeLightHc) BorderStrong() gothememe.Color { return gothememe.Hex("#000000") }

// Semantic colors
func (t *themeXcodeLightHc) Success() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#355d61").WithAlpha(0.1),
		Border:     gothememe.Hex("#355d61").WithAlpha(0.3),
		Text:       gothememe.Hex("#355d61"),
	}
}

func (t *themeXcodeLightHc) Warning() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#78492a").WithAlpha(0.1),
		Border:     gothememe.Hex("#78492a").WithAlpha(0.3),
		Text:       gothememe.Hex("#78492a"),
	}
}

func (t *themeXcodeLightHc) Error() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#ad1805").WithAlpha(0.1),
		Border:     gothememe.Hex("#ad1805").WithAlpha(0.3),
		Text:       gothememe.Hex("#ad1805"),
	}
}

func (t *themeXcodeLightHc) Info() gothememe.SemanticColor {
	return gothememe.SemanticColor{
		Background: gothememe.Hex("#703daa").WithAlpha(0.1),
		Border:     gothememe.Hex("#703daa").WithAlpha(0.3),
		Text:       gothememe.Hex("#703daa"),
	}
}

// ANSI colors
func (t *themeXcodeLightHc) Black() gothememe.Color        { return gothememe.Hex("#b4d8fd") }
func (t *themeXcodeLightHc) Red() gothememe.Color          { return gothememe.Hex("#ad1805") }
func (t *themeXcodeLightHc) Green() gothememe.Color        { return gothememe.Hex("#355d61") }
func (t *themeXcodeLightHc) Yellow() gothememe.Color       { return gothememe.Hex("#78492a") }
func (t *themeXcodeLightHc) Blue() gothememe.Color         { return gothememe.Hex("#0058a1") }
func (t *themeXcodeLightHc) Purple() gothememe.Color       { return gothememe.Hex("#9c2191") }
func (t *themeXcodeLightHc) Cyan() gothememe.Color         { return gothememe.Hex("#703daa") }
func (t *themeXcodeLightHc) White() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeXcodeLightHc) BrightBlack() gothememe.Color  { return gothememe.Hex("#8a99a6") }
func (t *themeXcodeLightHc) BrightRed() gothememe.Color    { return gothememe.Hex("#ad1805") }
func (t *themeXcodeLightHc) BrightGreen() gothememe.Color  { return gothememe.Hex("#174145") }
func (t *themeXcodeLightHc) BrightYellow() gothememe.Color { return gothememe.Hex("#78492a") }
func (t *themeXcodeLightHc) BrightBlue() gothememe.Color   { return gothememe.Hex("#003f73") }
func (t *themeXcodeLightHc) BrightPurple() gothememe.Color { return gothememe.Hex("#9c2191") }
func (t *themeXcodeLightHc) BrightCyan() gothememe.Color   { return gothememe.Hex("#441ea1") }
func (t *themeXcodeLightHc) BrightWhite() gothememe.Color  { return gothememe.Hex("#000000") }

// Code/Syntax highlighting colors
func (t *themeXcodeLightHc) CodeBackground() gothememe.Color  { return gothememe.Hex("#ffffff") }
func (t *themeXcodeLightHc) CodeText() gothememe.Color        { return gothememe.Hex("#000000") }
func (t *themeXcodeLightHc) CodeComment() gothememe.Color     { return gothememe.Hex("#8a99a6") }
func (t *themeXcodeLightHc) CodeKeyword() gothememe.Color     { return gothememe.Hex("#9c2191") }
func (t *themeXcodeLightHc) CodeString() gothememe.Color      { return gothememe.Hex("#355d61") }
func (t *themeXcodeLightHc) CodeNumber() gothememe.Color      { return gothememe.Hex("#78492a") }
func (t *themeXcodeLightHc) CodeFunction() gothememe.Color    { return gothememe.Hex("#0058a1") }
func (t *themeXcodeLightHc) CodeOperator() gothememe.Color    { return gothememe.Hex("#ad1805") }
func (t *themeXcodeLightHc) CodePunctuation() gothememe.Color { return gothememe.Hex("#000000") }
func (t *themeXcodeLightHc) CodeVariable() gothememe.Color    { return gothememe.Hex("#703daa") }
func (t *themeXcodeLightHc) CodeConstant() gothememe.Color    { return gothememe.Hex("#78492a") }
func (t *themeXcodeLightHc) CodeType() gothememe.Color        { return gothememe.Hex("#441ea1") }
