// Command syntaxgen generates syntax highlighting CSS from gothememe themes.
//
// Usage:
//
//	syntaxgen [flags]
//
// Flags:
//
//	-theme string
//	      Theme ID to generate CSS for (default "dracula_pro")
//	-format string
//	      Syntax format: chroma, prism, highlightjs (default "chroma")
//	-output string
//	      Output file (default: stdout)
//	-variables
//	      Use CSS variables instead of inline colors
//	-minify
//	      Minify output
//	-list
//	      List available themes
//
// Example:
//
//	syntaxgen -theme dracula_pro -format chroma > syntax.css
//	syntaxgen -theme nord -format prism -output nord-prism.css
//	syntaxgen -list
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/tj-smith47/gothememe"
	"github.com/tj-smith47/gothememe/themes"
)

// Version information set by goreleaser.
var (
	Version = "dev"
	Commit  = "none"
	Date    = "unknown"
)

func main() {
	var (
		themeID      = flag.String("theme", "dracula_pro", "Theme ID to generate CSS for")
		format       = flag.String("format", "chroma", "Syntax format: chroma, prism, highlightjs")
		output       = flag.String("output", "", "Output file (default: stdout)")
		useVariables = flag.Bool("variables", false, "Use CSS variables instead of inline colors")
		minify       = flag.Bool("minify", false, "Minify output")
		listThemes   = flag.Bool("list", false, "List available themes")
		version      = flag.Bool("version", false, "Print version information")
	)

	flag.Parse()

	if *version {
		fmt.Printf("syntaxgen %s (%s) built %s\n", Version, Commit, Date)
		os.Exit(0)
	}

	if *listThemes {
		printThemeList()
		os.Exit(0)
	}

	// Get theme
	theme := themes.ByID(*themeID)
	if theme == nil {
		fmt.Fprintf(os.Stderr, "Error: theme %q not found\n", *themeID)
		fmt.Fprintf(os.Stderr, "Use -list to see available themes\n")
		os.Exit(1)
	}

	// Determine syntax format
	var syntaxFormat gothememe.SyntaxFormat
	switch strings.ToLower(*format) {
	case "chroma":
		syntaxFormat = gothememe.SyntaxChroma
	case "prism":
		syntaxFormat = gothememe.SyntaxPrism
	case "highlightjs", "hljs":
		syntaxFormat = gothememe.SyntaxHighlightJS
	default:
		fmt.Fprintf(os.Stderr, "Error: unknown format %q (use: chroma, prism, highlightjs)\n", *format)
		os.Exit(1)
	}

	// Generate CSS
	opts := gothememe.SyntaxOptions{
		Format:       syntaxFormat,
		UseVariables: *useVariables,
		Minify:       *minify,
	}

	css := gothememe.GenerateSyntaxCSS(theme, opts)

	// Add header comment if not minified
	if !*minify {
		header := fmt.Sprintf("/* %s Syntax Highlighting for %s */\n/* Generated by gothememe syntaxgen */\n\n",
			theme.DisplayName(), formatName(syntaxFormat))
		css = header + css
	}

	// Write output
	if *output != "" {
		if err := os.WriteFile(*output, []byte(css), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Generated %s (%d bytes)\n", *output, len(css))
	} else {
		fmt.Print(css)
	}
}

func formatName(f gothememe.SyntaxFormat) string {
	switch f {
	case gothememe.SyntaxChroma:
		return "Chroma"
	case gothememe.SyntaxPrism:
		return "Prism.js"
	case gothememe.SyntaxHighlightJS:
		return "Highlight.js"
	default:
		return "Unknown"
	}
}

func printThemeList() {
	allThemes := themes.All()

	// Sort by ID
	sort.Slice(allThemes, func(i, j int) bool {
		return allThemes[i].ID() < allThemes[j].ID()
	})

	fmt.Printf("Available themes (%d total):\n\n", len(allThemes))

	// Group by first letter for readability
	currentLetter := ""
	for _, t := range allThemes {
		firstLetter := strings.ToUpper(string(t.ID()[0]))
		if firstLetter != currentLetter {
			if currentLetter != "" {
				fmt.Println()
			}
			currentLetter = firstLetter
			fmt.Printf("── %s ──\n", currentLetter)
		}

		darkLight := "dark"
		if !t.IsDark() {
			darkLight = "light"
		}
		fmt.Printf("  %-30s %s (%s)\n", t.ID(), t.DisplayName(), darkLight)
	}
}
